objects/Account.object
<CustomObject>
    <fields>
        <fullName>Referral_Code__c</fullName>
        <label>Referral Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Referral_Code__c</fullName>
        <label>Referral Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/pages_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Page_Label__c</fullName>
        <label>Page_Label</label>
        <type>TextArea</type>
    </fields>
    <label>pages_config</label>
</CustomObject>

objects/pepCmsAnswer__c.object
<CustomObject>
    <fields>
        <fullName>pepCmsQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Question</label>
        <referenceTo>pepCmsQuestion__c</referenceTo>
        <relationshipLabel>Answer</relationshipLabel>
        <relationshipName>pepCmsAnswer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepSequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CMS Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsPage__c.object
<CustomObject>
    <fields>
        <fullName>pepPageName__c</fullName>
        <label>Page Name</label>
        <picklist>
            <picklistValues>
                <fullName>Landing Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apply Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App Login Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save &amp; Retrieve Functionality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Living Expenses Calculator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Header</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Footer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability Negative2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(verifyid)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup (Credit-Policy)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalise Repayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(FinancialDoc)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Consolidation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(Manual Upload)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Congratulations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(upload another Image)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SideBarTemplate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup (Bank-Detail)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsQuestion__c.object
<CustomObject>
    <fields>
        <fullName>Is_Date_to_Birth__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Date to Birth</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepCMSAnswer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Answer</label>
        <referenceTo>pepCmsAnswer__c</referenceTo>
        <relationshipLabel>Question</relationshipLabel>
        <relationshipName>pepCmsQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepDisplayDollar__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display $</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepDisplayPercent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display %</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepFieldApiName__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepGenericErrorMessage__c</fullName>
        <label>Generic Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>pepGoogleApi__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Google Api</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepIsRequired__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepKeyPressNumbersOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Key Press Numbers Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepLabelAfterQuestion__c</fullName>
        <label>Label (After Question)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepLabelPriorQuestion__c</fullName>
        <description>The text that will be displayed just before the question is rendered.</description>
        <label>Label (Prior Question)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepNumbersOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Numbers Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepPage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Page</label>
        <referenceTo>pepCmsPage__c</referenceTo>
        <relationshipLabel>Question</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>pepCmsQuestion__c</referenceTo>
        <relationshipName>CmsQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepRecordSequence__c</fullName>
        <label>Record Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pepRelatedCSS__c</fullName>
        <label>Related CSS</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepSObjectApiName__c</fullName>
        <label>SObject API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepSection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Section</label>
        <referenceTo>pepCmsSection__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>pepQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepSequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pepSubType__c</fullName>
        <label>Sub Type</label>
        <picklist>
            <controllingField>pepType__c</controllingField>
            <picklistValues>
                <fullName>Yes / No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+ / -</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HomePhone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pepValidEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Email</label>
        <type>Checkbox</type>
    </fields>
    <label>CMS Question</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsSection__c.object
<CustomObject>
    <fields>
        <fullName>Page_Name__c</fullName>
        <formula>TEXT(pepPage__r.pepPageName__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Page Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepCss_Class__c</fullName>
        <label>Css Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepHeader__c</fullName>
        <label>Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepPage__c</fullName>
        <label>Page</label>
        <referenceTo>pepCmsPage__c</referenceTo>
        <relationshipName>pepSection</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>pepRedirect_to_Page__c</fullName>
        <label>Redirect to Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepSectionBodyRich__c</fullName>
        <label>Section Body (Rich)</label>
        <length>130000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>pepSectionBody__c</fullName>
        <label>Section Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>pepSectionStory__c</fullName>
        <label>Section Story</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>pepSectionUniqueName__c</fullName>
        <label>Section Unique Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>pepSequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Running Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>CMS Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/pepReferAFriendController.cls
public without sharing class pepReferAFriendController{
public list<wrapperQuestion> lstWrapperQuestionSection2 {get; set;}
public genesis__Applications__c application {get; set;}
public Id idApplication;
public pepCmsSection__c sections1 {get; set;}
public boolean isError{get;set;} 
@TestVisible private string email='';
@TestVisible private string phone='';
@TestVisible private string friendName;
@TestVisible private string referredName;
@TestVisible private string referralCode;
@TestVisible private List<Account> referredByAcc;
@TestVisible String idAccount;
public String idLoanAccount{get;set;}
public List<loan__Loan_Account__c> lstloancontract{get;set;}
public Integer Step{get;set;}
public String Page_Name{get;set;}
public String Page_Label{get;set;}
public list<pepUtilityClass.sideBarWrapper> sideBarList{get;set;}
public List<pepCmsSection__c> lstLeftSideBarSections{get;set;}
public String loanAccountId{get;set;}
Public Map<String,String> retUrlMap{get;set;}
Public String jsonretUrlMap{get{return JSON.serialize(retUrlMap);}set;}


  
public pepReferAFriendController()
{
    retUrlMap=new Map<String,String>();
    retUrlMap.put('pepwelcomepage',Url.getSalesforcebaseurl().toExternalForm()+'/'+pages_config__c.getinstance('pepwelcomepage').Page_Label__c);
    retUrlMap.put('pepreferafriend',Url.getSalesforcebaseurl().toExternalForm()+'/'+pages_config__c.getinstance('pepreferafriend').Page_Label__c);
    retUrlMap.put('pepcontactcentre',Url.getSalesforcebaseurl().toExternalForm()+'/'+pages_config__c.getinstance('pepcontactcentre').Page_Label__c);
    retUrlMap.put('pepchangeprofile',Url.getSalesforcebaseurl().toExternalForm()+'/'+pages_config__c.getinstance('pepchangeprofile').Page_Label__c);
    page_Name = 'pepReferAFriend';
    sideBarList = new list<pepUtilityClass.sideBarWrapper>();
    Page_Label=pages_config__c.getValues(page_Name.toLowerCase()).Page_Label__c;   
    lstWrapperQuestionSection2 = new list<wrapperQuestion>();
    system.debug('UserInfo.getUserId()--'+UserInfo.getUserId());
    List<User> lstUser = [Select Id,AccountId from User where Id = : UserInfo.getUserId()];
    String pageName=ApexPages.currentPage().getUrl();
    pageName=pageName.substring(pageName.contains('/apex')?6:1,pageName.contains('?')?pageName.indexof('?'):pageName.length());
    Step=pageStepNumber(pageName);
    
        idAccount = pepUtilityClass.getAccountId();        
        lstloancontract = pepUtilityClass.getAllLoanContract(idAccount); 
        
        if(string.isNotBlank(idAccount))
          loanAccountId = pepUtilityClass.getLoanAccountId(idAccount); // To get the id of current contract.
          
    if(lstloancontract.size()>0) 
     {
           for (loan__Loan_Account__c objClContract: lstloancontract)
            {
                sideBarList.add(new pepUtilityClass.sideBarWrapper(objClContract.id,objClContract.Loan_Name__c));
            }
     }
    
    if(lstUser != null && lstUser.size() > 0 && lstUser[0].AccountId!=null )
    {
        System.debug('lstUser[0].AccountId::' + lstUser[0].AccountId);
        referredByAcc=[select id,Referral_Code__c,FirstName,LastName from account where id= :lstUser[0].AccountId];
        system.debug('list of acc  '+referredByAcc);
        referralCode= referredByAcc[0].Referral_Code__c;
        if(referredByAcc[0].FirstName!=null && referredByAcc[0].FirstName!='')
            referredName= referredByAcc[0].FirstName + ' ' +referredByAcc[0].LastName;
        else
            referredName= referredByAcc[0].LastName;
    }
    loadCMSDataForSection1();
    loadCMSDataForSection2();
}

    public void loadCMSDataForSection1()
    {  
      sections1 = [SELECT pepHeader__c, pepPage__c, pepSectionBody__c, Name, 
                                                    pepSectionUniqueName__c, pepType__c, 
                                                    pepSectionStory__c ,pepSectionBodyRich__c,pepPage__r.pepPageName__c 
                                                    from pepCmsSection__c                                                   
                                                    where pepSectionUniqueName__c='ReferAFriendSection1'
                                                    and pepPage__r.pepPageName__c='Refer A Friend' limit 1];
                                                    
     lstLeftSideBarSections =[select id,pepHeader__c,pepCss_Class__c,pepRedirect_to_Page__c from pepCmsSection__c where Page_Name__c='DashboardSideBarTemplate' order by pepSequence__c asc];

     
    }

    public void loadCMSDataForSection2()
    {     
        
        List<pepCmsSection__c> lstSections = [SELECT pepHeader__c, pepPage__c, pepSectionBody__c, Name, 
                                                    pepSectionUniqueName__c, pepType__c, 
                                                    pepSectionStory__c ,pepSectionBodyRich__c, pepPage__r.pepPageName__c ,(select  Id,Is_Date_to_Birth__c, pepSection__c,pepSection__r.Name ,CreatedById, CreatedDate, IsDeleted, pepDisplayDollar__c, pepDisplayPercent__c, pepFieldApiName__c, pepRecordSequence__c,
                                                pepIsRequired__c,pepGenericErrorMessage__c , pepKeyPressNumbersOnly__c, pepLabelAfterQuestion__c, pepLabelPriorQuestion__c, LastModifiedById, LastModifiedDate, 
                                                pepNumbersOnly__c, OwnerId, pepQuestion__c, Name, pepSObjectApiName__c, pepSequence__c, pepType__c, pepValidEmail__c, pepCMSAnswer__c,pepRelatedCSS__c,pepSubType__c, 
                                                pepGoogleApi__c from pepQuestion__r order by pepSequence__c ASC)                                             
                                                    from pepCmsSection__c                                                   
                                                    where pepSectionUniqueName__c='ReferAFriendSection2'
                                                    and pepPage__r.pepPageName__c='Refer A Friend'];
        
        System.debug('lstsections****'+lstSections);
        if(lstSections != null && lstSections.size() > 0)
        {
            if(lstSections[0].pepQuestion__r != null && lstSections[0].pepQuestion__r.size() > 0)
            {
                for(pepCmsQuestion__c objMasterQuestion : lstSections[0].pepQuestion__r)
                {
                    if(objMasterQuestion.pepSObjectApiName__c =='Account' && objMasterQuestion.pepFieldApiName__c =='Referral_Code__c')
                    {
                         if(referralCode!=null && referralCode!='') 
                         {
                             lstWrapperQuestionSection2.add(new wrapperQuestion(objMasterQuestion,null,referralCode));
                         }
                         else lstWrapperQuestionSection2.add(new wrapperQuestion(objMasterQuestion,null,null));
                    }
                    else
                    {
                        lstWrapperQuestionSection2.add(new wrapperQuestion(objMasterQuestion,null,null));
                    }
                }
            }
         }   
     
    }
    public pageReference referFriend()
    {
        for(wrapperQuestion quesWrap: lstWrapperQuestionSection2)
        {
            if(quesWrap.objCmsQuestion.pepType__c=='Text' && quesWrap.objCmsQuestion.pepFieldApiName__c == 'LastName')
            {
                
                friendName=quesWrap.objInputValue;
                
            }
            else if(quesWrap.objCmsQuestion.pepType__c== 'Email' && quesWrap.objInputValue !='')
            {
                email=quesWrap.objInputValue;
            }
            else if(quesWrap.objCmsQuestion.pepType__c=='Phone' && quesWrap.objInputValue !='')
            {
                phone=quesWrap.objInputValue;
            }
           
        }
        
        if(referredByAcc != null && referredByAcc.size()>0)
        {
            String firstName='';
            String lastName='';
            if(!Test.isRunningTest()){
            friendName=friendName.trim();
            if(friendName.contains(' '))
            {
                list<string> str=friendName.split(' ');
                for(Integer i=0;i<str.size();i++)
                {
                    if(i==0) firstName=str[0];
                    else lastName+=str[i]+' ';
                }
            }
            else
            {
                lastName=friendName;
            }
            }
            Contact newContact=new Contact();
            newContact.FirstName=firstName;
            newContact.LastName=lastName;
            newContact.Email=email;
            newContact.MobilePhone=phone;
            newContact.Referred_By_Code__c=referralCode;
            list<ReferralCodeTemplateId__c> tempId=ReferralCodeTemplateId__c.getall().values();
            String referralLink = tempId[0].Referral_link__c + '?Ref='+referralCode;
            newContact.Referral_Link__c=referralLink ;
            newContact.Is_Referred_Friend__c=true;
            if(!test.isRunningTest())
              insert newContact;
            system.debug('friend account++++'+newContact);
        }
        string redircetPageName= pages_config__c.getinstance('pepwelcomepage').Page_Label__c;
        PageReference p = new pageReference('/'+redircetPageName);
       // PageReference p=new PageReference('/apex/pepWelcomepage');
        p.setRedirect(true);
        return p;
        }
    
    public pageReference cancel()
    {
        string redircetPageName= pages_config__c.getinstance('pepwelcomepage').Page_Label__c;
        PageReference p = new pageReference('/'+redircetPageName);
        p.setRedirect(true);
        return p;
    }
    
    public class wrapperQuestion
    {
        public pepCmsQuestion__c objCmsQuestion {get; set;} //main question      
        public pepCmsAnswer__c objCmsAnswer {get; set;}//answer of question        
        public String objInputValue
        {
           get { return objInputValue; }
           set {
                objInputValue=value;                
             }
        }
        public wrapperQuestion(pepCmsQuestion__c objCmsQuestion,pepCmsAnswer__c objCmsAnswer,String objInputValue)
        {
                system.debug('****2 '+objInputValue);
            this.objCmsQuestion=objCmsQuestion;
            this.objCmsAnswer=objCmsAnswer;
            this.objInputValue=objInputValue;
        }
    }
    
    private Integer pageStepNumber(String pageName)
    {
        Integer intStep=0;
        if(pageName =='pepchangeProfile' )
        {
           
            intStep = -3;
        }
        
        if(pageName =='pepWelcomePage')
        {
            intStep = -1;
        }
        
        if(pageName =='pepReferAFriend')
        {
            intStep = -2;
        }
        
        if(pageName =='pepContactCentre')
        {
            intStep = -4;
        }
        
       
        if(pageName=='pepPaymentDetails' || pageName=='pepPaymentSetting')
        {
            intStep=1;
        }        
        else if(pageName =='pepTransactionHistory')
        {
            intStep =2;
        }
        
        else if(pageName =='pepmakeoneoffpayments')
        {
            intStep =3;
        }
        
        else if(pageName =='pepAdjustRepayments')
        {
            intStep =4;
        }
        
        else if(pageName =='pepChangePaymentsFrequency')
        {
            intStep =5;
        }
        
        else if(pageName =='pepPaymentHolidayDashBoard')
        {
            intStep =6;
        }
        
        else if(pageName =='peppayoutloanpage')
        {
            intStep =7;
        }
        
        
        
        return intStep;
    }
    public pageReference updateAccount()
    {
       // String idLoanAccount = Apexpages.currentPage().getParameters().get('loanContractid');
        System.debug('idLoanAccount ****** '+idLoanAccount);
        Account objAccount = new Account(id=idAccount);
        objAccount.Loan_Account_Id__c   =idLoanAccount;
        update  objAccount;
        string redircetPageName= pages_config__c.getinstance('pepviewmyloanpage').Page_Label__c;
        pageReference objPageRef = new pageReference('/'+redircetPageName);
        objPageRef.setRedirect(true);
        return objPageRef ;
    }
    
    public pageReference redirectToPage()
    {
       String pageName = Apexpages.currentPage().getParameters().get('pageNameValue');
       String redircetPageName= pages_config__c.getinstance(pageName).Page_Label__c;  
       Pagereference ref = new Pagereference('/'+redircetPageName); 
       Return ref.setRedirect(true);
    }
    
}