objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACN__c</fullName>
        <label>ACN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepPepperCustomSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_Hours__c</fullName>
        <label>Operating Hours</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PepperMoneyContact__c</fullName>
        <label>PepperMoneyContact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acn__c</fullName>
        <label>acn</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>creditbodyname__c</fullName>
        <label>creditbodyname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>creditbodyurl__c</fullName>
        <label>creditbodyurl</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>displayname__c</fullName>
        <label>displayname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepAppEmailId__c</fullName>
        <label>pepAppEmailId</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>pepCall__c</fullName>
        <label>Call</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>replyemailId__c</fullName>
        <label>replyemailId</label>
        <type>Email</type>
    </fields>
    <label>PepperCustomSetting</label>
</CustomObject>

classes/pafss_TestSendNewUserEmailController.cls
//  -------------------------------------------------------------------------------------------------------
//  This class serves as the test class for pafss_SendNewUserEmailController
//  -------------------------------------------------------------------------------------------------------
//  Created Date : 01-FEB-2017          Created By: Sandeep Bijlwan         Email: sandeep.bijlwan@saasfocus.com
//  -------------------------------------------------------------------------------------------------------
@isTest(SeeAllData=False) 
public class pafss_TestSendNewUserEmailController
{
    @isTest static void test0()
    {    
        collect__Source_System__c objSource = ScCollection_CommonTrackerClass.createTestSourceSystem('PAF');
        collect__Loan_Account__c objLoanAcc = ScCollection_CommonTrackerClass.createTestContract(objSource.id);
        
        Account acc = new Account();
        acc.LastName = 'testAc';
        acc.PersonEmail = 'san@bijlwan.com';
        insert acc;
        
        pepPepperCustomSetting__c objCust = new pepPepperCustomSetting__c ();
        objCust.acn__c = '094317665';
        objCust.pepCall__c = '13 73 77';
        objCust.Company_Name__c= 'Pepper Group Ltd';
        objCust.creditbodyname__c= 'veda';
        objCust.creditbodyurl__c= 'http://www.veda.com.au';
        objCust.displayname__c= 'Pepper Money';
        objCust.Operating_Hours__c= '8:30 AM to 5:30 PM';
        objCust.pepAppEmailId__c= 'plapplications@pepper.com.au';
        objCust.PepperMoneyContact__c= '1300 659 620';
        objCust.replyemailId__c = 'noreply@pepper.com.au';
        objCust.SetupOwnerId=UserInfo.getOrganizationId();
        insert objCust;
        
        clcommon__Party__c objParty = new clcommon__Party__c ();
        objParty.collect__CL_Contract__c = objLoanAcc.id;
        objParty.clcommon__Account__c = acc.id;
        insert objParty;
        
        pafss_SendNewUserEmailController obj = new pafss_SendNewUserEmailController();
        pafss_SendNewUserEmailController.sendNewUserEmail(objParty.id);
    }
}