objects/Account.object
<CustomObject>
    <fields>
        <fullName>Current_Application_Id__c</fullName>
        <label>Current Application Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking_Id__c</fullName>
        <label>Tracking Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pages_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Page_Label__c</fullName>
        <label>Page_Label</label>
        <type>TextArea</type>
    </fields>
    <label>pages_config</label>
</CustomObject>

objects/RetrieveCode__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RetrieveCode</label>
</CustomObject>

classes/pepJumioFailureControllerTracker.cls
@isTest

public class pepJumioFailureControllerTracker
{

   private static  Account objAccount;
   private static genesis__Applications__c objApplication;  
   private static  void loadData()
   {
       createApplication();
       createAccount();  
       
   }
   
   //This method creates account
   private static void createAccount()
   {     
     objAccount=  pepCommonTrackerController.createAccount();
     objAccount.Current_Application_Id__c = objApplication.id;
     objAccount.Tracking_Id__c  ='1234';
     update objAccount;     
       
   }
   //This method creates Application
   private static void createApplication()
   {
       RetrieveCode__c objRetrieveCode = pepCommonTrackerController.createRetrieveCode();      
       objApplication =genesis.TestHelper.createApplication();
       
        pages_config__c objConfig = new pages_config__c();
                   objConfig.Page_Label__c='loanSetupManualUpload';
                   objConfig.Name='peploansetupmanualupload';
                   insert objConfig;
       
   }
   
   static testmethod void unitTest1()
   {
       Test.startTest();
       loadData();
       ApexPages.Currentpage().getParameters().put('jumioIdScanReference','1234');
       pepJumioFailureController  objController = new pepJumioFailureController();
       objController.redirect();
       Test.stopTest();
   }



}