objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <label>Customer Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Stacktrace__c</fullName>
        <label>Error_Stacktrace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Line__c</fullName>
        <label>Line</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{DDMMYY}-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SCV_CustomerNumberAction.cls
public class SCV_CustomerNumberAction {

	@InvocableMethod(label='Assign Unique Customer IDs' description='Assign 8-10 digits unique customer numbers.')
    public static void assignCustomerIds(List<Account> accountsToUpdate) {
        
        List<Account> accounts = [SELECT Id, Customer_Id__c
        						FROM Account 
            					WHERE Id IN :new Map<Id, Account>(accountsToUpdate).keySet()
            					AND Customer_Id__c = null
            					];

		for(Account acc : accounts) {
			if (acc.Customer_Id__c == null) {
                acc.Customer_Id__c = SCV_Utility.generateCustomerNumber(acc.Id);
			}
		}

        try {
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.AllowSave = true;
            List<Database.SaveResult> sr = Database.update(accounts, dml);

            /*if (!sr.isSuccess()) {
                string strErr = 'Contact_Merge_Error_Merge_Failed' + ' Error: ';
                for (Database.Error err : sr.getErrors()) {
                    strErr += err.getMessage() + '\n';
                }
            }*/

        } catch (Exception ex) {
            //Handle exceptions
            System.debug('@Exception: ' + ex);

            //Log errors
            Error_Log__c error = new Error_Log__c();
            error.Error_Stacktrace__c = ex.getStackTraceString();
            error.Line__c = ex.getLineNumber();
            error.Type__c = ex.getTypeName();
            error.Error_Message__c = ex.getMessage();
            insert error;
        }

    }

}