objects/Account.object
<CustomObject>
    <fields>
        <fullName>pepIsDummyAccount__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Dummy Account</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Application__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to save the stage of pages after click on continue button.</description>
    <fields>
        <fullName>Navigation_Status__c</fullName>
        <label>Navigation Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RedirectPage__c</fullName>
        <label>RedirectPage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Navigation Status</label>
</CustomObject>

objects/Captcha_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Captcha Settings</description>
    <label>Captcha Settings</label>
</CustomObject>

objects/OTP_Template__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>OTP Template</label>
</CustomObject>

objects/pages_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Page_Label__c</fullName>
        <label>Page_Label</label>
        <type>TextArea</type>
    </fields>
    <label>pages_config</label>
</CustomObject>

objects/pepCmsPage__c.object
<CustomObject>
    <label>CMS Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsQuestion__c.object
<CustomObject>
    <fields>
        <fullName>pepFieldApiName__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepRecordSequence__c</fullName>
        <label>Record Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CMS Question</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsSection__c.object
<CustomObject>
    <label>CMS Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>CMS Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Residential_Address__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>genesis__Applications__c</referenceTo>
        <relationshipLabel>Residential Address</relationshipLabel>
        <relationshipName>Residential_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Residential Address</label>
    <nameField>
        <displayFormat>RA - {0000}</displayFormat>
        <label>Residential Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residential Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RetrieveCode__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RetrieveCode</label>
</CustomObject>

classes/pepPersonalDetailsController_Tracker.cls
@isTest(SeeAllData=False)

private class pepPersonalDetailsController_Tracker 
{
    
    @isTest static void pepPersonalDetailsControllerTest0() {
        
        pepCommonTrackerController obj =new pepCommonTrackerController();
        pages_config__c pg1 = new pages_config__c(Name='peppersonaldetails',Page_Label__c='PersonalDetails');
            insert pg1;
            pages_config__c pg11 = new pages_config__c(Name='pepexpensepage',Page_Label__c='ExpensePage');
            insert pg11;
            pages_config__c pg12 = new pages_config__c(Name='pepincomepage',Page_Label__c='IncomePage');
            insert pg12;
            pages_config__c pg13 = new pages_config__c(Name='peploandetails',Page_Label__c='loandetails');
            insert pg13;
            pages_config__c pg14 = new pages_config__c(Name='pepreferredpage',Page_Label__c='ReferredPage');
            insert pg14;
            pages_config__c pg15 = new pages_config__c(Name='pepreferredpage',Page_Label__c='ReferredPage');
            insert pg15;
            pages_config__c pg16 = new pages_config__c(Name='pepserviceabilitydecline',Page_Label__c='serviceabilitydecline');
            insert pg16;
            pages_config__c pg17 = new pages_config__c(Name='pepgenericredirection',Page_Label__c='GenericRedirection');
            insert pg17;
            pages_config__c pg18 = new pages_config__c(Name='pepotp',Page_Label__c='OTP');
            insert pg18;
            
            Application__c app1 = new Application__c(Name='pepOTP', RedirectPage__c='pepOTP', Navigation_Status__c='OTP');
            insert app1;
            
            
            Application__c app2 = new Application__c(Name='pepofferscreen', RedirectPage__c='pepofferscreen', Navigation_Status__c='OfferScreen');
            insert app2;
            pages_config__c pg19 = new pages_config__c(Name='pepofferscreen',Page_Label__c='OfferScreen');
            insert pg19;
        Captcha_Settings__c captchaSetting =  pepCommonTrackerController.createCaptchaSetting();
        Account acc= pepCommonTrackerController.createAccount();
        acc.pepIsDummyAccount__c =  false;
        acc.LastName = 'Sharma';
        update acc;
        
       test.startTest();
        genesis__Applications__c objApplication = new genesis__Applications__c();
        RetrieveCode__c objRetrieveCode = pepCommonTrackerController.createRetrieveCode();
        objApplication = genesis.TestHelper.createApplication();
        genesis.TestHelper.createApplication(); 
        objApplication.Debit_Frequency__c ='bi-weekly';
        objApplication.genesis__Account__c = acc.id;
        objApplication.Serviceability_Status__c = 'Approved';
        objApplication.pepLastSaved__c = system.now();
        update objApplication; 
       
        Pagereference pd=Page.pepLoanSetupUploadedDocs;
        Test.setcurrentPagereference(pd);
        Cookie Applicationid=new Cookie('Applicationid',pepEncryptDecryptData.EncryptData(String.valueof(objApplication.id)),'-1',null,false);
        pd.setcookies(new cookie[]{Applicationid});
     test.stopTest();   
        ApexPages.currentPage().getHeaders().put('X-Salesforce-SIP','192.168.2.1');
        ApexPages.currentPage().getParameters().put('redirectFromPageNo','2');
        
        Residential_Address__c resAdd = pepCommonTrackerController.createResidential();
        resAdd.Application__c = objApplication.id;
        update resAdd;
        
        genesis__Employment_Information__c empInfo = pepCommonTrackerController.employmentInformation();
        empInfo.genesis__Application__c = objApplication.id;
        empInfo.Sequence__c = 5;
        update empInfo;
         
        pepCmsPage__c objPage1 = pepCommonTrackerController.createPage('pepLoanSetupUploadedDocs');
        
        //Section Creation
        pepCmsSection__c objSection1 = new pepCmsSection__c();
        objSection1 = pepCommonTrackerController.createSection1(objPage1);
        
        //Question Creation       
        pepCmsQuestion__c objQuestion2 = pepCommonTrackerController.createCmsQuestion(objPage1,objSection1);   
        objQuestion2.pepFieldApiName__c='Residential_Address__c';
        objQuestion2.pepRecordSequence__c=2;
        update objQuestion2;
        
        //update objModel;
        
        OTP_Template__c temp = pepCommonTrackerController.createOTPTemplate();
      
        pepCMSModelContainer_New newIncome = new pepCMSModelContainer_New();
        newIncome.objApplication = objApplication;
        newIncome.objAccount = acc;
        newIncome.objAccount.PersonEmail = acc.PersonEmail;
        newIncome.objAccount.PersonMobilePhone = acc.PersonMobilePhone;
        
        List<pepCMSModelContainer_New.wrapQuestion> lstWrapClass1 = new List<pepCMSModelContainer_New.wrapQuestion>();
        pepCMSModelContainer_New.wrapQuestion wrapClass1 = new pepCMSModelContainer_New.wrapQuestion();
        wrapClass1.objCmsQuestion = objQuestion2;
        lstWrapClass1.add(wrapClass1);
        
        List<pepCMSModelContainer_New.wrapSection> lstWrapClass = new List<pepCMSModelContainer_New.wrapSection>();
        pepCMSModelContainer_New.wrapSection wrapClass = new pepCMSModelContainer_New.wrapSection();
        wrapClass.lseQuestions = lstWrapClass1; 
        lstWrapClass.add(wrapClass);
        newIncome.lstSection = lstWrapClass;
        
        
        
        pepCmsModelContainer modelContainer = new pepCmsModelContainer();
        modelContainer.strPageName='Personal Details';
        modelContainer.strSectionName='PersonalDetailsSec1';
        modelContainer.objApplication = objApplication;
        modelContainer.objAccount = acc;
        
        pepCmsModelContainer modelContainer1 = new pepCmsModelContainer();
      
        modelContainer1.objApplication = objApplication;
        modelContainer1.objAccount = acc;
        
        pepPersonalDetailsController objClass = new pepPersonalDetailsController ();
        objClass.strDate = system.today();
        objClass.Page_Name = 'pepLoanSetupUploadedDocs';
        objClass.Page_Name = 'pepLoanSetupUploadedDocs';
        objClass.strPageName = 'Personal Details';
        objClass.objModelContainer=newIncome ;
        objClass.objModel = modelContainer;
        objClass.objModel3 = modelContainer1;
       
        objClass.SaveValues();
        objClass.saveCallFromHeader();
        objClass.saveData();
        acc.pepIsDummyAccount__c = true;
        acc.LastName = 'DUMMY';
        update acc;
        objClass.getpopulateValues();
        //Added By varun to increase the code coverage
        genesis__Applications__c applicationApproved = new genesis__Applications__c(id=objClass.Objmodelcontainer.objapplication.id,Serviceability_Status__c = 'Approved',genesis__Status__c='CONDITIONALLY APPROVED');
        update applicationApproved;
        objClass.checkVedaStausAndRedirect();
        genesis__Applications__c applicationDeclined = new genesis__Applications__c(id=objClass.Objmodelcontainer.objapplication.id,Serviceability_Status__c = 'Declined',genesis__Status__c='DECLINED');
        update applicationDeclined;
        objClass.checkVedaStausAndRedirect();
        genesis__Applications__c applicationReferred = new genesis__Applications__c(id=objClass.Objmodelcontainer.objapplication.id,Serviceability_Status__c = 'Referred',genesis__Status__c='REFERRED');
        update applicationReferred;
        objClass.checkVedaStausAndRedirect();
        objClass.saveDataFromExt();
        
        objClass.getCookieData();
        objClass.fetchResidentialAddress();
        objClass.doVerify();
        objClass.checkcookie();
    }
}