objects/Application__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to save the stage of pages after click on continue button.</description>
    <fields>
        <fullName>Navigation_Status__c</fullName>
        <label>Navigation Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Navigation Status</label>
</CustomObject>

objects/pages_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Page_Label__c</fullName>
        <label>Page_Label</label>
        <type>TextArea</type>
    </fields>
    <label>pages_config</label>
</CustomObject>

objects/pepCmsAnswer__c.object
<CustomObject>
    <fields>
        <fullName>pepCmsQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Question</label>
        <referenceTo>pepCmsQuestion__c</referenceTo>
        <relationshipLabel>Answer</relationshipLabel>
        <relationshipName>pepCmsAnswer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CMS Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsPage__c.object
<CustomObject>
    <label>CMS Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsQuestion__c.object
<CustomObject>
    <fields>
        <fullName>pepCMSAnswer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Answer</label>
        <referenceTo>pepCmsAnswer__c</referenceTo>
        <relationshipLabel>Question</relationshipLabel>
        <relationshipName>pepCmsQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CMS Question</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsSection__c.object
<CustomObject>
    <fields>
        <fullName>pepSectionStory__c</fullName>
        <label>Section Story</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>pepSectionUniqueName__c</fullName>
        <label>Section Unique Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CMS Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>CMS Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RetrieveCode__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RetrieveCode</label>
</CustomObject>

classes/PepFinaliseRepayment_Tracker.cls
@isTest(SeeAllData=False) private class PepFinaliseRepayment_Tracker{
    
   @isTest static void PepFinaliseRepaymentTest(){
    pepCmsPage__c objPage1 = pepCommonTrackerController.createPage('Finalise Repayment');
     
     //Section Creation
    pepCmsSection__c objSection1 = new pepCmsSection__c();
    objSection1 = pepCommonTrackerController.createSection1(objPage1);
    objSection1.pepSectionUniqueName__c = 'LoanDetailsSection1';
    objSection1.pepSectionStory__c ='test story';
    update objSection1;
     
     
    pepCmsQuestion__c objQuestion1 = pepCommonTrackerController.createCmsQuestion(objPage1,objSection1);
      
      
    pepCmsAnswer__c objAnswer1 = new pepCmsAnswer__c();
    objAnswer1 = pepCommonTrackerController.createCmsAnswer(objQuestion1);
         
    PepFinaliseRepayment.wrappperQusetion objWrapper = new PepFinaliseRepayment.wrappperQusetion(objQuestion1);   
   test.StartTest();   
   pages_config__c objConfig = new pages_config__c();
   objConfig.Page_Label__c='LoanSetupCreditPolicy';
   objConfig.Name='peploansetupcreditpolicy';
   insert objConfig;
    RetrieveCode__c objRetrieveCode = pepCommonTrackerController.createRetrieveCode();
      
    genesis__Applications__c objApplication = new genesis__Applications__c();
    objApplication = genesis.TestHelper.createApplication();
    objApplication.Debit_Frequency__c ='bi-weekly';
    objApplication.Automated_Payment_Start_Date__c=System.Today();
    objApplication.genesis__Payment_Amount__c=2000;
    objApplication.Debit_Amount__c=2000;
    update objApplication;
    
    Application__c objApp = new Application__c();
    objApp=pepCommonTrackerController.createApplication();
    
    Pagereference pd=Page.pepFinaliseRepayment;
    Test.setcurrentPagereference(pd);
    
    Cookie Applicationid=new Cookie('Applicationid',pepEncryptDecryptData.EncryptData(String.valueof(objApplication.id)),'-1',null,false);
    pd.setcookies(new cookie[]{Applicationid});
  test.StopTest();   
    PepFinaliseRepayment objFinalise = new PepFinaliseRepayment();
    objFinalise.checkcookie();
    objFinalise.calculateRepaymentValue();
    objFinalise.saveForLater();
    Application__c objApp1 = new Application__c();
    objApp1=pepCommonTrackerController.createApplication();
    objApp1.Name='pepLoanSetupCreditPolicy';
    objApp1.Navigation_Status__c='LoanSetup-FinaliseRepayment';
    update objApp1;
    objFinalise.redirectToNextPage();
    objFinalise.selectedFrequency='weekly';
    objFinalise.calculateRepaymentValue();
    objFinalise.selectedFrequency='monthly';
    objFinalise.calculateRepaymentValue();
    objFinalise.selectedFrequency='abc';
    objFinalise.calculateRepaymentValue();
    
  
   }
}