objects/Application__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to save the stage of pages after click on continue button.</description>
    <label>Application Navigation Status</label>
</CustomObject>

objects/Decisioning_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Callout_Class_Name__c</fullName>
        <label>Callout Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parser_Class_Name__c</fullName>
        <label>Parser Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Class_Name__c</fullName>
        <label>Response Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Decisioning Configuration</label>
    <nameField>
        <label>Decisioning Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decisioning Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IdMatrix_Analysis_Result__c.object
<CustomObject>
    <fields>
        <fullName>Veda_IdMatrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Veda IdMatrix</label>
        <referenceTo>Veda_IdMatrix__c</referenceTo>
        <relationshipLabel>IdMatrix Analysis Results</relationshipLabel>
        <relationshipName>IdMatrix_Analysis_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IdMatrix Analysis Result</label>
    <nameField>
        <label>Analysis Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IdMatrix Analysis Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IdMatrix_Fraud_Assessment_Response__c.object
<CustomObject>
    <fields>
        <fullName>Veda_IdMatrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Veda IdMatrix</label>
        <referenceTo>Veda_IdMatrix__c</referenceTo>
        <relationshipLabel>IdMatrix Fraud Assessment Response</relationshipLabel>
        <relationshipName>IdMatrix_Fraud_Assessment_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IdMatrix Fraud Assessment Response</label>
    <nameField>
        <label>Fraud Assessment Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IdMatrix Fraud Assessment Response</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IdMatrix_Rules_Result__c.object
<CustomObject>
    <fields>
        <fullName>Veda_IdMatrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Veda IdMatrix</label>
        <referenceTo>Veda_IdMatrix__c</referenceTo>
        <relationshipLabel>IdMatrix Rules Results</relationshipLabel>
        <relationshipName>IdMatrix_Rules_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IdMatrix Rules Result</label>
    <nameField>
        <label>Rules Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IdMatrix Rules Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IdMatrix_Search_Result__c.object
<CustomObject>
    <fields>
        <fullName>Veda_IdMatrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Veda IdMatrix</label>
        <referenceTo>Veda_IdMatrix__c</referenceTo>
        <relationshipLabel>IdMatrix Search Results</relationshipLabel>
        <relationshipName>IdMatrix_Search_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IdMatrix Search Result</label>
    <nameField>
        <label>Search Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IdMatrix Search Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <label>Security</label>
    <nameField>
        <label>Security Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Residential_Address__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>genesis__Applications__c</referenceTo>
        <relationshipLabel>Residential Address</relationshipLabel>
        <relationshipName>Residential_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current Address?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PostCode__c</fullName>
        <label>PostCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Number__c</fullName>
        <label>Street Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Type__c</fullName>
        <label>Street Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suburb__c</fullName>
        <label>Suburb</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <label>Unit Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Residential Address</label>
    <nameField>
        <displayFormat>RA - {0000}</displayFormat>
        <label>Residential Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residential Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RetrieveCode__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>RetrieveCode</label>
</CustomObject>

objects/Veda_IdMatrix__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>genesis__Applications__c</referenceTo>
        <relationshipLabel>Veda IdMatrix</relationshipLabel>
        <relationshipName>Veda_IdMatrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Veda IdMatrix</label>
    <nameField>
        <displayFormat>VID-{0000000000}</displayFormat>
        <label>Veda IdMatrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Veda IdMatrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestVedaIdMatrixImpl.cls
@isTest
public class TestVedaIdMatrixImpl {
   
     	testMethod static void vedaIdMatrixTest(){ 
      	RetrieveCode__c mc =  new RetrieveCode__c();
     	mc.code__c='AAA14341';
     	insert mc;
    	Account ac = genesis.TestHelper.createAccount();
    	genesis__Applications__c app=TestHelper.createLoanApplication();
        
    	Residential_Address__c rs = new Residential_Address__c();
    	rs.Current_Address__c=true;
    	rs.Street_Number__c='123';
    	rs.Street_Name__c='Privet';
    	rs.Street_Type__c='ST';
    	rs.Suburb__c='Little Whinging';
    	rs.State__c='NSW';
    	rs.Property__c='Potter Manor';
    	rs.Unit_Number__c='3';
    	rs.PostCode__c='2999';
    	rs.Country_Code__c='AUS';
   	 	rs.Application__c=app.Id;
    	insert rs;
   
    	TestHelper.insertIDMatrixCustomSetting();
    	System.debug('app='+app.Id);
   	 	VedaResponse vr = new VedaResponse();
    	VedaIdMatrixImpl  v  = new VedaIdMatrixImpl();
    	Decisioning_Configuration__c c = new Decisioning_Configuration__c();
    	c.Name='Veda IdMatrix';
    	c.Active__c=true;
    	c.Callout_Class_Name__c='VedaIdMatrixImpl';
    	c.Order__c=1;
    	c.Parser_Class_Name__c='VedaIdMatrixParser';
    	c.Response_Class_Name__c='ints.IDMatrixResponse';
    	insert c;
    	vr.app=app;
    	Test.startTest();   
      	VedaServices.webServiceVedaIdMatrix(app.Id);   
        Test.stopTest();
    	List<Veda_IdMatrix__c> veda_matrix = [select id from Veda_IdMatrix__c where Application__c =: app.id];
        system.assertEquals(veda_matrix.size(), 1);
        List<IdMatrix_Rules_Result__c> rules_result = [select id from IdMatrix_Rules_Result__c where Veda_IdMatrix__c =: veda_matrix[0].id];
        system.assertEquals(rules_result.size(), 1);
        List<IdMatrix_Analysis_Result__c> analysis = [select id from IdMatrix_Analysis_Result__c where Veda_IdMatrix__c =: veda_matrix[0].id];
        system.assertEquals(analysis.size(), 1);
        List<IdMatrix_Search_Result__c> searchRes = [select id from IdMatrix_Search_Result__c where Veda_IdMatrix__c =: veda_matrix[0].id];
        system.assertEquals(searchRes.size(), 1);
        List<IdMatrix_Fraud_Assessment_Response__c> asses = [select id from IdMatrix_Fraud_Assessment_Response__c where Veda_IdMatrix__c =: veda_matrix[0].id];
        system.assertEquals(asses.size(), 1);
    	
    }
    
    
    
    

}