objects/Application_Data__c.object
<CustomObject>
    <fields>
        <fullName>ApplicationDate__c</fullName>
        <label>ApplicationDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ApplicationNumber__c</fullName>
        <externalId>true</externalId>
        <label>ApplicationNumber</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ApplicationState__c</fullName>
        <label>ApplicationState</label>
        <picklist>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AssetType__c</fullName>
        <label>AssetType</label>
        <picklist>
            <picklistValues>
                <fullName>Bike</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caravan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motor Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>PAF - Dealer Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAF - Auto Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAF - Mortagage Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAF - Commercial Broker</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MileStone__c</fullName>
        <label>MileStone</label>
        <picklist>
            <picklistValues>
                <fullName>Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved in Principle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Documents Issued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NetFinancedAmount__c</fullName>
        <label>NetFinancedAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Sub Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved With Condition(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InProcess</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Introducer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Settled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotalFinancedAmount__c</fullName>
        <label>TotalFinancedAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>PAF Application Data</label>
    <nameField>
        <displayFormat>AppData-{00000}</displayFormat>
        <label>Application Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PAF Application Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mulesoft_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_ver__c</fullName>
        <label>API ver</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chatter_Notification_Body__c</fullName>
        <description>Stores the text will be sent as a chatter feed. 
Available Variables = $DashboardName</description>
        <inlineHelpText>Use $DashboardName variable in the text. It&apos;ll be replaced while posting the chatter feed.</inlineHelpText>
        <label>Chatter Notification Body  PAF</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Handling_URL__c</fullName>
        <label>Error Handling URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Error_Recipient__c</fullName>
        <inlineHelpText>Please enter email id&apos;s of recipient. To whom error messages to be sent.</inlineHelpText>
        <label>Error Recipients</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mortgage_User_Group__c</fullName>
        <description>Add all the id for Public Groups and User to whom notifications need to send.</description>
        <inlineHelpText>Add all the id for Public Groups and User to whom notifications need to send.</inlineHelpText>
        <label>Mortgage User Group</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mulesoft_Job_Url__c</fullName>
        <label>Mulesoft Job Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Mulesoft_Password__c</fullName>
        <label>Mulesoft Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mulesoft_User_Name__c</fullName>
        <label>Mulesoft User Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PAF_Last_Sync_Time__c</fullName>
        <label>PAF Last Sync Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PAF_User_Groups__c</fullName>
        <description>Add all the id for Public Groups and User to whom notifications need to send.</description>
        <inlineHelpText>Add all the id for Public Groups and User to whom notifications need to send.</inlineHelpText>
        <label>PAF User Groups</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SF_Password__c</fullName>
        <label>SF Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Token_Endpoint__c</fullName>
        <label>SF Token Endpoint</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>SF_User_Name__c</fullName>
        <label>SF User Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Instance_URL__c</fullName>
        <label>Salesforce Instance URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Success_Recipients__c</fullName>
        <label>Success Recipients</label>
        <type>TextArea</type>
    </fields>
    <label>Mulesoft Configuration</label>
</CustomObject>

objects/PFA_Analytical_Snapshot__c.object
<CustomObject>
    <fields>
        <fullName>ApplicationDate__c</fullName>
        <label>ApplicationDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ApplicationNumber__c</fullName>
        <label>ApplicationNumber</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApplicationState__c</fullName>
        <label>ApplicationState</label>
        <picklist>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AssetType__c</fullName>
        <label>AssetType</label>
        <picklist>
            <picklistValues>
                <fullName>Bike</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caravan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motor Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>PAF - Dealer Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAF - Auto Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAF - Commercial Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAF - Mortgage Broker</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MileStone__c</fullName>
        <label>MileStone</label>
        <picklist>
            <picklistValues>
                <fullName>Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved in Principle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Documents Issued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NetFinancedAmount__c</fullName>
        <label>NetFinancedAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Sub Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved With Condition(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InProcess</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Introducer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Settled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotalFinancedAmount__c</fullName>
        <label>TotalFinancedAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>PAF Analytical Snapshot</label>
    <nameField>
        <displayFormat>PFA-Snap{0000}</displayFormat>
        <label>PFA Analytical Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PAF Analytical Snapshot</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestPAFAnalyticsBatch.cls
@isTest
public class TestPAFAnalyticsBatch 
{
    static testMethod void MortgageAnalyticsBatch() 
    { 
     Database.BatchableContext BC;
     Mulesoft_Configuration__c Mule =New Mulesoft_Configuration__c();
            Mule.Name='Mulesoft';
            Mule.API_ver__c='34.0';
            Mule.Client_Id__c='3MVG9Se4BnchkASmwj33vhYPd_QE9LxUiHnGD_sa93eiXJ9kqKzcjzoPtAN_b5kSvTq0Soxp9xHBx.xMZaD_J';
            Mule.Client_Secret__c='7150987666493593516';
            Mule.Error_Handling_URL__c='https://c.cs31.visual.force.com/apex/MulesoftBatchJobHandler';
            Mule.Error_Recipient__c='sumit.banarji@saasfocus.com ';
            Mule.Mulesoft_Job_Url__c='sumit.banarji@saasfocus.com ';
            Mule.Mulesoft_Password__c='P3pp3rPa55';
            Mule.Mulesoft_User_Name__c='pepper';
            Mule.Salesforce_Instance_URL__c='https://cs31.salesforce.com/home/home.jsp?sdtd=1';
            Mule.SF_Password__c='saasfocus@2016';
            Mule.SF_Token_Endpoint__c='https://test.salesforce.com/services/oauth2/token';
            Mule.SF_User_Name__c='siddharth.malhotra@pepper.com.au.clevel';
            Mule.Success_Recipients__c='sumit.banarji@saasfocus.com ';
            Mule.PAF_Last_Sync_Time__c=System.today()-3;
            Mule.Mortgage_User_Group__c = 'me';
            Mule.PAF_User_Groups__c = 'me';
            Mule.Chatter_Notification_Body__c ='testBody';
            Insert Mule;
        Application_Data__c Application =New Application_Data__c();
          
           Application.ApplicationDate__c=system.today();
           Application.NetFinancedAmount__c=84843;
           Application.MileStone__c='Application';
           Application.ApplicationNumber__c='P-20160521000602';
           Application.Channel__c='PAF - Auto Broker';
           Application.AssetType__c='Caravan';
           Application.Sub_Status__c='Approved';
           Application.ApplicationState__c='ACT ';
           Application.TotalFinancedAmount__c=2333344;
           Insert Application;
        PFA_Analytical_Snapshot__c PFAAnalytical =New PFA_Analytical_Snapshot__c();
           PFAAnalytical.ApplicationDate__c=system.today();
           PFAAnalytical.NetFinancedAmount__c=84843;
           PFAAnalytical.MileStone__c='Application';
           PFAAnalytical.ApplicationNumber__c='P-20160521000602';
           PFAAnalytical.Channel__c='PAF - Auto Broker';
           PFAAnalytical.AssetType__c='Caravan';
           PFAAnalytical.Sub_Status__c='Approved';
           PFAAnalytical.ApplicationState__c='ACT   ';
           PFAAnalytical.TotalFinancedAmount__c=2333344;
           Insert PFAAnalytical;
          Test.startTest();
          PAF_Analytics_Batch PAF =New PAF_Analytics_Batch();
          Database.executebatch(PAF);
           PAF.start(BC);
          Test.stopTest();
        
    }
}