objects/Application__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to save the stage of pages after click on continue button.</description>
    <fields>
        <fullName>Navigation_Status__c</fullName>
        <label>Navigation Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RedirectPage__c</fullName>
        <label>RedirectPage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Navigation Status</label>
</CustomObject>

objects/pages_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Page_Label__c</fullName>
        <label>Page_Label</label>
        <type>TextArea</type>
    </fields>
    <label>pages_config</label>
</CustomObject>

objects/pepCmsPage__c.object
<CustomObject>
    <fields>
        <fullName>pepPageName__c</fullName>
        <label>Page Name</label>
        <picklist>
            <picklistValues>
                <fullName>Landing Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apply Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App Login Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save &amp; Retrieve Functionality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Living Expenses Calculator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Header</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Footer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability Negative2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(verifyid)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup (Credit-Policy)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalise Repayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(FinancialDoc)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Consolidation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(Manual Upload)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Congratulations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(upload another Image)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SideBarTemplate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup (Bank-Detail)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsSection__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_Link_1__c</fullName>
        <label>Marketing Linkc 1</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>pepCss_Class__c</fullName>
        <label>Css Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepHeader__c</fullName>
        <label>Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepPage__c</fullName>
        <label>Page</label>
        <referenceTo>pepCmsPage__c</referenceTo>
        <relationshipName>pepSection</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>pepRedirect_to_Page__c</fullName>
        <label>Redirect to Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepSectionBodyRich__c</fullName>
        <label>Section Body (Rich)</label>
        <length>130000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>pepSectionBody__c</fullName>
        <label>Section Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>pepSectionStoryRich__c</fullName>
        <label>Section Story</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>pepSectionStory__c</fullName>
        <label>Section Story</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>pepSectionUniqueName__c</fullName>
        <label>Section Unique Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>pepSequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Running Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>CMS Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RetrieveCode__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RetrieveCode</label>
</CustomObject>

classes/pepCongratulations_Tracker.cls
// ---------------------------------------------------------------------------------------------------------
// This Tracker class is used to cover pepCongratulations class. 
// 
//      Date                       Author                
// ---------------------------------------------------------------------------------------------------------
//      14th June 2016           Rishabh Tyagi          
// ---------------------------------------------------------------------------------------------------------
@isTest(seeAllData= false)
Public Class pepCongratulations_Tracker
{
    
  private Static  pepCmsPage__c objPage;
  private Static  pepCmsSection__c objSection;
  private Static  Account objAccount;
  private Static  genesis__Applications__c objGenesisApp;
  private Static  Application__c objApp;
  private static pepCmsPage__c objcmspage;
  private static pepCmsSection__c objCMSSection;
  private static pepCmsSection__c objCMSSection1;
  private static pepCmsSection__c objCMSSection2;
  private static pepCmsSection__c objCMSSection3;
  
  private static List<pepCmsSection__c> lstPepCMS;
  
  static testMethod void testPepCongratulations() 
  {
      test.starttest();
      
        pages_config__c pg11 = new pages_config__c(Name='peploansetupverifyid',Page_Label__c='loansetupverifyid');
            insert pg11;

      
      RetrieveCode__c objRetrieveCode = pepCommonTrackerController.createRetrieveCode();
      objAccount = pepCommonTrackerController.CreateBusinessAcc();
      objGenesisApp = genesis.TestHelper.createApplication();
      objGenesisApp.genesis__Account__c = objAccount.id;
      update objGenesisApp;
     
      
      //Instance of page Reference
      pagereference pd=Page.pepCongratulations;
      Test.setcurrentPagereference(pd);
      
       createpage();
      
       //Set cookies 
       Cookie Applicationid=new Cookie('Applicationid',pepEncryptDecryptData.EncryptData(String.valueof(objGenesisApp.id)),'-1',null,false);
       pd.setcookies(new cookie[]{Applicationid});
       
       
       pepCongratulations objPepCong = new pepCongratulations();
       objPepCong.checkcookie();
      
        Application__c pepApplication = new Application__c(Name= 'pepCongratulations',Navigation_Status__c='LoanSetup-Offer',RedirectPage__c='pepCongratulations');
        insert pepApplication;
        objPepCong.saveForLater();
        
        Application__c  pepApplication1  =  pepCommonTrackerController.createApplication();
        pepApplication1.Name = 'peploanSetupverifyid'; 
        pepApplication1.RedirectPage__c = 'peploanSetupverifyid';
        pepApplication1.Navigation_Status__c = 'LoanSetup-Jumio';
        update pepApplication1;
         
        objPepCong.redirectToNextPage();
        test.stoptest();
       
  }
  
  static void createpage()
   {
       objcmspage = new pepCmsPage__c();
       objcmspage.pepPageName__c = 'Congratulations';
       insert objcmspage;
       
       //CMS Section 1
       objCMSSection = new pepCmsSection__c();
       objCMSSection.pepPage__c = objcmspage.id;
       objCMSSection.pepCss_Class__c = 'mainCat_share';
       objCMSSection.pepHeader__c = 'Refer-a-friend';
       objCMSSection.Marketing_Link_1__c = '';
       objCMSSection.pepRedirect_to_Page__c = '';
       objCMSSection.pepSectionBody__c = '';
       objCMSSection.pepSectionBodyRich__c = 'test body rich1';
       objCMSSection.pepSectionStory__c = '';
       objCMSSection.pepSectionStoryRich__c = '';
       objCMSSection.pepSectionUniqueName__c = 'Test1';
       objCMSSection.pepSequence__c = 0;
       objCMSSection.pepType__c = 'Help Text';
       insert objCMSSection;
       
       //CMS Section 1
       objCMSSection1 = new pepCmsSection__c();
       objCMSSection1.pepPage__c = objcmspage.id;
       objCMSSection1.pepCss_Class__c = 'mainCat_share';
       objCMSSection1.pepHeader__c = 'Refer-a-friend';
       objCMSSection1.Marketing_Link_1__c = '';
       objCMSSection1.pepRedirect_to_Page__c = '';
       objCMSSection1.pepSectionBody__c = '';
       objCMSSection1.pepSectionBodyRich__c = 'test body rich2';
       objCMSSection1.pepSectionStory__c = '';
       objCMSSection1.pepSectionStoryRich__c = '';
       objCMSSection1.pepSectionUniqueName__c = 'Test2';
       objCMSSection1.pepSequence__c = 1;
       objCMSSection1.pepType__c = 'Help Text';
       insert objCMSSection1;
       
       
       //CMS Section 2
       objCMSSection2 = new pepCmsSection__c();
       objCMSSection2.pepPage__c = objcmspage.id;
       objCMSSection2.pepCss_Class__c = 'mainCat_share';
       objCMSSection2.pepHeader__c = 'Refer-a-friend';
       objCMSSection2.Marketing_Link_1__c = '';
       objCMSSection2.pepRedirect_to_Page__c = '';
       objCMSSection2.pepSectionBody__c = '';
       objCMSSection2.pepSectionBodyRich__c = '{!genesis__Applications__c.genesis__Account__r.Id}';
       objCMSSection2.pepSectionStory__c = '';
       objCMSSection2.pepSectionStoryRich__c = '';
       objCMSSection2.pepSectionUniqueName__c = 'Test3';
       objCMSSection2.pepSequence__c = 2;
       objCMSSection2.pepType__c = 'Help Text';
       insert objCMSSection2;
       
       //CMS Section 3
       objCMSSection3 = new pepCmsSection__c();
       objCMSSection3.pepPage__c = objcmspage.id;
       objCMSSection3.pepCss_Class__c = 'mainCat_share';
       objCMSSection3.pepHeader__c = 'Refer-a-friend';
       objCMSSection3.Marketing_Link_1__c = '';
       objCMSSection3.pepRedirect_to_Page__c = '';
       objCMSSection3.pepSectionBody__c = '';
       objCMSSection3.pepSectionBodyRich__c = '{!genesis__Applications__c.Id}';
       objCMSSection3.pepSectionStory__c = '';
       objCMSSection3.pepSectionStoryRich__c = '';
       objCMSSection3.pepSectionUniqueName__c = 'Test4';
       objCMSSection3.pepSequence__c = 3;
       objCMSSection3.pepType__c = 'Help Text';
       insert objCMSSection3;
       
       
       lstPepCMS = new List<pepCmsSection__c>();
       lstPepCMS.add(objCMSSection);
       lstPepCMS.add(objCMSSection1);
       lstPepCMS.add(objCMSSection2);
       lstPepCMS.add(objCMSSection3);
       
   }
   
}