objects/Application__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to save the stage of pages after click on continue button.</description>
    <label>Application Navigation Status</label>
</CustomObject>

objects/pages_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Page_Label__c</fullName>
        <label>Page_Label</label>
        <type>TextArea</type>
    </fields>
    <label>pages_config</label>
</CustomObject>

objects/pepCmsPage__c.object
<CustomObject>
    <label>CMS Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsQuestion__c.object
<CustomObject>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HomePhone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Question</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsSection__c.object
<CustomObject>
    <fields>
        <fullName>pepSectionUniqueName__c</fullName>
        <label>Section Unique Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Running Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>CMS Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RetrieveCode__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RetrieveCode</label>
</CustomObject>

classes/PepLoginController_Tracker.cls
@isTest 
public class PepLoginController_Tracker {
    
    @isTest static void PepLoginController_TrackerTest(){
        pepCommonTrackerController obj =new pepCommonTrackerController();
        pepCmsPage__c objPage = pepCommonTrackerController.createPage('Login Screen');
        pepCmsSection__c objSection = new pepCmsSection__c();
        objSection = pepCommonTrackerController.createSection(objPage);
        objSection.pepSectionUniqueName__c ='SectionThree(LS)';
        System.debug(objSection);
        
        pepCmsQuestion__c objQuestion = pepCommonTrackerController.createCmsQuestion(objPage,objSection);
        objQuestion.pepType__c='Text';
    Test.StartTest();   
    
           pages_config__c objConfig = new pages_config__c();
           objConfig.Page_Label__c='loginpage';
           objConfig.Name='peploginpage';
           insert objConfig;
           
           pages_config__c objConfig1 = new pages_config__c();
           objConfig1.Page_Label__c='welcomepage';
           objConfig1.Name='pepwelcomepage';
           insert objConfig1;
           
           pages_config__c objConfig3 = new pages_config__c();
           objConfig3.Page_Label__c='forgotpassword';
           objConfig3.Name='pepforgotpassword';
           insert objConfig3;
           
           pages_config__c objConfig4 = new pages_config__c();
           objConfig4.Page_Label__c='Contract';
           objConfig4.Name='pepcontract';
           insert objConfig4;
    
         RetrieveCode__c objRetrieveCode = pepCommonTrackerController.createRetrieveCode();
      
         genesis__Applications__c objApplication = new genesis__Applications__c();
         objApplication = genesis.TestHelper.createApplication();
         objApplication.Debit_Frequency__c ='bi-weekly';
         objApplication.Automated_Payment_Start_Date__c=System.Today();
         objApplication.genesis__Payment_Amount__c=2000;
         objApplication.RedirectToContract__c=True;
         update objApplication;
    
         Application__c objApp = new Application__c();
        objApp=pepCommonTrackerController.createApplication();
    
         Pagereference pd=Page.peploginpage;
         Test.setcurrentPagereference(pd);
     
         Cookie Applicationid=new Cookie('Applicationid',pepEncryptDecryptData.EncryptData(String.valueof(objApplication.id)),'-1',null,false);
         pd.setcookies(new cookie[]{Applicationid});
    Test.StopTest();    
         PepLoginController objLoginController = new PepLoginController();
        
        
        String userName ='test';
        String password ='password';
        objLoginController.loginUser();
        
        objLoginController.navigateToForgot();
        PepLoginController.checkCookieAndRedirect();
        
        objApplication.RedirectToContract__c=False;
        PepLoginController.checkCookieAndRedirect();
    }

}