objects/Application__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to save the stage of pages after click on continue button.</description>
    <fields>
        <fullName>Navigation_Status__c</fullName>
        <label>Navigation Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RedirectPage__c</fullName>
        <label>RedirectPage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Navigation Status</label>
</CustomObject>

objects/Expense_and_Debt__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Remaining_as_Debt__c</fullName>
        <description>This will be needed to be provided if revolving credit and debt consolidation is true</description>
        <label>Debt Amount Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>genesis__Applications__c</referenceTo>
        <relationshipLabel>Expenses and Debts</relationshipLabel>
        <relationshipName>Expenses_and_Debts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Consolidate_As_A_Debt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Consolidate As Debt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mortgage Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Household Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment and Services Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle and Transport Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Living Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food and Living Expense</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Expense_Debt__c</fullName>
        <label>Type of Expense/Debt</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Credit card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Council Rates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strata</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electricity Rates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Rates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gas Rates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gambling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Total of all other monthly expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent or mortgage repayments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utilities, rates and services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &amp; contents insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other living expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other sevices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motor vehicle expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private health insurance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Expense and Debt</label>
    <nameField>
        <displayFormat>END-{0000000000}</displayFormat>
        <label>Expense and Debts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses and Debts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/pages_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Page_Label__c</fullName>
        <label>Page_Label</label>
        <type>TextArea</type>
    </fields>
    <label>pages_config</label>
</CustomObject>

objects/pepBank_API_Details__c.object
<CustomObject>
    <fields>
        <fullName>pepBank_Name__c</fullName>
        <label>Bank Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bank API Detail</label>
    <nameField>
        <displayFormat>BNK-{0000}</displayFormat>
        <label>Bank API Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank API Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsAnswer__c.object
<CustomObject>
    <fields>
        <fullName>pepCmsQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Question</label>
        <referenceTo>pepCmsQuestion__c</referenceTo>
        <relationshipLabel>Answer</relationshipLabel>
        <relationshipName>pepCmsAnswer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CMS Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsPage__c.object
<CustomObject>
    <label>CMS Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsQuestion__c.object
<CustomObject>
    <fields>
        <fullName>pepCMSAnswer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Answer</label>
        <referenceTo>pepCmsAnswer__c</referenceTo>
        <relationshipLabel>Question</relationshipLabel>
        <relationshipName>pepCmsQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepLabelPriorQuestion__c</fullName>
        <description>The text that will be displayed just before the question is rendered.</description>
        <label>Label (Prior Question)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HomePhone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Question</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsSection__c.object
<CustomObject>
    <fields>
        <fullName>pepHeader__c</fullName>
        <label>Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepSectionUniqueName__c</fullName>
        <label>Section Unique Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Running Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>CMS Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RetrieveCode__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RetrieveCode</label>
</CustomObject>

classes/pepDebtConsolidationController_Tracker.cls
@isTest(SeeAllData=False) private class pepDebtConsolidationController_Tracker{
    
   @isTest static void pepDebtConsolidationController(){
   
   
        loan__Loan_Purpose__c objLoanPurpose = new loan__Loan_Purpose__c();
        objLoanPurpose.Name='New Car';
        objLoanPurpose.loan__Loan_Purpose_Code__c='VNC0001';
        objLoanPurpose.loan__Description__c='Vehicle New Car';
        insert objLoanPurpose;

        clcommon__CL_Purpose__c objClPurpose = new clcommon__CL_Purpose__c();
        objClPurpose.Name='a debt consolidation loan';
        objClPurpose.clcommon__Description__c='A loan for a new car.';
        //objClPurpose.Loan_Purpose__c=objLoanPurpose.id;
        objClPurpose.Serial_No__c=4;
        insert objClPurpose;
        
          pages_config__c pg11 = new pages_config__c(Name='pepfinaliserepayment',Page_Label__c='FinaliseRepayment');
            insert pg11;

        
        pepBank_API_Details__c objBankDetail = new pepBank_API_Details__c(pepBank_Name__c='hdfc');
        insert objBankDetail;
        
        pepCmsPage__c objPage1 = pepCommonTrackerController.createPage('Debt Consolidation');
       
        pepCmsSection__c objSection1 = new pepCmsSection__c();
        objSection1 = pepCommonTrackerController.createSection1(objPage1);
        objSection1.pepSectionUniqueName__c = 'DebtConsolidationAllExpenses';
        objSection1.pepHeader__c='DebtDescription';
        update objSection1;
       
        pepCmsQuestion__c objQuestion1 = pepCommonTrackerController.createCmsQuestion(objPage1,objSection1);
        objQuestion1.pepLabelPriorQuestion__c='Financial Institution';
        objQuestion1.pepType__c ='Picklist';
        update objQuestion1;
        pepCmsAnswer__c objAnswer1 = new pepCmsAnswer__c();
        objAnswer1 = pepCommonTrackerController.createCmsAnswer(objQuestion1);
        
        
        //pepDebtConsolidationController.QuesAnsWrap objQuesWrap = new pepDebtConsolidationController.QuesAnsWrap();
        
       
        RetrieveCode__c objRetrieveCode = pepCommonTrackerController.createRetrieveCode();
      
        genesis__Applications__c objApplication = new genesis__Applications__c();
        objApplication = genesis.TestHelper.createApplication();
        objApplication.Debit_Frequency__c ='bi-weekly';
        objApplication.Automated_Payment_Start_Date__c=System.Today();
        objApplication.genesis__Payment_Amount__c=2000;
        objApplication.Debit_Amount__c=2000;
        objApplication.genesis__CL_Purpose__c=objClPurpose.id;
        update objApplication;
        
        Expense_and_Debt__c objExpence = new Expense_and_Debt__c();
        objExpence.Application__c = objApplication.id;
        objExpence.Type__c='Debt';
        objExpence.Consolidate_As_A_Debt__c=True;
        objExpence.Type_of_Expense_Debt__c='Credit card1';
        objExpence.Amount_Remaining_as_Debt__c=20000;
        insert objExpence;
    
        Application__c objApp1 = new Application__c();
        objApp1=pepCommonTrackerController.createApplication();
        objApp1.Name='pepDebtConsolidation';
        objApp1.Navigation_Status__c='LoanSetup-DebtConsolidation';
        objApp1.RedirectPage__c='pepDebtConsolidation';
        update objApp1;

    
        Pagereference pd=Page.pepFinaliseRepayment;
        Test.setcurrentPagereference(pd);
    
        Cookie Applicationid=new Cookie('Applicationid',pepEncryptDecryptData.EncryptData(String.valueof(objApplication.id)),'-1',null,false);
        pd.setcookies(new cookie[]{Applicationid});
        
        pepDebtConsolidationController.expenseWrapper objwrap = new pepDebtConsolidationController.expenseWrapper();
        pepDebtConsolidationController.QuesAnsWrap objQue= new pepDebtConsolidationController.QuesAnsWrap();
        
        pepDebtConsolidationController objContoller = new pepDebtConsolidationController();
        objContoller.saveForLater();
        Application__c objApp2 = new Application__c();
        objApp2=pepCommonTrackerController.createApplication();   
        objQue.objInputValue='heyt';     
        //objContoller.saveData();
        objContoller.checkcookie();
        
        List<pepDebtConsolidationController.QuesAnsWrap> lstWrap = new List<pepDebtConsolidationController.QuesAnsWrap>();
        pepDebtConsolidationController.QuesAnsWrap objQue1 = new pepDebtConsolidationController.QuesAnsWrap();
        objQue1.objQues=objQuestion1;
        objQue1.objInputValue='hie';
        lstWrap.add(objQue1);
        pepDebtConsolidationController.expenseWrapper objwrap1 = new pepDebtConsolidationController.expenseWrapper();
        objwrap1.lstQAWrap=lstWrap;
        
        pepDebtConsolidationController objContoller1 = new pepDebtConsolidationController();
        objContoller1.saveData();
   }
   
}