objects/Application_Data__c.object
<CustomObject>
    <fields>
        <fullName>ApplicationNumber__c</fullName>
        <externalId>true</externalId>
        <label>ApplicationNumber</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CRM_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>PAF Application Data</relationshipLabel>
        <relationshipName>PAF_Application_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NetFinancedAmount__c</fullName>
        <label>NetFinancedAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Sub Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved With Condition(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InProcess</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Introducer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Settled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PAF Application Data</label>
    <nameField>
        <displayFormat>AppData-{00000}</displayFormat>
        <label>Application Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PAF Application Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CRM_Actual_loan_amount__c</fullName>
        <label>Actual loan amount submitted</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CRM_Application_ID__c</fullName>
        <label>Application ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CRMtrgPAFtoOpportunityLookupHandler.cls
public class CRMtrgPAFtoOpportunityLookupHandler {
    
    /*
        public static void CreateOpportunityLookup(List<Application_Data__c> lstBeforeInsertApplicationRecords){
    
        Set<String> setString = new Set<String>();   
        for(Application_Data__c objApplicationData : lstBeforeInsertApplicationRecords){   
            if(!String.isBlank(objApplicationData.ApplicationNumber__c)){       
                setString.add(objApplicationData.ApplicationNumber__c);      
            }   
        }
        
        List<Opportunity> lstOpportunity = [select id,CRM_Application_ID__c from Opportunity where CRM_Application_ID__c in : setString];
        Map<String,ID> mapStringToOpportunityID = new Map<String,ID>();
        if(lstOpportunity != null && lstOpportunity.size()>0){
            for(Opportunity objOpp : lstOpportunity){      
                if(!String.isBlank(objOpp.CRM_Application_ID__c)){           
                    mapStringToOpportunityID.put(objOpp.CRM_Application_ID__c,objOpp.id);          
                }       
            }
        }
        list<Opportunity> lstToUpdateOpportunity = new List<Opportunity>();
        for(Application_Data__c objApplicationData : lstBeforeInsertApplicationRecords){   
            if(!String.isBlank(objApplicationData.ApplicationNumber__c)){ 
                if(mapStringToOpportunityID.get(objApplicationData.ApplicationNumber__c) !=null){
                    objApplicationData.CRM_Opportunity__c = mapStringToOpportunityID.get(objApplicationData.ApplicationNumber__c);
                    opportunity opp = new opportunity();
                    opp.id =  mapStringToOpportunityID.get(objApplicationData.ApplicationNumber__c);
                    opp.CRM_Actual_loan_amount__c = objApplicationData.NetFinancedAmount__c;
                    lstToUpdateOpportunity.add(opp);
                 } 
            }   
        }
    
        if(lstToUpdateOpportunity != null && lstToUpdateOpportunity.Size()>0){
            
            update lstToUpdateOpportunity;
        
        }
    
    }
    
    */
    Public static boolean temp = false;
    public static void UpdateOpportunityStatus(List<Application_Data__c> lstAfterUpdateApplicationRecords,Map<id,Application_Data__c> MapPAfOldValues){      
        List<Opportunity> lstToUpdateopp = new List<Opportunity>();
        for(Application_Data__c objApplication : lstAfterUpdateApplicationRecords){
            if(objApplication.CRM_Opportunity__c != null){
                Opportunity oppToUpdate = new Opportunity();
                oppToUpdate.id = objApplication.CRM_Opportunity__c;
                
                if(objApplication.Sub_Status__c == 'Approved'){
          
                    oppToUpdate.StageName = 'Formally Approved';                   
                    temp = true;
                }  
                
                if(objApplication.NetFinancedAmount__c != MapPAfOldValues.get(objApplication.id).NetFinancedAmount__c || objApplication.CRM_Opportunity__c != MapPAfOldValues.get(objApplication.id).CRM_Opportunity__c){
                   
                    oppToUpdate.CRM_Actual_loan_amount__c = objApplication.NetFinancedAmount__c;
                    temp = true;
                
                }  
                lstToUpdateopp.add(oppToUpdate);
            }        
        }
        
        if(lstToUpdateopp != null && lstToUpdateopp.Size()>0 && temp == true){
            update lstToUpdateopp;
        }
    
    }

}