objects/Application__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to save the stage of pages after click on continue button.</description>
    <fields>
        <fullName>Navigation_Status__c</fullName>
        <label>Navigation Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RedirectPage__c</fullName>
        <label>RedirectPage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Navigation Status</label>
</CustomObject>

objects/Income__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>genesis__Applications__c</referenceTo>
        <relationshipLabel>Incomes</relationshipLabel>
        <relationshipName>Incomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Other_Income__c</fullName>
        <label>Other Income?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Income</label>
    <nameField>
        <displayFormat>INC-{0000000000}</displayFormat>
        <label>Income Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/pages_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Page_Label__c</fullName>
        <label>Page_Label</label>
        <type>TextArea</type>
    </fields>
    <label>pages_config</label>
</CustomObject>

objects/pepCmsPage__c.object
<CustomObject>
    <label>CMS Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsQuestion__c.object
<CustomObject>
    <label>CMS Question</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsSection__c.object
<CustomObject>
    <label>CMS Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>CMS Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RetrieveCode__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RetrieveCode</label>
</CustomObject>

classes/pepIncomeController_tracker.cls
@isTest(seeAlldata=False)
public class pepIncomeController_tracker {
    
    static testMethod void loadData()
    {
      //-------------pepLoanDetails Page----------------------------------------------------------- 
       loan.testhelper.createSeedDataForTesting();
        pepCmsPage__c objcmspage = pepCommonTrackerController.createPage('Income Details');
        pepCmsSection__c objcmssection = pepCommonTrackerController.createSection(objcmspage);
        pepCmsQuestion__c objcmsquestion = pepCommonTrackerController.createCmsQuestion(objcmspage,objcmssection);
       
        pages_config__c pg = new pages_config__c(Name='pepincomepage',Page_Label__c='IncomePage');
        insert pg;
        
        pages_config__c pg1 = new pages_config__c(Name='pepexpensepage',Page_Label__c='ExpensePage');
        insert pg1;
        
        pages_config__c pg11 = new pages_config__c(Name='peploandetails',Page_Label__c='loandetails');
        insert pg11;
        
        Application__c objAppNav = new Application__c();
       objAppNav.Name='pepIncomePage';
       objAppNav.Navigation_Status__c='Income';
       objAppNav.RedirectPage__c='pepIncomePage';
       insert objAppNav;
       
       Application__c objAppNav1 = new Application__c();
       objAppNav1.Name='pepLoanDetails';
       objAppNav1.Navigation_Status__c='LoanDetails';
       objAppNav1.RedirectPage__c='pepLoanDetails';
       insert objAppNav1;
        
  Test.StartTest();      
        RetrieveCode__c objRetrieveCode = pepCommonTrackerController.createRetrieveCode();
        
        
        genesis__Applications__c objApplication = new genesis__Applications__c();
        objApplication = genesis.TestHelper.createApplication();
        objApplication.Debit_Frequency__c ='bi-weekly';
        objApplication.Automated_Payment_Start_Date__c=System.Today();
        objApplication.genesis__Payment_Amount__c=2000;
        objApplication.Debit_Amount__c=2000;
        objApplication.pepCurrent_Page__c=1;
        update objApplication;
        
      /*  Application__c objApp = new Application__c(Name='pepIncomePage',Navigation_Status__c='Income',RedirectPage__c='pepIncomePage');
        insert objApp; */
        Application__c objApp1 = new Application__c(Name='pepExpensePage',Navigation_Status__c='Expense',RedirectPage__c='pepExpensePage');
        insert objApp1;
        
        Income__c objIncome = new Income__c();
        objIncome.Application__c=objApplication.id;
        objIncome.Other_Income__c='No';
        insert objIncome;
        List<Income__c> lstInc = new List<Income__c>();
        lstInc.add(objIncome);
        
        
        PageReference pageRef = Page.pepIncomePage;
        pageRef.getHeaders().put('X-Salesforce-SIP','1');
        pageRef.getParameters().put('redirectFromPageNo','1');
        Test.setCurrentPagereference(pageRef);
        
        Cookie Applicationid=new Cookie('Applicationid',pepEncryptDecryptData.EncryptData(String.valueof(objApplication.id)),'-1',null,false);
        pageRef.setcookies(new cookie[]{Applicationid});
        
  		Test.StopTest();
        pepIncomeController objIncomeController = new pepIncomeController();
        objIncomeController.objModelContainer.lstIncome=lstInc;
        objIncomeController.objModelContainer.objApplication=objApplication;
        objIncomeController.pagetoredirect='1';
        objIncomeController.parsedSectionStory();
        objIncomeController.continueLoanApp();
        objIncomeController.saveData();
        objIncomeController.saveCallFromHeader();
        objIncomeController.pagetoredirect='2';
        objIncomeController.saveCallFromHeader();
        objIncomeController.pagetoredirect='3';
        objIncomeController.saveCallFromHeader();
        PageReference resultPage = objIncomeController.onLoading();
       	System.assertEquals('/ExpensePage', resultPage.getURL());
       
    }
}