objects/Application__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to save the stage of pages after click on continue button.</description>
    <label>Application Navigation Status</label>
</CustomObject>

objects/pages_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Page_Label__c</fullName>
        <label>Page_Label</label>
        <type>TextArea</type>
    </fields>
    <label>pages_config</label>
</CustomObject>

objects/pepCmsSection__c.object
<CustomObject>
    <label>CMS Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>CMS Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RetrieveCode__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RetrieveCode</label>
</CustomObject>

objects/Technical_Error_Email_Group__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Disable_Automatic_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Automatic Notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_SMS_count__c</fullName>
        <label>Email/SMS count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <label>Technical Error Email Group</label>
</CustomObject>

classes/pepgenericredirection_Tracker.cls
@isTest(SeeAllData=False) private class pepgenericredirection_Tracker{
    
   @isTest static void pepgenericredirectionTest(){
                    pepCommonTrackerController obj =new pepCommonTrackerController();
                    Account objAccount = pepCommonTrackerController.CreateBusinessAcc();
                    list<pepCmsSection__c> lstSection = new list<pepCmsSection__c>();
                test.startTest();     
                    genesis__Applications__c objApplication = new genesis__Applications__c();
                    RetrieveCode__c objRetrieveCode = pepCommonTrackerController.createRetrieveCode();
                    objApplication = genesis.TestHelper.createApplication();
                    objApplication.Debit_Frequency__c ='bi-weekly';
                    objApplication.RedirectToContract__c = true;
                    objApplication.genesis__Account__c = objAccount.id;
                    update objApplication; 
                 test.stopTest();     
                    Application__c objApp = new Application__c();
                    objApp=pepCommonTrackerController.createApplication();
                    pages_config__c pg1 = new pages_config__c(Name='pepgenericredirection',Page_label__c='GenericRedirection');
                    insert pg1;
                    Pagereference pd=Page.pepGenericRedirection;
                    Test.setcurrentPagereference(pd);
                    
                    Cookie Applicationid=new Cookie('Applicationid',pepEncryptDecryptData.EncryptData(String.valueof(objApplication.id)),'-1',null,false);
                    pd.setcookies(new cookie[]{Applicationid});
                    
                    pepgenericredirection objController = new pepgenericredirection();
                    Technical_Error_Email_Group__c terEmailGrp = new Technical_Error_Email_Group__c(Name='TechnicalErrorGroup',Email__c='varun.arora@saasfocus.com',Mobile__c='04141369952');
                    insert terEmailGrp;
                    Technical_Error_Email_Group__c terEmailGrp1 = new Technical_Error_Email_Group__c(Name='AutomaticEmail/SMS',Email__c='varun.arora@saasfocus.com',Mobile__c='04141369952',Disable_Automatic_Notification__c=False,Email_SMS_count__c=0);
                    insert terEmailGrp1;
                    objcontroller.sendTechnicalerroremail();
    
    }
    
 }