objects/Application__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to save the stage of pages after click on continue button.</description>
    <label>Application Navigation Status</label>
</CustomObject>

objects/Decisioning_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Callout_Class_Name__c</fullName>
        <label>Callout Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parser_Class_Name__c</fullName>
        <label>Parser Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Class_Name__c</fullName>
        <label>Response Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Decisioning Configuration</label>
    <nameField>
        <label>Decisioning Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decisioning Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <label>Security</label>
    <nameField>
        <label>Security Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Residential_Address__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>genesis__Applications__c</referenceTo>
        <relationshipLabel>Residential Address</relationshipLabel>
        <relationshipName>Residential_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current Address?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PostCode__c</fullName>
        <label>PostCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Number__c</fullName>
        <label>Street Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Type__c</fullName>
        <label>Street Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suburb__c</fullName>
        <label>Suburb</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <label>Unit Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Residential Address</label>
    <nameField>
        <displayFormat>RA - {0000}</displayFormat>
        <label>Residential Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residential Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RetrieveCode__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>RetrieveCode</label>
</CustomObject>

classes/TestDandBImpl.cls
@isTest
public class TestDandBImpl {
    testMethod static void DandBTest(){ 
        RetrieveCode__c mc =  new RetrieveCode__c();
        mc.code__c='AAA14341';
        insert mc;
        Account ac = genesis.TestHelper.createAccount();
        genesis__Applications__c app=TestHelper.createLoanApplication();
        Residential_Address__c rs = new Residential_Address__c();
        rs.City__c = 'Melbourne';
        rs.Country__c = 'Australia';
        rs.Current_Address__c=true;
        rs.Street_Number__c='123';
        rs.Street_Name__c='Privet';
        rs.Street_Type__c='ST';
        rs.Suburb__c='Little Whinging';
        rs.State__c='NSW';
        rs.Property__c='Potter Manor';
        rs.Unit_Number__c='3';
        rs.PostCode__c='2999';
        rs.Country_Code__c='AUS';
        rs.Application__c=app.Id;
        insert rs;
        //TestHelper.insertIDMatrixCustomSetting();
        System.debug('app='+app.Id);
        VedaResponse vr = new VedaResponse();
        DandBImpl  v  = new DandBImpl();
        Decisioning_Configuration__c c = new Decisioning_Configuration__c();
        c.Name='DandB';
        c.Active__c=true;
        c.Callout_Class_Name__c='DandBImpl';
        c.Order__c=1;
        c.Parser_Class_Name__c='DandBParser';
        c.Response_Class_Name__c='ints.DunAndBradstreetResponse';
        insert c;
        vr.app=app;
        Test.startTest();
        VedaServices.webServiceDanB(app.Id);
        Test.stopTest();
    }    
    

}