objects/Application__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to save the stage of pages after click on continue button.</description>
    <fields>
        <fullName>Navigation_Status__c</fullName>
        <label>Navigation Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RedirectPage__c</fullName>
        <label>RedirectPage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Navigation Status</label>
</CustomObject>

objects/pages_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Page_Label__c</fullName>
        <label>Page_Label</label>
        <type>TextArea</type>
    </fields>
    <label>pages_config</label>
</CustomObject>

objects/RetrieveCode__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RetrieveCode</label>
</CustomObject>

classes/pepCreditPolicyController_Tracker.cls
@isTest(SeeAllData=False)

private class pepCreditPolicyController_Tracker 
{
    
    @isTest static void pepCreditPolicyControllerTest0() {
    
        pepCommonTrackerController obj =new pepCommonTrackerController(); 
        
        genesis__Applications__c objApplication = new genesis__Applications__c();
        RetrieveCode__c objRetrieveCode = pepCommonTrackerController.createRetrieveCode();
        objApplication = genesis.TestHelper.createApplication();
        objApplication.Debit_Frequency__c ='bi-weekly';
        update objApplication;
        
         Application__c o = new Application__c();
        o.Name='pepContract';
        o.Navigation_Status__c='LoanSetup-Contract';
        o.RedirectPage__c='pepContract';
        insert o;
        
        Application__c o1 = new Application__c();
        o1.Name='pepLoanSetupCreditPolicy';
        o1.Navigation_Status__c='LoanSetup-ReadCreditPolicy';
        o1.RedirectPage__c='pepLoanSetupCreditPolicy';
        insert o1;
        
          pages_config__c pg11 = new pages_config__c(Name='pepsession',Page_Label__c='Session');
            insert pg11;

        
        Pagereference pd=Page.pepPaymentSetup;
        Test.setcurrentPagereference(pd);
        Cookie Applicationid=new Cookie('Applicationid',pepEncryptDecryptData.EncryptData(String.valueof(objApplication.id)),'-1',null,false);
        pd.setcookies(new cookie[]{Applicationid});
        
        Application__c app = new Application__c();
        app = pepCommonTrackerController.createApplication();
        app.Name= 'pepContract';
        app.Navigation_Status__c='LoanSetup-Contract';
        app.RedirectPage__c='pepContract';
        update app;
        
        Application__c app1 = new Application__c();
        app1 = pepCommonTrackerController.createApplication();
        app1.Name= 'pepLoanSetupCreditPolicy';
        app1.Navigation_Status__c='LoanSetup-ReadCreditPolicy';
        app1.RedirectPage__c='pepLoanSetupCreditPolicy';
        update app1;
        
        pepCreditPolicyController objClass = new pepCreditPolicyController();
        objClass.checkcookie();
        objClass.saveForLater();
        objClass.saveAndRedirect();
    }
}