objects/Application__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to save the stage of pages after click on continue button.</description>
    <label>Application Navigation Status</label>
</CustomObject>

objects/DandB__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>genesis__Applications__c</referenceTo>
        <relationshipLabel>DandB</relationshipLabel>
        <relationshipName>DandB</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DandB</label>
    <nameField>
        <displayFormat>DnB-{0000000000}</displayFormat>
        <label>DanB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DandB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RetrieveCode__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>RetrieveCode</label>
</CustomObject>

objects/Veda_Comprehensive__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>genesis__Applications__c</referenceTo>
        <relationshipLabel>Veda Comprehensive</relationshipLabel>
        <relationshipName>Veda_Comprehensive</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Veda Comprehensive</label>
    <nameField>
        <displayFormat>VC-{0000000000}</displayFormat>
        <label>Veda Comprehensive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Veda Comprehensive</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Veda_Fraud__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>genesis__Applications__c</referenceTo>
        <relationshipLabel>Veda Fraud</relationshipLabel>
        <relationshipName>Veda_Fraud</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Veda Fraud</label>
    <nameField>
        <displayFormat>VF-{0000000000}</displayFormat>
        <label>Veda Fraud Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Veda Fraud</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Veda_IdMatrix__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>genesis__Applications__c</referenceTo>
        <relationshipLabel>Veda IdMatrix</relationshipLabel>
        <relationshipName>Veda_IdMatrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Veda IdMatrix</label>
    <nameField>
        <displayFormat>VID-{0000000000}</displayFormat>
        <label>Veda IdMatrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Veda IdMatrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestUncheckShowFlagDetails.cls
@isTest
public class TestUncheckShowFlagDetails {
    public static testMethod void UncheckVedaFraud(){
        RetrieveCode__c mc =  new RetrieveCode__c();
        mc.code__c='AAA14341';
        insert mc;
        Account ac = genesis.TestHelper.createAccount();
        genesis__Applications__c app=TestHelper.createLoanApplication();
        
        Veda_Fraud__c vf = new Veda_Fraud__c();
        vf.Application__c=app.Id;
        insert vf;
        test.startTest();
        UncheckShowDetailsFlag.uncheckShowDetaislFlagOfVedaFraud(vf.Id,app.Id);
        test.stopTest();
    }
     public static testMethod void UncheckVedaComprehensive(){
        RetrieveCode__c mc =  new RetrieveCode__c();
        mc.code__c='AAA14341';
        insert mc;
        Account ac = genesis.TestHelper.createAccount();
        genesis__Applications__c app=TestHelper.createLoanApplication();
        
        Veda_Comprehensive__c vc = new Veda_Comprehensive__c();
        vc.Application__c=app.Id;
        insert vc;
        test.startTest();
        UncheckShowDetailsFlag.uncheckShowDetaislOfVedaComprehensive(vc.Id,app.Id);
        test.stopTest();
         
    }
     public static testMethod void UncheckIdMatrix(){
        RetrieveCode__c mc =  new RetrieveCode__c();
        mc.code__c='AAA14341';
        insert mc;
        Account ac = genesis.TestHelper.createAccount();
        genesis__Applications__c app=TestHelper.createLoanApplication();
        
        Veda_IdMatrix__c IdMtx = new Veda_IdMatrix__c();
        IdMtx.Application__c=app.Id;
        insert IdMtx;
        test.startTest();
        UncheckShowDetailsFlag.uncheckShowDetaislOfIdMatrix(IdMtx.Id,app.Id);
        test.stopTest();
    }
    public static testMethod void UncheckDandB(){
        RetrieveCode__c mc =  new RetrieveCode__c();
        mc.code__c='AAA14341';
        insert mc;
        Account ac = genesis.TestHelper.createAccount();
        genesis__Applications__c app=TestHelper.createLoanApplication();
        
        DandB__c dandb = new DandB__c();
        dandb.Application__c=app.Id;
        insert dandb;
        test.startTest();
        UncheckShowDetailsFlag.uncheckShowDetaislOfDanB(dandb.Id,app.Id);
        test.stopTest();
    }
    
    public static testMethod void testUncheckCollateral(){
        
        Test.startTest();
        genesis__Applications__c app=TestHelper.createLoanApplication();
        clcommon__Collateral__c col = new clcommon__Collateral__c(
                                clcommon__Collateral_Name__c = 'ABC',genesis__Application__c= app.id);
        insert col;
        clcommon__Collateral__c col1 = new clcommon__Collateral__c(
                                clcommon__Collateral_Name__c = 'ABC',genesis__Application__c= app.id);
        insert col1;
        
        UncheckShowDetailsFlag.uncheckShowDetailsFlagForCollateral(col.Id);
        
        Test.stopTest();
    }
}