objects/Collections_Sync_Job_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Check_Sync_Job_Data_Exists__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables a validation that ALL Sync Job data has to exist  before SyncJob2 is called</description>
        <inlineHelpText>Enables a validation that ALL Sync Job data has to exist  before SyncJob2 is called</inlineHelpText>
        <label>Check Sync Job Data Exists</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EmailESBStagingSyncProcess__c</fullName>
        <label>EmailESBStagingSyncProcess</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EmailStagingActualSyncProcess__c</fullName>
        <label>EmailStagingActualSyncProcess</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EmailsToGetFilesMissingAlert__c</fullName>
        <description>Email Addresses that will receive Missing Sync File Notifications</description>
        <inlineHelpText>Email Addresses that will receive Missing Sync File Notifications</inlineHelpText>
        <label>EmailsToGetFilesMissingAlert</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Enable_Email_Alerts__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables Email Alert for Sync Job validations</description>
        <inlineHelpText>Enables Email Alert for Sync Job validations</inlineHelpText>
        <label>Enable Email Alerts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_SMS_Alerts__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable SMS Alerts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_Sync_Job_API_Settings__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this field is ticked these settings are used by the CLCollectionsWebServices.SyncJobService when invoking SyncJob2, if not checked the settings are taken from the @HttpPost method</description>
        <inlineHelpText>If this field is ticked these settings are used by the CLCollectionsWebServices.SyncJobService when invoking SyncJob2, if not checked the settings are taken from the @HttpPost method</inlineHelpText>
        <label>Override Sync Job API Settings</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Processes_Names_Mortgage__c</fullName>
        <label>Processes Names(Mortgage)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Processes_Names_PAF__c</fullName>
        <label>Processes Names(PAF)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SMS_Recipients_For_Sync_Data_Failures__c</fullName>
        <description>Mobile numbers to receive Sync Job alert</description>
        <inlineHelpText>Mobile numbers to receive Sync Job alert</inlineHelpText>
        <label>SMS Recipients For Sync Data Failures</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SMS_Template_AllFilesReceivedProcess__c</fullName>
        <label>SMS Template(AllFilesReceivedProcess)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sync_Job_Batch_Size__c</fullName>
        <description>Controls the Batch Size that is passed into SyncJob2 when called by the ESB and Override API Settings = true</description>
        <inlineHelpText>Controls the Batch Size that is passed into SyncJob2 when called by the ESB and Override API Settings = true</inlineHelpText>
        <label>Sync Job Batch Size</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sync_Job_Invokes_Create_Activity_Job__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Controls whether or not the SyncJob2 invokes CreateOtherCollectionsActivityJob on completion, if Override = True</description>
        <inlineHelpText>Controls whether or not the SyncJob2 invokes CreateOtherCollectionsActivityJob on completion, if Override = True</inlineHelpText>
        <label>Sync Job Invokes Create Activity Job</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_Job_Parent_Table__c</fullName>
        <description>The first Object to be Sync&apos;d - normally interface__Staging_Bank_Account__c if Override = True</description>
        <inlineHelpText>The first Object to be Sync&apos;d - normally interface__Staging_Bank_Account__c if Override = True</inlineHelpText>
        <label>Sync Job Parent Table</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Job_Submit_Next_Job__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Controls whether or not the Staging Objects are chained together or just the Parent is run on its own if Override = True</description>
        <inlineHelpText>Controls whether or not the Staging Objects are chained together or just the Parent is run on its own if Override = True</inlineHelpText>
        <label>Sync Job Submit Next Job</label>
        <type>Checkbox</type>
    </fields>
    <label>Collections Sync Job Settings</label>
</CustomObject>

objects/Sms_Magic__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to store sms settings</description>
    <fields>
        <fullName>senderId__c</fullName>
        <label>senderId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sms Magic</label>
</CustomObject>

classes/ScCollection_TestTrgOnSyncStatHandler.cls
/*------------------------------------------------------------
Author:        Sandip Bijlwan
Name:          ScCollection_TestTrgOnSyncStatHandler
Company:       Saasfocus
Description:   This class is use to test the trigger behavious.
History
2/08/2017      Sandip Bijlwan     
------------------------------------------------------------*/
@isTest(SeeAllData=False) Public Class ScCollection_TestTrgOnSyncStatHandler{
    
    /*------------------------------------------------------------
        Author:        Sandip Bijlwan
        Name:          test0
        Company:       Saasfocus
        Description:   This method is used to test send sms and email notification.
        Inputs:        no input.
        Returns:       void
        ------------------------------------------------------------*/
    @istest static void test0(){
        
        Collections_Sync_Job_Settings__c objErr = new Collections_Sync_Job_Settings__c();

        objErr.EmailESBStagingSyncProcess__c = 'ahumby@pepper.com.au';
        objErr.EmailStagingActualSyncProcess__c = 'ahumby@pepper.com.au';
        objErr.EmailsToGetFilesMissingAlert__c = 'ahumby@pepper.com.au';
        objErr.Enable_Email_Alerts__c = true;
        objErr.Check_Sync_Job_Data_Exists__c = true;
        objErr.SMS_Recipients_For_Sync_Data_Failures__c = '1234567890';
        objErr.SMS_Template_AllFilesReceivedProcess__c = 'SMS Template text';
        objErr.Processes_Names_Mortgage__c = 'Contracts,Transactions,Bank-Accounts,Party';
        objErr.Processes_Names_PAF__c = 'Contracts,Transactions,Bank-Accounts,Party';
        objErr.Enable_SMS_Alerts__c = true;
        objErr.Override_Sync_Job_API_Settings__c = true;
        objErr.Sync_Job_Batch_Size__c = 1000;
        objErr.Sync_Job_Invokes_Create_Activity_Job__c = true;
        objErr.Sync_Job_Submit_Next_Job__c = true;
        objErr.Sync_Job_Parent_Table__c = 'staging__Interface_Bank_Account__c';
        insert objErr;
        
        Sms_Magic__c objMagic = new Sms_Magic__c();
        objMagic.Name='CollectionSenderId';
        objMagic.senderId__c='PepperMoney';
        insert objMagic;
        
        collect__Sync_Statistics__c objStats = new collect__Sync_Statistics__c(
                                                            collect__Batch_Id__c = '707p000000DUM5IAAX',
                                                            collect__Num_Errors__c = 1,
                                                            collect__Parent_Batch_Id__c = '707p000000DUM5IAAX',
                                                            collect__Records_Deleted__c = 0.0,
                                                            collect__Records_Inserted__c = 20.0,
                                                            collect__Records_Processed__c = 20.0,
                                                            collect__Records_Read__c = 20.0,
                                                            collect__Records_Updated__c = 0.0,
                                                            collect__Source_Table__c = 'staging__interface_bank_account__c',
                                                            collect__Target_Table__c = 'collect__bank_account__c');
        test.StartTest();
        insert objStats;
        test.StopTest();
        
        smagicinteract__smsMagic__c objsmsmagic = [Select id,smagicinteract__PhoneNumber__c  from smagicinteract__smsMagic__c limit 1];
        system.assert(objsmsmagic.smagicinteract__PhoneNumber__c =='1234567890','worked');
    }

}