objects/CRM_Annual_KPI__c.object
<CustomObject>
    <fields>
        <fullName>CRM_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRM_Annual_KPIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRM_Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2017-2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018-2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019-2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020-2021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021-2022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2022-2023</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2023-2024</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Annual KPI</label>
    <nameField>
        <label>Annual KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual KPIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_KPI__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Annual_KPI__c</fullName>
        <label>Annual KPI</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.CRM_User__c</field>
                <operation>equals</operation>
                <valueField>CRM_Annual_KPI__c.CRM_User__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.CRM_Year__c</field>
                <operation>equals</operation>
                <valueField>CRM_Annual_KPI__c.CRM_Year__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CRM_Annual_KPI__c</referenceTo>
        <relationshipName>CRM_KPIs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CRM_From__c</fullName>
        <label>From</label>
        <summarizedField>CRM_Monthly_Target_and_Achievement__c.CRM_From__c</summarizedField>
        <summaryForeignKey>CRM_Monthly_Target_and_Achievement__c.CRM_KPI__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CRM_Quarter__c</fullName>
        <label>Quarter</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_To__c</fullName>
        <label>To</label>
        <summarizedField>CRM_Monthly_Target_and_Achievement__c.CRM_To__c</summarizedField>
        <summaryForeignKey>CRM_Monthly_Target_and_Achievement__c.CRM_KPI__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CRM_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRM_User_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRM_Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2017-2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018-2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019-2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020-2021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021-2022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2022-2023</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2023-2024</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Quarterly Target And Achievement</label>
    <nameField>
        <label>Quarterly Target And Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quarterly Target And Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CRM_Monthly_Target_and_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>CRM_From__c</fullName>
        <label>From</label>
        <summarizedField>CRM_Weekly_Target_and_Achievement__c.CRM_From__c</summarizedField>
        <summaryForeignKey>CRM_Weekly_Target_and_Achievement__c.CRM_Monthly_Target_and_Achievement__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CRM_KPI__c</fullName>
        <label>Quarterly Target and Achievements</label>
        <referenceTo>CRM_KPI__c</referenceTo>
        <relationshipLabel>Monthly Target and Achievements</relationshipLabel>
        <relationshipName>Monthly_Target_and_Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CRM_Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>JANUARY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FEBRUARY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MARCH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APRIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JUNE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JULY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUGUST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEPTEMBER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OCTOBER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOVEMBER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DECEMBER</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_To__c</fullName>
        <label>To</label>
        <summarizedField>CRM_Weekly_Target_and_Achievement__c.CRM_To__c</summarizedField>
        <summaryForeignKey>CRM_Weekly_Target_and_Achievement__c.CRM_Monthly_Target_and_Achievement__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Monthly Target and Achievement</label>
    <nameField>
        <label>Monthly Target and Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Target and Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CRM_Weekly_Target_and_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>CRM_From__c</fullName>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CRM_Monthly_Target_and_Achievement__c</fullName>
        <label>Monthly Target and Achievement</label>
        <referenceTo>CRM_Monthly_Target_and_Achievement__c</referenceTo>
        <relationshipLabel>Weekly Target and Achievements</relationshipLabel>
        <relationshipName>Weekly_Target_and_Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CRM_To__c</fullName>
        <label>To</label>
        <type>Date</type>
    </fields>
    <label>Weekly Target and Achievement</label>
    <nameField>
        <label>Weekly Target and Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weekly Target and Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CRMMonthlyTrgtAndAchmentHndlr_Tracker.cls
/*------------------------------------------------------------
Author:        Sandip Bijlwan
Name:          CRMMonthlyTrgtAndAchmentHndlr_Tracker
Company:       Saasfocus
Description:   This class is use to test the trigger behavious.  
------------------------------------------------------------*/
@isTest(SeeAllData=False)
Public class CRMMonthlyTrgtAndAchmentHndlr_Tracker{
    
    /*------------------------------------------------------------------------------
    Author:        Sandip Bijlwan
    Name:          testWeeklyTargetAndAchievement
    Company:       Saasfocus
    Description:   This method is used to test Trigger Working.
    Inputs:        no input
    Returns:       void
    -----------------------------------------------------------------------------------*/
    
    @isTest
    Public static void testWeeklyTargetAndAchievement(){
        
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Id = :userInfo.getProfileId()]; 
        User u = new User(Alias = 'testcrm', Email='testcrmuser@testpepper.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testcrmuser@testpepper.com');
        insert u;   
        CRM_Annual_KPI__c objAnualKpi;
        Test.startTest();
        System.runAs(u){
            objAnualKpi= new CRM_Annual_KPI__c(
                            Name = 'test data',
                            CRM_User__c = u.Id,
                            CRM_Year__c = '2017-2018');
            insert objAnualKpi;
            
        }
        Test.stopTest();
        List<CRM_KPI__c> lstQuarterlyKpi = [Select Id From CRM_KPI__c where CRM_Annual_KPI__c = :objAnualKpi.Id and RecordTypeId= : 
                                            Schema.SObjectType.CRM_KPI__c.getRecordTypeInfosByName().get(Label.CRM_RT_Settled).getRecordTypeId() and CRM_Quarter__c = '1'];
        List<CRM_Monthly_Target_and_Achievement__c> lstMonthly = [Select Id from CRM_Monthly_Target_and_Achievement__c Where 
                                                                CRM_KPI__c = :lstQuarterlyKpi[0].Id and CRM_Month__c = 'JANUARY'];  
        
        List<CRM_Weekly_Target_and_Achievement__c> lstWeeklyRecords = [Select Id,Name,CRM_From__c,CRM_To__c From CRM_Weekly_Target_and_Achievement__c Where 
                                                                       CRM_Monthly_Target_and_Achievement__c  = :lstMonthly[0].Id];
                                                                       
        System.assertEquals(lstWeeklyRecords[0].Name,'Week 1 Target and Achievement');
        
    }

}