objects/CRM_Borrowing_Power_Living_Expense__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Couple_Base__c</fullName>
        <label>Couple Base</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Couple_Increment__c</fullName>
        <label>Couple Increment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Dependant_Base__c</fullName>
        <label>Dependant Base</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Lower_Threshold__c</fullName>
        <label>Lower Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Single_Adult_Base__c</fullName>
        <label>Single Adult Base</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Single_Adult_Increment__c</fullName>
        <label>Single Adult Increment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Borrowing Power Living Expense</label>
    <nameField>
        <displayFormat>BPLE-{0000}</displayFormat>
        <label>Borrowing Power Living Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowing Power Living Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_Borrowing_Power_Other__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Credit_Card_Multiplier__c</fullName>
        <label>Credit Card Multiplier</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Mortgage_Debt_Rate__c</fullName>
        <label>Mortgage Debt Rate</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_NSR__c</fullName>
        <label>NSR</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Rent_Rate__c</fullName>
        <label>Rent Rate</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CRM_Term_Years__c</fullName>
        <label>Term Years</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Borrowing Power (Other)</label>
    <nameField>
        <displayFormat>BPOE-{0000}</displayFormat>
        <label>Borrowing Power (Other) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowing Power</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_Borrowing_Power_Rate__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Credit_Impairment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Impairment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_Rate__c</fullName>
        <label>Rate</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Self_Employed_Months__c</fullName>
        <label>Self Employed Months</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Self_Employed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Self Employed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CRM_Type_Detail__c</fullName>
        <label>Type Detail</label>
        <picklist>
            <picklistValues>
                <fullName>Non-Conforming Full Doc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Conforming Low Doc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime Full Doc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime Low Doc</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>NCFD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PFD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Borrowing Power Rate</label>
    <nameField>
        <displayFormat>BPR-{00000}</displayFormat>
        <label>Borrowing Power Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowing Power Rate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_Tax_Rates__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Bracket_Amount__c</fullName>
        <label>Bracket Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Bracket_Max__c</fullName>
        <label>Bracket Max</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Bracket_Min__c</fullName>
        <label>Bracket Min</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Bracket_Rate__c</fullName>
        <label>Bracket Rate</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CRM_Type_Description__c</fullName>
        <label>Type Description</label>
        <picklist>
            <picklistValues>
                <fullName>PAYG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Employed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medicare Levy</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_Type__c</fullName>
        <label>Type</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tax Rates</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Tax Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CRM_Borrower_Count__c</fullName>
        <label>Borrower count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Credit_Impairment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit impairment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_Email__c</fullName>
        <label>Email</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Est_Rent_Income__c</fullName>
        <label>Est. rent income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CRM_Gross_Income_Borrower_1__c</fullName>
        <label>Gross income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CRM_Lead_Channel_Level_2__c</fullName>
        <label>Lead channel level 2</label>
        <picklist>
            <controllingField>CRM_Lead_Channel__c</controllingField>
            <picklistValues>
                <fullName>General Phone number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign specific phone number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSC transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_Lead_Channel__c</fullName>
        <label>Lead channel level 1</label>
        <picklist>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_Loan_Purpose__c</fullName>
        <label>Loan purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>CRM_Rate__c</fullName>
        <label>Rate</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Party__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Company__c</fullName>
        <label>Company</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Credit_Impairment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Impairment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CRM_Gross_Income_Frequency__c</fullName>
        <label>Gross Income Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Gross_Income__c</fullName>
        <label>Gross Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CRM_Months_Self_Employed__c</fullName>
        <label>Months Self Employed</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Name__c</fullName>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CRM_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Co Borrower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guarantor</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_Years_Self_Employed__c</fullName>
        <label>Years Self Employed</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Party</label>
    <nameField>
        <displayFormat>A-{00}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Party</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/crmCalculatingBorrowingPower_Tracker.cls
@isTest public class crmCalculatingBorrowingPower_Tracker{
    
    @isTest static void Test0(){
        
        Lead objLead = new Lead();
        objLead.lastname = 'test';
        objLead.Company = 'comp';
        objLead.CRM_Lead_Channel__c = 'Digital';
        objLead.CRM_Lead_Channel_Level_2__c='Email';
        objLead.CRM_Est_Rent_Income__c = 200000;
        objLead.CRM_Gross_Income_Borrower_1__c  = 20000000;
        objLead.CRM_Borrower_Count__c = 2;
        objLead.CRM_Loan_Purpose__c ='Purchase' ;
        
        insert objLead;
        
        Party__c part = new party__c();
        part.CRM_Name__c='ConName' ;
        part.CRM_Email__c = 'test@email.com' ;
        part.CRM_Phone__c = '1';
        part.CRM_Type__c = 'Co Borrower';
        part.CRM_Company__c = 'testAccount';
        part.Lead__c = objLead.id;
        part.CRM_Credit_Impairment__c = true;
        part.CRM_Months_Self_Employed__c ='2';
        part.CRM_Years_Self_Employed__c ='1';
        part.CRM_Gross_Income__c = 20000000;
        part.CRM_Gross_Income_Frequency__c = '200000';
        
        insert part;
        
        CRM_Borrowing_Power_Other__c borrTax = new CRM_Borrowing_Power_Other__c();
        borrTax.CRM_Term_Years__c =30;
        borrTax.CRM_Credit_Card_Multiplier__c =0.0300;
        borrTax.CRM_NSR__c=1;
        borrTax.CRM_Rent_Rate__c=0.0800;
        borrTax.CRM_Start_Date__c=System.Today()-455;
        borrTax.CRM_Mortgage_Debt_Rate__c=0.2000;
        
        insert borrTax;
        
        List<CRM_Tax_Rates__c> lstTax = new List<CRM_Tax_Rates__c>();
        CRM_Tax_Rates__c taxRate = new CRM_Tax_Rates__c();
        taxRate.CRM_Type__c = 1;
        taxRate.CRM_Type_Description__c = 'PAYG';
        taxRate.CRM_Bracket_Min__c = 180001.00 ;
        taxRate.CRM_Bracket_Rate__c = 0.4500;
        taxRate.CRM_Start_Date__c = System.Today()-455;
        lstTax.add(taxRate);
        
        CRM_Tax_Rates__c taxRate1 = new CRM_Tax_Rates__c();
        taxRate1.CRM_Type__c = 1;
        taxRate1.CRM_Type_Description__c = 'PAYG';
        taxRate1.CRM_Bracket_Min__c = 37001.00 ;
        taxRate1.CRM_Bracket_Max__c = 80000.00;
        taxRate1.CRM_Bracket_Rate__c = 0.3250;
        taxRate1.CRM_Bracket_Amount__c = 13975.00;
        taxRate1.CRM_Start_Date__c = System.Today()-455;
        lstTax.add(taxRate1);
        
        CRM_Tax_Rates__c taxRate2 = new CRM_Tax_Rates__c();
        taxRate2.CRM_Type__c = 3;
        taxRate2.CRM_Type_Description__c = 'Medicare Levy';
        taxRate2.CRM_Bracket_Min__c = 20542.00 ;
        taxRate2.CRM_Bracket_Max__c = 24166.00;
        taxRate2.CRM_Bracket_Rate__c = 0.1000;
        taxRate2.CRM_Bracket_Amount__c = 362.50;
        taxRate2.CRM_Start_Date__c = System.Today()-455;
        lstTax.add(taxRate2);
        
        CRM_Tax_Rates__c taxRate3 = new CRM_Tax_Rates__c();
        taxRate3.CRM_Type__c = 1;
        taxRate3.CRM_Type_Description__c = 'PAYG';
        taxRate3.CRM_Bracket_Min__c = 0.00;
        taxRate3.CRM_Bracket_Max__c = 20541.00;
        taxRate3.CRM_Bracket_Rate__c = 0.0000;
        taxRate3.CRM_Bracket_Amount__c = 0.00;
        taxRate3.CRM_Start_Date__c = System.Today()-455;
        lstTax.add(taxRate3);
        
        insert lstTax;
        
        List<CRM_Borrowing_Power_Rate__c> lstBorrRate = new List<CRM_Borrowing_Power_Rate__c>();
        CRM_Borrowing_Power_Rate__c powRate = new CRM_Borrowing_Power_Rate__c();
        powRate.CRM_Type_Detail__c = 'Prime Full Doc';
        powRate.CRM_Type__c = 'PFD';
        powRate.CRM_Credit_Impairment__c = false;
        powRate.CRM_Self_Employed__c = false;
        powRate.CRM_Rate__c = 0.0720;
        powRate.CRM_Start_Date__c = System.Today()-455 ;
        powRate.CRM_Self_Employed_Months__c = 0;
        lstBorrRate.add(powRate);
        
        CRM_Borrowing_Power_Rate__c powRate1 = new CRM_Borrowing_Power_Rate__c();
        powRate1.CRM_Type_Detail__c = 'Non-Conforming Low Doc';
        powRate1.CRM_Type__c = 'NCLD';
        powRate1.CRM_Credit_Impairment__c = true;
        powRate1.CRM_Self_Employed__c = true;
        powRate1.CRM_Rate__c = 0.0804;
        powRate1.CRM_Start_Date__c = System.Today()-455 ;
        powRate1.CRM_Self_Employed_Months__c = 0;
        lstBorrRate.add(powRate1);
        
        CRM_Borrowing_Power_Rate__c powRate2 = new CRM_Borrowing_Power_Rate__c();
        powRate2.CRM_Type_Detail__c = 'Non-Conforming Full Doc';
        powRate2.CRM_Type__c = 'NCFD';
        powRate2.CRM_Credit_Impairment__c = true;
        powRate2.CRM_Self_Employed__c = false;
        powRate2.CRM_Rate__c = 0.0799;
        powRate2.CRM_Start_Date__c = System.Today()-455 ;
        powRate2.CRM_Self_Employed_Months__c = 0;
        lstBorrRate.add(powRate2);
        
        CRM_Borrowing_Power_Rate__c powRate3 = new CRM_Borrowing_Power_Rate__c();
        powRate3.CRM_Type_Detail__c = 'Prime Low Doc';
        powRate3.CRM_Type__c = 'PLD';
        powRate3.CRM_Credit_Impairment__c = false;
        powRate3.CRM_Self_Employed__c = true;
        powRate3.CRM_Rate__c = 0.0720;
        powRate3.CRM_Start_Date__c = System.Today()-455 ;
        powRate3.CRM_Self_Employed_Months__c = 24;
        lstBorrRate.add(powRate3);
        
        insert lstBorrRate;
        
        CRM_Borrowing_Power_Living_Expense__c objLiving = new CRM_Borrowing_Power_Living_Expense__c();
        objLiving.CRM_Lower_Threshold__c = 600000.00;
        objLiving.CRM_Single_Adult_Increment__c = 5.00;
        objLiving.CRM_Single_Adult_Base__c = 15564.00;
        objLiving.CRM_Couple_Base__c = 26724.00;
        objLiving.CRM_Couple_Increment__c = 10.00;
        objLiving.CRM_Dependant_Base__c = 5520.00;
        objLiving.CRM_Couple_Increment__c = 3.00;
        objLiving.CRM_Start_Date__c = System.Today()-455;
        
        insert objLiving;
        
     /*   
        crmCalculatingBorrowingPower objClass = new crmCalculatingBorrowingPower();
        crmCalculatingBorrowingPower.fetchBorrowingPower(objLead.id,part.id);
     */   
        CRMLeadRest obj = new CRMLeadRest();
        CRMLeadRest.getBorrPowerFromLeadID(objLead.id,part.id);
        CRMLeadRest.getBorrPowerFromLeadID(objLead.id,null);
        CRMLeadRest.getBorrPowerFromLeadID(part.id,null);
    }
    
    
    
}