objects/CRM_Application__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Net_Amount_Financed_Amount__c</fullName>
        <label>Net Amount Financed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CRM_Primary_Introducer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Introducer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications (Primary Introducer)</relationshipLabel>
        <relationshipName>Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRM_Settlement_Date__c</fullName>
        <label>Settlement Date</label>
        <type>Date</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>PAF</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_Forecast_Year__c</fullName>
        <label>Forecast Year</label>
        <picklist>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2023</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2024</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2025</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_Introducer__c</fullName>
        <label>Introducer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Forecasts</relationshipLabel>
        <relationshipName>Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Forecast</label>
    <nameField>
        <label>Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CRMTrgOnApplicationTracker.cls
@isTest(SeeAllData = False) Public class CRMTrgOnApplicationTracker{
    
    @isTest static void test0(){
        
        Account objAccount = new Account();
        objAccount.Name = 'testingAccount';
        insert objAccount;
        
        CRM_Forecast__c objForecast = new CRM_Forecast__c();
        objForecast.Name='hah';
        objForecast.CRM_Forecast_Year__c = '2017';
        objForecast.CRM_Business_Unit__c = 'PAF';
        objForecast.CRM_Introducer__c = objAccount.id;
        insert objForecast;
        CRM_Application__c objApplication1 = new CRM_Application__c();
        objApplication1.CRM_Primary_Introducer__c = objAccount.id;
        objApplication1.CRM_Net_Amount_Financed_Amount__c = 20000;
        objApplication1.CRM_Settlement_Date__c = Date.newInstance(2017,1,1);
        objApplication1.Name = 'rec 2017';
        insert objApplication1;
        
        objApplication1.CRM_Settlement_Date__c = Date.newInstance(2017,2,1);
        update objApplication1;
        
            
        List<CRM_Application__c> lstApp = new List<CRM_Application__c>();
        for(integer i=1;i<=12;i++){
            CRM_Application__c objApplication = new CRM_Application__c();
            objApplication.CRM_Primary_Introducer__c = objAccount.id;
            objApplication.CRM_Net_Amount_Financed_Amount__c = 20000;
            objApplication.CRM_Settlement_Date__c = Date.newInstance(2017,i,1);
            objApplication.Name = 'rec 2017 '+i;
            lstApp.add(objApplication);
        }
         for(integer i=1;i<=12;i++){
            CRM_Application__c objApplication = new CRM_Application__c();
            objApplication.CRM_Primary_Introducer__c = objAccount.id;
            objApplication.CRM_Net_Amount_Financed_Amount__c = 20000;
            objApplication.CRM_Settlement_Date__c = Date.newInstance(2017,i,1);
            objApplication.Name = 'rec1 2017 '+i;
            lstApp.add(objApplication);
        }
        for(integer i=1;i<=12;i++){
            CRM_Application__c objApplication = new CRM_Application__c();
            objApplication.CRM_Primary_Introducer__c = objAccount.id;
            
            objApplication.CRM_Settlement_Date__c = Date.newInstance(2017,i,1);
            objApplication.Name = 'rec1 2017 '+i;
            lstApp.add(objApplication);
        }
        insert lstApp;
        
        
        

    }
    
}