objects/CRM_Annual_KPI__c.object
<CustomObject>
    <fields>
        <fullName>CRM_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRM_Annual_KPIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRM_Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2017-2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018-2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019-2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020-2021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021-2022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2022-2023</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2023-2024</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Annual KPI</label>
    <nameField>
        <label>Annual KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual KPIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_Related_Party__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Related Party</relationshipLabel>
        <relationshipName>Related_Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRM_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Co Borrower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guarantor</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Related Party</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Related Party Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Party</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CRM_Email__c</fullName>
        <label>Email</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Lead_Channel_Level_2__c</fullName>
        <label>Lead channel level 2</label>
        <picklist>
            <controllingField>CRM_Lead_Channel__c</controllingField>
            <picklistValues>
                <fullName>General Phone number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign specific phone number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSC transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_Lead_Channel__c</fullName>
        <label>Lead channel level 1</label>
        <picklist>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>PAF</fullName>
        <active>true</active>
        <businessProcess>PAF</businessProcess>
        <label>PAF</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CRM_Lead_Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Email Enquiry Leads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Enquiry PAF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSC Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Form - Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Form Apps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Form Apps - A/R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WSW - ARM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WSW - Direct</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>PAF</fullName>
        <active>true</active>
        <businessProcess>PAF Sales process</businessProcess>
        <label>PAF</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Party__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Company__c</fullName>
        <label>Company</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Create_New_Business_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create New Business Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_Create_New_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create New Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_Create_New_Person_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create New Person Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CRM_Existing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Existing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Party</relationshipLabel>
        <relationshipName>Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRM_Existing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Existing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Party</relationshipLabel>
        <relationshipName>Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRM_Name__c</fullName>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CRM_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Co Borrower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guarantor</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Party</label>
    <nameField>
        <displayFormat>A-{00}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Party</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CRMTrgOnLead_Tracker.cls
/*------------------------------------------------------------
Author:        Sandip Bijlwan
Name:          CRMTrgOnLead_Tracker
Company:       Saasfocus
Description:   This class is use to test the trigger behavious.  
------------------------------------------------------------*/
@isTest(SeeAllData=False)
public class CRMTrgOnLead_Tracker{
    
      /*------------------------------------------------------------------------------
    Author:        Sandip Bijlwan
    Name:          testLeadTrigger
    Company:       Saasfocus
    Description:   This method is used to test Trigger Working.
    Inputs:        no input
    Returns:       void
    -----------------------------------------------------------------------------------*/

    @isTest static void testLeadTrigger(){
        
        Profile p = [SELECT Id FROM Profile WHERE Id = :userInfo.getProfileId()]; 
        User u = new User(Alias = 'testcrm', Email='testcrmuser@testpepper.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testcrmuser@testpepper.com');
        insert u;   
        CRM_Annual_KPI__c objAnualKpi;
        System.runAs(u){
            
            objAnualKpi= new CRM_Annual_KPI__c(
                            Name = 'test data',
                            CRM_User__c = u.Id,
                            CRM_Year__c = '2017-2018');
            insert objAnualKpi;
            
            Lead objLead = new Lead();
            objLead.LastName ='lastLeadName';
            objLead.Company = 'CompanyOfLead';
            objLead.CRM_Lead_Channel__c = 'Digital';
            objLead.CRM_Lead_Channel_Level_2__c = 'Email';
            objLead.OwnerId = u.Id;
            objLead.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('PAF').getRecordTypeId();
            insert objLead;
            
            Lead objLead1 = new Lead();
            objLead1.LastName ='lastLeadName1';
            objLead1.Company = 'CompanyOfLead1';
            objLead1.CRM_Lead_Channel__c = 'Digital';
            objLead1.CRM_Lead_Channel_Level_2__c = 'Email';
            objLead1.OwnerId = u.Id;
            objLead1.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('PAF').getRecordTypeId();
            insert objLead1;
            
            Account acc = new Account(Name= 'testAccount');
            insert acc;
            Account acc1 = new Account(Name= 'testAccount1');
            insert acc1;
            
            id reid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
            
            Account perAcc = new Account(LastName = 'PerName' , personEmail ='per@email.com',recordtypeid = reid);
            insert perAcc;
            
            Contact objCon = new Contact(LastName = 'ConName' ,Accountid = acc.id , Email = 'test@email.com');
            insert objCon;
            Contact objCon1 = new Contact(LastName = 'ConName1' ,Accountid = acc1.id , Email = 'test1@email.com');
            insert objCon1;
            
            List<Party__c> lstParty = new List<Party__c>();
            
            Party__c objParty = new Party__c();
            objParty.CRM_Name__c = 'N';
            objParty.CRM_Email__c  = 'N@gmail.com';
            objParty.CRM_Phone__c  = '1';
            objParty.CRM_Type__c  = 'Co Borrower';
            objParty.CRM_Company__c  = 'C';
            objParty.Lead__c  = objLead.id;
            objParty.CRM_Create_New_Business_Account__c = True;
            objParty.CRM_Create_New_Contact__c  = True;
            objParty.CRM_Create_New_Person_Account__c = false;
            
            lstParty.add(objParty);
            
            Party__c objParty1 = new Party__c();
            objParty1.CRM_Name__c = 'N1';
            objParty1.CRM_Email__c  = 'N1@gmail.com';
            objParty1.CRM_Phone__c  = '2';
            objParty1.CRM_Type__c  = 'Co Borrower';
            objParty1.CRM_Company__c  = 'C1';
            objParty1.Lead__c  = objLead.id;
            objParty1.CRM_Create_New_Business_Account__c = false;
            objParty1.CRM_Create_New_Contact__c  = true;
            objParty1.CRM_Existing_Account__c = acc.id;
            lstParty.add(objParty1);
            
            Party__c objParty2 = new Party__c();
            objParty2.CRM_Name__c = 'N2';
            objParty2.CRM_Email__c  = 'N2@gmail.com';
            objParty2.CRM_Phone__c  = '3';
            objParty2.CRM_Type__c  = 'Co Borrower';
            objParty2.CRM_Company__c  = 'C2';
            objParty2.Lead__c  = objLead.id;
            objParty2.CRM_Create_New_Business_Account__c = true;
            objParty2.CRM_Create_New_Contact__c  = false;
            objParty2.CRM_Existing_Contact__c = objCon.id;
            
            lstParty.add(objParty2);
        
            Party__c objParty4 = new Party__c();
            objParty4.CRM_Name__c = 'N4';
            objParty4.CRM_Email__c  = 'N4@gmail.com';
            objParty4.CRM_Phone__c  = '14';
            objParty4.CRM_Type__c  = 'Co Borrower';
            objParty4.Lead__c  = objLead.id;
            objParty4.CRM_Create_New_Person_Account__c = true;
            
            lstParty.add(objParty4);
            
            Party__c objParty5 = new Party__c();
            objParty5.CRM_Name__c = 'N5';
            objParty5.CRM_Email__c  = 'N14@gmail.com';
            objParty5.CRM_Phone__c  = '145';
            objParty5.CRM_Type__c  = 'Co Borrower';
            objParty5.Lead__c  = objLead.id;
            objParty5.CRM_Create_New_Person_Account__c = false;
            objParty5.CRM_Existing_Account__c = perAcc.id;
            
            lstParty.add(objParty5);
            
            Party__c objParty6 = new Party__c();
            objParty6.CRM_Name__c = 'N6';
            objParty6.CRM_Email__c  = 'N6@gmail.com';
            objParty6.CRM_Phone__c  = '16';
            objParty6.CRM_Type__c  = 'Guarantor';
            objParty6.Lead__c  = objLead.id;
            objParty6.CRM_Create_New_Business_Account__c = true;
            objParty6.CRM_Create_New_Contact__c  = true;
            
            lstParty.add(objParty6);
            
            Party__c objParty7 = new Party__c();
            objParty7.CRM_Name__c = 'N7';
            objParty7.CRM_Email__c  = 'N7@gmail.com';
            objParty7.CRM_Phone__c  = '17';
            objParty7.CRM_Type__c  = 'Guarantor';
            objParty7.Lead__c  = objLead.id;
            objParty7.CRM_Create_New_Business_Account__c = true;
            objParty7.CRM_Create_New_Contact__c  = false;
            objParty7.CRM_Existing_Contact__c = objCon1.id; 
            
            lstParty.add(objParty7); 
           
            Party__c objParty9 = new Party__c();
            objParty9.CRM_Name__c = 'N';
            objParty9.CRM_Email__c  = 'N@gmail.com';
            objParty9.CRM_Phone__c  = '1';
            objParty9.CRM_Type__c  = 'Guarantor';
            objParty9.Lead__c  = objLead.id;
            objParty9.CRM_Create_New_Business_Account__c = false;
            objParty9.CRM_Create_New_Contact__c  = true;
            objParty9.CRM_Existing_Account__c = acc.id;
            
            lstParty.add(objParty9);
            
            insert lstParty;
            
             Test.StartTest();
               
                
                Database.LeadConvert lc = new database.LeadConvert();
                lc.setLeadId(objLead.id);
                lc.setDoNotCreateOpportunity(false);
                //LeadStatus convertStatus = [Select Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
                lc.setConvertedStatus('Qualified');
                
                Database.LeadConvertResult lcr = Database.convertLead(lc);
                
                Database.LeadConvert lc1 = new database.LeadConvert();
                lc1.setLeadId(objLead1.id);
                lc1.setDoNotCreateOpportunity(false);
                lc1.setConvertedStatus('Qualified');
                
            	Map<id,id> mapleadIdToOppId = new Map<id,id>();
                Database.LeadConvertResult lcr1 = Database.convertLead(lc1);
            test.stopTest();
            
            	Opportunity opp = [Select Id from Opportunity Limit 1];
            	mapleadIdToOppId.put(objLead.id,opp.Id);
                CRMTriggerOnLeadHandler objLeadController = new CRMTriggerOnLeadHandler();
            	objLeadController.mapleadIdToOppId = mapleadIdToOppId;
            	objLeadController.createExAccountAndExContact(new List<Party__c>{objParty9});
			  	List<CRM_Related_Party__c> lstRelatedParty = [Select Id,CRM_Related_Opportunity__c From CRM_Related_Party__c Limit 1];     
            	system.assertEquals(lstRelatedParty[0].CRM_Related_Opportunity__c,opp.Id,'Success test');
                                                   
        }
    
    }


}