objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Stacktrace__c</fullName>
        <label>Error_Stacktrace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Line__c</fullName>
        <label>Line</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{DDMMYY}-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/pepErrorLog.cls
public without sharing class pepErrorLog {
 public static void LogErrors(Error[] Errors)
     {
      List<Error_Log__c> lstErrors = new List<Error_Log__c>();

       for(Error objError: Errors)
          {
            Error_Log__c objLog = new Error_Log__c();
            objLog.Object_Name__c=objError.object_Name;
           
            if(objError.objException!=null)
            {
                objLog.Error_Message__c=objError.objException.getMessage(); objLog.Error_Stacktrace__c=objError.objException.getStackTraceString();
                objLog.Type__c=objError.objException.getTypeName(); objLog.Line__c=objError.objException.getLineNumber();
            }
            
            lstErrors.add(objLog);
          }
        
         if(lstErrors!=null && lstErrors.size()>0)
         {
            insert lstErrors;
         }
       } 
  public class Error
    {
        public String object_Name;
        public Exception objException;
        public Error(){}
        public Error(String object_Name,Exception objException)
        {
        this.object_Name=object_Name;
        this.objException=objException;
        }
        
    }       
}