objects/Expense_and_Debt__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Expenses and Debts</relationshipLabel>
        <relationshipName>Expenses_and_Debts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Remaining_as_Debt__c</fullName>
        <description>This will be needed to be provided if revolving credit and debt consolidation is true</description>
        <label>Debt Amount Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consolidate_As_A_Debt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Consolidate As Debt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mortgage Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Household Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment and Services Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle and Transport Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Living Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food and Living Expense</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Expense_Debt__c</fullName>
        <label>Type of Expense/Debt</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Credit card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Council Rates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strata</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electricity Rates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Rates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gas Rates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gambling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Total of all other monthly expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent or mortgage repayments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utilities, rates and services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &amp; contents insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other living expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other sevices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motor vehicle expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private health insurance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Expense and Debt</label>
    <nameField>
        <displayFormat>END-{0000000000}</displayFormat>
        <label>Expense and Debts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses and Debts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/pages_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Page_Label__c</fullName>
        <label>Page_Label</label>
        <type>TextArea</type>
    </fields>
    <label>pages_config</label>
</CustomObject>

objects/pepCmsAnswer__c.object
<CustomObject>
    <fields>
        <fullName>pepCmsQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Question</label>
        <referenceTo>pepCmsQuestion__c</referenceTo>
        <relationshipLabel>Answer</relationshipLabel>
        <relationshipName>pepCmsAnswer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepSequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CMS Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsQuestion__c.object
<CustomObject>
    <fields>
        <fullName>Is_Date_to_Birth__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Date to Birth</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepCMSAnswer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Answer</label>
        <referenceTo>pepCmsAnswer__c</referenceTo>
        <relationshipLabel>Question</relationshipLabel>
        <relationshipName>pepCmsQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepDisplayDollar__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display $</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepDisplayPercent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display %</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepFieldApiName__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepGenericErrorMessage__c</fullName>
        <label>Generic Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>pepGoogleApi__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Google Api</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepIsRequired__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepKeyPressNumbersOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Key Press Numbers Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepLabelAfterQuestion__c</fullName>
        <label>Label (After Question)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepLabelPriorQuestion__c</fullName>
        <description>The text that will be displayed just before the question is rendered.</description>
        <label>Label (Prior Question)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepNumbersOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Numbers Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>pepCmsQuestion__c</referenceTo>
        <relationshipName>CmsQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepRecordSequence__c</fullName>
        <label>Record Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pepRelatedCSS__c</fullName>
        <label>Related CSS</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepSObjectApiName__c</fullName>
        <label>SObject API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepSection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Section</label>
        <referenceTo>pepCmsSection__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>pepQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepSequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pepSubType__c</fullName>
        <label>Sub Type</label>
        <picklist>
            <controllingField>pepType__c</controllingField>
            <picklistValues>
                <fullName>Yes / No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+ / -</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HomePhone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pepValidEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Email</label>
        <type>Checkbox</type>
    </fields>
    <label>CMS Question</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsSection__c.object
<CustomObject>
    <fields>
        <fullName>Page_Name__c</fullName>
        <formula>TEXT(pepPage__r.pepPageName__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Page Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepHeader__c</fullName>
        <label>Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepSectionBodyRich__c</fullName>
        <label>Section Body (Rich)</label>
        <length>130000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>pepSectionUniqueName__c</fullName>
        <label>Section Unique Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>pepSequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Running Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>CMS Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/pepDebtConsolidationController.cls
// created by Bhawna - completed  - 7-APR-2016
// last changes-- 
// This class build business logic for Debt consolidation page
public class pepDebtConsolidationController {

genesis__Applications__c objApplication;
public list<genesis__Applications__c> lstApplication;
public static final string EXPENSE_TYPE= 'Debt';
public static final string EXPENSE_SUB_CREDIT = 'Credit card';
public string strCreditCardAmount{get;set;}
public list<expenseWrapper> lstExpenseWrapper{get;set;}
public boolean IsRequest{get;set;}
public boolean IsAccept{get;set;}
public list<QuesAnsWrap> lstQuesAnsWrap;
map<Id,string> mpFinInstIdToString;
public string strCCDesc{get;set;}
list<pepBank_API_Details__c> lstBankAPIDetails;
list<selectOption> lstBankName{get; set;} 
public decimal dcmlCreditCardAmountRemaining{get;set;}
public List<pepCmsQuestion__c> lstQuestions;
public Boolean successSaveForLater{get;set;}
public list<Expense_and_Debt__c> debtList;
// constructor
public pepDebtConsolidationController()
{
    objApplication =  new genesis__Applications__c(); 
    lstApplication = new list<genesis__Applications__c>();
    lstExpenseWrapper =  new list<expenseWrapper>();
    lstQuesAnsWrap = new list<QuesAnsWrap>();
    lstQuestions = new List<pepCmsQuestion__c>();
    mpFinInstIdToString =  new map<Id,string>();
    lstBankAPIDetails =  new list<pepBank_API_Details__c>();
    lstBankName =  new list<selectOption>();
    debtList = new list<Expense_and_Debt__c> ();
    IsRequest = false;
    IsAccept =  false;
    getCookieData();
    fetchApplications();
    fetchApplication();
    getBankAPIDetails();
    fetchExpenses();
}

//fetch cookies
public void getCookieData()
{
        Cookie cookieApplicationId = ApexPages.currentPage().getCookies().get('ApplicationId');  
        
        if(cookieApplicationId !=null && cookieApplicationId.getValue() !=null && cookieApplicationId.getValue() !='')
        {                           
               objApplication.Id = pepEncryptDecryptData.DecryptData(String.valueof(cookieApplicationId.getValue()));
        }        
}

public void fetchApplication()
{
    String[] lstTypes = new String[]{'genesis__Applications__c', 'Expense_and_Debt__c'};    
    String FieldSetName='pepGeneral';
    if(objApplication.Id !=null)
    {
        lstApplication=pepUtilityClass.fetchApplicationAndChild(lstTypes,FieldSetName,null,objApplication.Id,null);
        system.debug('lstApplication:: '+lstApplication);
        system.debug('Bhawna-Debt-Purpose:: '+lstApplication[0].genesis__CL_Purpose__c); 
      /*  if(lstApplication != null && lstApplication.size() >0)
           {        
               objApplication = lstApplication[0];
                   
           }   */
    }
}
      public void fetchApplications()
        {
            //hardcode application Id
            System.debug('method called');
            Map<string,string> childobjects = new Map<string,string>();       
            String[] lstTypes = new String[]{''};
            if(objApplication != null && objApplication.Id !=null)
            {
                
               List<genesis__Applications__c>  lstApplication  =pepInvokeCLMethodHelper.fetchApplications(null ,objApplication.Id,null,null,childobjects );
               System.debug('lstApplication  *********'+lstApplication);
                if(lstApplication != null && lstApplication.size() >0)
                {        
                    objApplication = lstApplication[0];
                   
                }
                
                
            }
        }

private void fetchExpenses()
{
    lstQuestions = fetchQuestions();
    system.debug('lstQuesAnsWrap:: '+lstQuesAnsWrap);
    string strExpenseHeader='';
    string strCCHeader='';
    list<pepCmsSection__c> lstSection = [select id, pepHeader__c,pepSectionBodyRich__c,pepSectionUniqueName__c from pepCmsSection__c where Page_Name__c= 'Debt Consolidation'];
    if(lstSection!=null && lstSection.size()>0)
    {
        for(pepCmsSection__c objSection :lstSection)
        {
            if(objSection.pepSectionUniqueName__c == 'DebtConsolidationAllExpenses')
                strExpenseHeader = objSection.pepHeader__c;
            
            if(objSection.pepSectionUniqueName__c == 'DebtConsolidationCreditCards')
                strCCHeader = objSection.pepHeader__c;
        }
    }
    
    if(lstApplication!=null && lstApplication.size()>0 && lstApplication[0].Purpose_Name__c !=null && lstApplication[0].Purpose_Name__c!='')
    {
    
        system.debug('bhawna-Expenses-size-'+lstApplication[0].Expenses_and_Debts__r.size());
    
        //fetch Expenses
        if(lstApplication[0].Expenses_and_Debts__r != null && lstApplication[0].Expenses_and_Debts__r.size() > 0)
        {   
           dcmlCreditCardAmountRemaining = 0; 
           integer intCount=0; 
           integer intCountCC = 0;                     
           for(Expense_and_Debt__c objExpense : lstApplication[0].Expenses_and_Debts__r)
           {
               system.debug('bhanwa-expense type:: '+ objExpense.Type__c.toLowerCase() + ' -- '+ EXPENSE_TYPE.toLowerCase());
                if(objExpense.Type__c.toLowerCase()  == EXPENSE_TYPE.toLowerCase() && objExpense.Consolidate_As_A_Debt__c == true)// if expense if of type debt
                {
                    system.debug('objExpense.Amount_Remaining_as_Debt__c:: '+objExpense.Amount_Remaining_as_Debt__c);
                    system.debug('bhanwa-expense type:: '+ objExpense.Type_of_Expense_Debt__c.toLowerCase() + ' -- '+ EXPENSE_SUB_CREDIT.toLowerCase());
                    // if expense type is credit card
                    if(objExpense.Type_of_Expense_Debt__c.toLowerCase() == EXPENSE_SUB_CREDIT.toLowerCase())// if expense sub type is credit card
                    {
                        dcmlCreditCardAmountRemaining+= objExpense.Amount_Remaining_as_Debt__c;
                        ++intCountCC;
                    }                    
                    // if expense type is not credit card
                    else
                    {
                       //debtList
                        expenseWrapper objWrap =  new expenseWrapper();
                        objWrap.objExpense = objExpense;
                       // objWrap.strExpenseType = objExpense.Type_of_Expense_Debt__c;
                        Decimal dcml= objExpense.Amount_Remaining_as_Debt__c.setScale(2);
                        string strFormat=  dcml.format();                         
                        objWrap.strAmountRemaining = '$'+strFormat; 
                        //objWrap.strCount = string.valueOf(++intCount);
                        objWrap.strSectionHeader = strExpenseHeader.replace('{DebtDescription}', objExpense.Type_of_Expense_Debt__c );
                        objWrap.strSectionHeader = objWrap.strSectionHeader.replace('{DebtType}',string.valueOf(++intCount));
                        
                        list<QuesAnsWrap> lstQuesAnsWrap1 = new list<QuesAnsWrap>();
                        for(pepCmsQuestion__c objTempQ :lstQuestions )
                        {
                            QuesAnsWrap objChildWrap =  new QuesAnsWrap();
                            objChildWrap.objQues = objTempQ ;   
                            
                            // get it from Financial institution
                            objChildWrap.lstOptions.add(new SelectOption('null','choose one'));
                            objChildWrap.lstOptions.addAll(lstBankName);                        
                            
                            
                            lstQuesAnsWrap1.add(objChildWrap);     
                        }                                     
                        objWrap.lstQAWrap = lstQuesAnsWrap1 ;
                        lstExpenseWrapper.add(objWrap);
                    }
                    
                    
                }                 
           }
               
           // format credit crad amount remaining                
           Decimal rounded= dcmlCreditCardAmountRemaining.setScale(2);
           string strFormat=  rounded.format();
           strCreditCardAmount =  '$'+strFormat; 
           strCCDesc = strCCHeader.replace('{DebtDescription}',  string.valueOf(intCountCC)+ ' x' );    
        }  
            
       
    }
}

// wrapper class for expenses other than credit card
public class expenseWrapper
{
    public Expense_and_Debt__c objExpense{get;set;}
    //public string strCount{get;set;}
    //public string strExpenseType{get;set;}
    public list<QuesAnsWrap> lstQAWrap{get;set;}
    public string strAmountRemaining{get;set;}
    public integer intAccountNumber{get;set;}
    public string strFinancialInstitution{get;set;}
    public string strBSB{get;set;}
    public string strSectionHeader{get;set;}
   
    
    public expenseWrapper()
    {
        lstQAWrap=  new list<QuesAnsWrap>(); 
        objExpense =  new Expense_and_Debt__c();
    }
}

public class QuesAnsWrap
{
    public pepCmsQuestion__c objQues{get;set;}
    public string objInputValue{get;set;}
    public boolean boolBSCallBWebserviceError{get;set;}
    public list<SelectOption> lstOptions {get; set;}
    
    public QuesAnsWrap()
    {
        objQues =  new pepCmsQuestion__c();
        boolBSCallBWebserviceError = false;
        lstOptions = new list<SelectOption>();
    }
}

public pageReference saveData()
{    
     system.debug('-IsAccept::'+IsAccept + ' -IsRequest- '+ IsRequest);
    debtList = new list<Expense_and_Debt__c> ();
    system.debug('Bhawna-lstExpenseWrapper::'+lstExpenseWrapper);
    List<WrapperBankAccount> listacc;
    if(lstExpenseWrapper!=null && lstExpenseWrapper.size()>0)
    {
        listacc = new List<WrapperBankAccount>();
        boolean boolIsFailure = false;
        
        for(expenseWrapper objParentWrap: lstExpenseWrapper)
        { 
                   
            if(objParentWrap.lstQAWrap !=null && objParentWrap.lstQAWrap.size()>0)
            {
                WrapperBankAccount  bankAcc = new WrapperBankAccount();
                string strAccNo;
                string strAccName;
                string strBSB;
                string strFI;
                string strCR;
                System.debug('objParentWrap.lstQAWrap******'+objParentWrap.lstQAWrap);
               
                for(QuesAnsWrap objChildWrap: objParentWrap.lstQAWrap)
                {
                    system.debug('Question:: '+objChildWrap.objQues.pepLabelPriorQuestion__c );
                    system.debug('Answer:: '+objChildWrap.objInputValue);
                    system.debug('AccountId:'+lstApplication[0].genesis__Account__c);
                    
                    if(objChildWrap.objQues.pepLabelPriorQuestion__c == 'Account Name')
                        strAccName = objChildWrap.objInputValue;
                    if(objChildWrap.objQues.pepLabelPriorQuestion__c == 'Account Number')
                        strAccNo = objChildWrap.objInputValue;
                    if(objChildWrap.objQues.pepLabelPriorQuestion__c == 'BSB')
                    {
                        strBSB= objChildWrap.objInputValue;
                        //----- Code Added by Amit kumar 09/08/2016 -----------------------
                        //------ This code validates BSB through web service---------------- 
                        if(strBSB != null && strBSB !='' && strBSB.length() ==6)
                        {
                            String strBSBfromResponse = strbsb.substring(0, 3) + '-' + strbsb.substring(3, strbsb.length());
                            String strBsbValidationResponse = pepUtilityClass.callBSBvalidationWebService(strBSB);
                            System.debug('strBsbValidationResponse*****'+strBsbValidationResponse);
                            pepBSBWebserviceResponse objResponse = pepUtilityClass.readBSBXMlResponse(strBsbValidationResponse);
                            if(objResponse.BSB == null || (objResponse.BSB != null && objResponse.BSB.trim() != strBSBfromResponse.trim()))
                            {
                            
                                System.debug('strBsbValidationResponse*****'+strBsbValidationResponse);
                                objChildWrap.boolBSCallBWebserviceError = true;
                                boolIsFailure = true;
                            
                            }
                            else
                            {
                                objChildWrap.boolBSCallBWebserviceError = false;
                                strFI = objResponse.FinancialInstitutionCode;
                            }
                            
                        }
                    }
                    if(objChildWrap.objQues.pepLabelPriorQuestion__c == 'Creditor Reference')
                    {
                        strCR= objChildWrap.objInputValue; 
                        
                    }
                    if(objChildWrap.objQues.pepLabelPriorQuestion__c == 'Financial Institution' && objChildWrap.objQues.pepType__c == 'Picklist')
                    {
                        strFI = objChildWrap.objInputValue; 
                        //system.debug('FT::'+mpFinInstIdToString.get(objChildWrap.objInputValue));
                        //strFI = mpFinInstIdToString.get(objChildWrap.objInputValue);
                    }    
                   
                    // bankAcc.Set(accountId,‘Debt Consolidation', accountNo, bsbNo, financialIns, expense Id);
                    System.debug('strAccNo********'+strAccNo);
                    
                    
                }
                
               
                if(boolIsFailure ==false)
                {
                   
                
                        bankAcc.Set(lstApplication[0].genesis__Account__c,'Debt Consolidation', strAccNo , strBSB, strFI , objParentWrap.objExpense.Id, strAccName,  null, false, lstApplication[0].Id,true,true);
                        Expense_and_Debt__c debt =new Expense_and_Debt__c(id=objParentWrap.objExpense.id,Reference__c=strCR); 
                        debtList.add(debt);
                   
                }
                 Listacc.add(bankAcc);
            }
           
        }
         if(boolIsFailure ==true)
         {
             return null;
         }
    }
    
     BankApi bankapi = new BankApi();
     boolean isSuccessful = true;
     System.debug('ListAcc******'+ListAcc);
   //  System.debug('ListAcc******'+ListAcc.size());
     if(Listacc!=null && Listacc.size()>0)
     {   
         list<BankApi.Response> lstresp = new list<BankApi.Response>();
         if(test.isRunningTest()==false)
         lstresp= BankApi.addNewBanks(Listacc);
        // system.debug('Response:: '+lstresp);
         if(lstresp!=null && lstresp.size()>0)
         {
             Map<String,SObject> relatedObjects = new Map<String,SObject>();
             Map<String,List<SObject>> childObjects = new Map<String,List<SObject>>(); 
             system.debug('IsAccept::'+IsAccept + ' -IsRequest- '+ IsRequest);
             system.debug('lstApplication[0]'+lstApplication[0].Id);
             lstApplication[0].Is_Accept__c = IsAccept;
             lstApplication[0].Is_Request__c= IsRequest;                   
             pepInvokeCLMethodHelper.updateApplication(lstApplication[0],relatedObjects ,childObjects);
             update debtList;
             //for(BankApi.Response objResp:lstresp)
             //{
             //    if(objResp.status !='Successful')
             //        isSuccessful = false;
             //}
         }
         
         //system.debug('Status::'+resp.status);
     }
    // if(isSuccessful == true)
     //{
         system.debug('lstApplication[0].Id:: '+lstApplication[0].Id);
         Cookie myCookies=new Cookie('ApplicationId','',null,-1,false);
         myCookies = new Cookie('ApplicationId',pepEncryptDecryptData.EncryptData(String.valueof(lstApplication[0].Id)),null,-1,false);
         system.debug('cookieApplicationId2--'+myCookies);
         pepUtilityClass.SaveContinueStatus(objApplication,'pepFinaliseRepayment') ;
         String redircetPageName= pages_config__c.getinstance('pepfinaliserepayment').Page_Label__c;
         pageReference ref = new pageReference('/'+redircetPageName);
         ref.setCookies(new Cookie[]{myCookies }); 
         ref.setRedirect(true);
         return ref;
     //}else
     //{
     //    return null;
     //}
}

private List<pepCmsQuestion__c> fetchQuestions()
{  
    List<pepCmsQuestion__c> lstQuestions = [SELECT Id,Is_Date_to_Birth__c, pepSection__c,pepSection__r.Name , pepSection__r.pepSectionUniqueName__c, CreatedById, CreatedDate, IsDeleted, pepDisplayDollar__c, pepDisplayPercent__c, pepFieldApiName__c, 
                                                pepRecordSequence__c, pepIsRequired__c,pepGenericErrorMessage__c , pepKeyPressNumbersOnly__c, pepLabelAfterQuestion__c, pepLabelPriorQuestion__c, LastModifiedById, LastModifiedDate, 
                                                pepNumbersOnly__c, OwnerId, pepQuestion__c, Name, pepSObjectApiName__c, pepSequence__c, pepType__c, pepValidEmail__c, pepCMSAnswer__c,pepRelatedCSS__c,pepSubType__c, 
                                                pepGoogleApi__c,
                                                
                                                (SELECT Name,pepCmsQuestion__c,pepActualValue__c,pepDisplayText__c,pepSequence__c,Id 
                                                FROM pepCmsAnswer__r order by pepSequence__c ASC)                                         
                                             
                                                FROM pepCmsQuestion__c
                                                WHERE pepSection__r.pepSectionUniqueName__c ='DebtConsolidationAllExpenses'
                                                and pepSection__r.Page_Name__c= 'Debt Consolidation'
                                                ORDER BY pepSequence__c ASC];
    system.debug('lstQuestions :: '+lstQuestions );
    list<SelectOption> lstSO =  new list<SelectOption>();
    //list<pepCmsQuestion__c> lstQues=  new list<pepCmsQuestion__c>();
    for(pepCmsQuestion__c objTempQ :lstQuestions )
    {
       QuesAnsWrap objChildWrap =  new QuesAnsWrap();
       objChildWrap.objQues = objTempQ ;   
       
       // get it from Financial institution
       objChildWrap.lstOptions.add(new SelectOption('null','choose one'));
       objChildWrap.lstOptions.addAll(lstBankName);
       
      /* for(pepCmsAnswer__c A : objTempQ .pepCmsAnswer__r)
       {              
                 if(A.pepDisplayText__c == 'Choose one')
                 {
                     objChildWrap.lstOptions.add(new SelectOption('null', A.pepDisplayText__c));
                 }
                 else
                 {
                     objChildWrap.lstOptions.add(new SelectOption(A.ID, A.pepDisplayText__c));
                     mpFinInstIdToString.put(A.ID,A.pepDisplayText__c);
                 }                   
       }*/
       
       lstQuesAnsWrap.add(objChildWrap);     
    }                                               
    return  lstQuestions;
}

private void getBankAPIDetails()
{
         lstBankAPIDetails = [Select id,pepBank_Name__c from pepBank_API_Details__c limit 50000];
             
         system.debug('lstBankAPIDetails**' +lstBankAPIDetails );
             
         if(lstBankAPIDetails != null && lstBankAPIDetails.size() > 0)
         {
             for(pepBank_API_Details__c  objAPIDetails : lstBankAPIDetails )
             {
                 lstBankName.add(new selectOption(((objAPIDetails.pepBank_Name__c).toLowerCase()),objAPIDetails.pepBank_Name__c));
                 lstBankName.sort();
                // mpFinInstIdToString.put(A.ID,A.pepDisplayText__c);
             }
         }
}

//  This method is used to save the page name of current page in navigation status of application and sent notification(retrieval code)
  //  through SMS and Email to related account of respected application.

     public void saveForLater()
     {
            successSaveForLater=false;
           if(objApplication!=null && objApplication.id!=null)  
             {
                         genesis__Applications__c objApplicationReturn = new  genesis__Applications__c ();
                         objApplicationReturn = pepUtilityClass.SaveForLater(objApplication,'pepDebtConsolidation') ; 
             
                        if(objApplicationReturn!=null && objApplicationReturn.id!=null)
                         {  
                                  successSaveForLater = true;
                                  system.debug('aplicationIs'+objApplicationReturn);
                                  
                         }     
               }                                  
      
     }

Public Pagereference checkcookie(){
Pagereference pr=Peputilityclass.checkCookieAndRedirect();
return pr;
}

}