objects/Expense_and_Debt__c.object
<CustomObject>
    <label>Expense and Debt</label>
    <nameField>
        <displayFormat>END-{0000000000}</displayFormat>
        <label>Expense and Debts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses and Debts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/pages_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Page_Label__c</fullName>
        <label>Page_Label</label>
        <type>TextArea</type>
    </fields>
    <label>pages_config</label>
</CustomObject>

objects/pepCmsAnswer__c.object
<CustomObject>
    <fields>
        <fullName>pepActualValue__c</fullName>
        <label>Actual Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepCmsQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Question</label>
        <referenceTo>pepCmsQuestion__c</referenceTo>
        <relationshipLabel>Answer</relationshipLabel>
        <relationshipName>pepCmsAnswer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepDisplayText__c</fullName>
        <label>Display Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepSequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CMS Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsPage__c.object
<CustomObject>
    <fields>
        <fullName>pepPageName__c</fullName>
        <label>Page Name</label>
        <picklist>
            <picklistValues>
                <fullName>Landing Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apply Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App Login Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save &amp; Retrieve Functionality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Living Expenses Calculator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Header</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Footer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability Negative2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(verifyid)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup (Credit-Policy)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalise Repayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(FinancialDoc)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Consolidation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(Manual Upload)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Congratulations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(upload another Image)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SideBarTemplate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup (Bank-Detail)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsQuestion__c.object
<CustomObject>
    <fields>
        <fullName>pepCMSAnswer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Answer</label>
        <referenceTo>pepCmsAnswer__c</referenceTo>
        <relationshipLabel>Question</relationshipLabel>
        <relationshipName>pepCmsQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepDisplayDollar__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display $</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepDisplayPercent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display %</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepFieldApiName__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepGenericErrorMessage__c</fullName>
        <label>Generic Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>pepIsRequired__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepKeyPressNumbersOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Key Press Numbers Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepLabelAfterQuestion__c</fullName>
        <label>Label (After Question)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepLabelPriorQuestion__c</fullName>
        <description>The text that will be displayed just before the question is rendered.</description>
        <label>Label (Prior Question)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepNumbersOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Numbers Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepPage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Page</label>
        <referenceTo>pepCmsPage__c</referenceTo>
        <relationshipLabel>Question</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>pepCmsQuestion__c</referenceTo>
        <relationshipName>CmsQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepRecordSequence__c</fullName>
        <label>Record Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pepRelatedCSS__c</fullName>
        <label>Related CSS</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepSObjectApiName__c</fullName>
        <label>SObject API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepSection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Section</label>
        <referenceTo>pepCmsSection__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>pepQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepSequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pepSubType__c</fullName>
        <label>Sub Type</label>
        <picklist>
            <controllingField>pepType__c</controllingField>
            <picklistValues>
                <fullName>Yes / No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+ / -</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HomePhone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pepValidEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pepis_Consolidated_Debt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Consolidated Debt</label>
        <type>Checkbox</type>
    </fields>
    <label>CMS Question</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsSection__c.object
<CustomObject>
    <fields>
        <fullName>pepHeader__c</fullName>
        <label>Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepPage__c</fullName>
        <label>Page</label>
        <referenceTo>pepCmsPage__c</referenceTo>
        <relationshipName>pepSection</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>pepSectionUniqueName__c</fullName>
        <label>Section Unique Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>pepSequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Running Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>CMS Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/pepDefaultCompany__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>pepBusinessAccount__c</fullName>
        <label>BusinessAccount</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepDefault_Company_Id__c</fullName>
        <label>Default Company Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>pepDefaultCompany</label>
</CustomObject>

classes/PepApplyNowController.cls
// ---------------------------------------------------------------------------------------------------------
// This Controller is used to get old info of customer and to show terms and condition. 
//Code Refactoring done by Varun on August 26,2017 
// ---------------------------------------------------------------------------------------------------------

public  class PepApplyNowController
{         
    public Boolean strSelectedValue1;       
    public String strSelectedValue   { get; set;}      
    public List<wrapperSection> lstWrapperSection{get;set;}
    public Integer sectionNumber;
    @TestVisible private List<selectOption> lstclPurposeSelectOption; 
    @TestVisible public string strUrl;
    public boolean isError{get;set;}  
    public genesis__Applications__c objApplication{get;set;} 
    public pepCmsModelContainer  modelConInstance{get;set;}
    public pepCmsModelContainer_new  modelConInstance_New{get;set;}
    public String purposeName {get;set;}
    Public Pagereference  objNextPage; 
    public String sectionName {get;set;}
    public Integer intCurrentPageNumber;
    public Integer intPreviousPageNumber{get;set;}      
    public Id idDefaultCompany;
    public id idBusinessAccount;
    @TestVisible private String  returnValue;
    @TestVisible private String referralCode;        
    @TestVisible private Map<Id,String> mapOfPurposeIdToPurposeName;
    @TestVisible List<genesis__Rate_Card_Setup_Detail__c> lstRateCardSetupDetail;
    public String strMinLoanAmount{get;set;}
    public String strMaxLoanAmount{get;set;}       
    public String page_Name{get;set;}
    public String page_Label{get;set;}
    
    //Added by IJ These parameters would be fetched from the URL and saved against the application for staff loans and other purposes
    public string p1;
    public string p2;
    public string p3;
    public string p4;
    
    //   This Constructor is used to get the parameters thorough cookies.
    public pepApplyNowController()
    {
        strurl = ApexPages.currentPage().getUrl(); 
        if(strurl.contains('?'))
        {
            strurl = strurl.substringBefore('?');
        }
        
        strurl = strurl.split('apex/')[1]; 
        page_Name=ApexPages.currentPage().getUrl();
        page_Name=page_Name.substring(page_Name.contains('/apex')?6:1,page_Name.contains('?')?page_Name.indexof('?'):page_Name.length());
        Page_Label=pages_config__c.getValues(page_Name.toLowerCase()).Page_Label__c;
        
        
        objApplication = new  genesis__Applications__c(); 
        
        //added by : Sushant Kumar, purpose : to include apllication source information on creation of new application
        objApplication = pepUtilityClass.fillApplicationSourceInfo(objApplication);                                                                                                           
        
        MapOfPurposeIdToPurposeName = new Map<id,String>();                      
        referralCode= apexpages.currentpage().getparameters().get('Ref');
        modelConInstance_new = new pepCmsModelContainer_new();
        if(ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP')!=null)
        {
            ReturnValue = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP'); 
        }    
        
        lstRateCardSetupDetail = new List<genesis__Rate_Card_Setup_Detail__c>();
        modelConInstance = new pepCmsModelContainer();         
        if( ApexPages.currentPage().getParameters().get('redirectFromPageNo') != null 
           &&  ApexPages.currentPage().getParameters().get('redirectFromPageNo') !='')
        {
            intPreviousPageNumber = Integer.valueOf(ApexPages.currentPage().getParameters().get('redirectFromPageNo'));     
            
        }
        
        intCurrentPageNumber =  1;              
        sectionNumber=1;                           
        lstWrapperSection = new List<wrapperSection>();
        loadClPurpose(); 
        if(strurl == 'pepApplyNow')
        { 
            //entered by varun to load the Application through cookies.
            getcookiedata();
            fetchApplication();
            loadCMSContentForApplyPage();
            p1 = ApexPages.currentPage().getParameters().get('p1');
            p2 = ApexPages.currentPage().getParameters().get('p2');         
            p3 = ApexPages.currentPage().getParameters().get('p3');
            p4 = ApexPages.currentPage().getParameters().get('p4');
            
            if(p1 != null)
            {
                if(p1.length()>255)
                {
                    p1 = p1.substring(0,255);
                }
                Cookie param1 = new cookie('param1',p1,null,-1,false);
                ApexPages.currentPage().setcookies(new cookie[]{param1});
            }
            else
            {
                p1 = '';
                
            }
            
            if(p2 != null)
            {
                if(p2.length()>255)
                {
                    p2 = p2.substring(0,255);
                }
                Cookie param2 = new cookie('param2',p2,null,-1,false);
                ApexPages.currentPage().setcookies(new cookie[]{param2});
            }
            
            else
            {
                p2 = '';
                
            }            
            
            if(p3 != null)
            {
                if(p3.length()>255)
                {
                    p3 = p3.substring(0,255);
                }
                Cookie param3 = new cookie('param3',p3,null,-1,false);
                ApexPages.currentPage().setcookies(new cookie[]{param3});
            }
            else
            {
                p3 = '';
                
            }            
            
            if(p4 != null)
            {
                if(p4.length()>255)
                {
                    p4 = p4.substring(0,255);
                }
                Cookie param4 = new cookie('param4',p4,null,-1,false);
                ApexPages.currentPage().setcookies(new cookie[]{param4});
            }
            else
            {
                p4 = '';
                
            }            
            
        }
        loadDefaultCompany();     
        
        //Modified By : Sushant Kumar, purpose : this code will put application source information in cookies and these values
        //will be used on loan detail page for putting apllication source information in genesis application in case of application
        //instance is not created already on landing page.
        pepUtilityClass.setParametersInCookie();
    }
    
    // This method is used to get application id from cookies.
    
    public void getCookieData()
    {
        Cookie cookieApplicationId = ApexPages.currentPage().getCookies().get('ApplicationId');  
        if (cookieApplicationId == null)
        {
            //cookieApplicationId = new Cookie('ApplicationId',pepEncryptDecryptData.EncryptData(String.valueof(objApplication.Id)),null,-1,false);
            
        }        
        else if(cookieApplicationId !=null && cookieApplicationId.getValue() !=null && cookieApplicationId.getValue() !='')
        {                           
            objApplication.Id = pepEncryptDecryptData.DecryptData(String.valueof(cookieApplicationId.getValue()));
        }
        
    }
    
    // This method is used to fetch Application
    
    public void fetchApplication()
    {
        
        Map<string,string> childobjects = new Map<string,string>();       
        String[] lstTypes = new String[]{'Expense_and_Debt__c'};
            if(objApplication != null && objApplication.Id !=null)
        {
            
            List<genesis__Applications__c>  lstApplication  =pepInvokeCLMethodHelper.fetchApplications(null ,objApplication.Id,null,null,childobjects );
            if(lstApplication != null && lstApplication.size() >0)
            {        
                objApplication = lstApplication[0];
                //added by : Sushant Kumar, purpose : to include apllication source information on creation of new application
                objApplication = pepUtilityClass.fillApplicationSourceInfo(objApplication);                                                                                                             
            }
            
            
        }
    }
    
    // This method is used to load default company
    
    public void loadDefaultCompany()
    {
        pepDefaultCompany__c  objDefaultCompany = pepDefaultCompany__c.getInstance('Company Id');
        IdDefaultCompany = objDefaultCompany.pepDefault_Company_Id__c;
        idBusinessAccount = objDefaultCompany.pepBusinessAccount__c;
    }
    
    // This method is used to load CL purpose Object.
    
    public void loadClPurpose()
    {
        lstclPurposeSelectOption = new List<selectOption>(); 
        if(strurl == 'peplandingpage')
            lstclPurposeSelectOption.add(new SelectOption('', ''));
        else
            lstclPurposeSelectOption.add(new SelectOption('', 'choose one'));
        for(clcommon__CL_Purpose__c objPurpose : [select id,name from clcommon__CL_Purpose__c order by Serial_No__c asc limit 1000])
        {                
            lstclPurposeSelectOption.add(new SelectOption(objPurpose.Id, objPurpose.Name));
            MapOfPurposeIdToPurposeName.put(objPurpose.Id,objPurpose.name);
        }        
        
    }
    
    // This method is used to load CMS for aaply now page
    
    private void loadCMSContentForApplyPage()
    {
        
        List<pepCmsSection__c> lstlandingPageCmsSection =[select id,pepHeader__c,pepSectionUniqueName__c,
                                                          (select id,pepLabelAfterQuestion__c,
                                                           pepLabelPriorQuestion__c,
                                                           pepSequence__c,pepIsRequired__c,
                                                           pepType__c,pepSubType__c,
                                                           pepGenericErrorMessage__c,
                                                           pepSObjectApiName__c,
                                                           pepFieldApiName__c
                                                           from pepQuestion__r order by pepSequence__c asc) 
                                                          from pepCmsSection__c where pepPage__r.pepPageName__c ='Apply Page'];   
        
        map<id,pepCmsQuestion__c> mapAllQuestions = new map<id,pepCmsQuestion__c>( [SELECT  pepSection__c,pepRecordSequence__c,pepSection__r.Name ,pepis_Consolidated_Debt__c,pepSubType__c ,pepGenericErrorMessage__c,CreatedById, CreatedDate, IsDeleted, pepDisplayDollar__c, pepDisplayPercent__c, pepFieldApiName__c, 
                                                                                    pepIsRequired__c, pepKeyPressNumbersOnly__c, pepLabelAfterQuestion__c, pepLabelPriorQuestion__c, LastModifiedById, LastModifiedDate, 
                                                                                    pepNumbersOnly__c, OwnerId, pepQuestion__c, Name, Id, pepSObjectApiName__c, pepSequence__c, pepType__c, pepValidEmail__c, pepCMSAnswer__c,pepRelatedCSS__c,
                                                                                    (SELECT Name,pepCmsQuestion__c,pepActualValue__c,pepDisplayText__c,pepSequence__c,Id 
                                                                                     FROM pepCmsAnswer__r order by pepSequence__c ASC ), 
                                                                                    (SELECT  pepSection__c,pepRecordSequence__c,pepis_Consolidated_Debt__c,pepSubType__c ,pepGenericErrorMessage__c ,pepDisplayDollar__c,pepDisplayPercent__c,pepFieldApiName__c,pepIsRequired__c,pepKeyPressNumbersOnly__c, pepLabelAfterQuestion__c,
                                                                                     pepLabelPriorQuestion__c,pepNumbersOnly__c,pepQuestion__c,Name,pepSObjectApiName__c,pepSequence__c,pepType__c,Id,pepValidEmail__c,pepCMSAnswer__c ,pepRelatedCSS__c
                                                                                     FROM CmsQuestion__r
                                                                                     ORDER BY pepSequence__c ASC) 
                                                                                    FROM pepCmsQuestion__c where pepPage__r.pepPageName__c ='Apply Page'
                                                                                    ORDER BY pepSequence__c ASC]);
        
        if(lstlandingPageCmsSection != null && lstlandingPageCmsSection.size() > 0)
        { 
            for(pepCmsSection__c objSection :lstlandingPageCmsSection)
            {
                if(objSection.pepQuestion__r != null && objSection.pepQuestion__r.size() > 0)
                {                       
                    wrapperSection objWrapperSection = new wrapperSection();
                    objWrapperSection.objSection = objSection ;
                    objWrapperSection.lstWrapperQuestion = new List<wrapperApplication>();
                    for(pepCmsQuestion__c objQues : objSection.pepQuestion__r)
                    { 
                        wrapperApplication objWrapper = new  wrapperApplication ();
                        objWrapper.objQuestion = objQues;
                        objWrapper.lstExpectedAnswers = new list<wrapperAnswer> ();
                        for(pepCmsAnswer__c objAnswer : mapAllQuestions.get(objQues.Id).pepCmsAnswer__r)
                        {
                            wrapperAnswer objwrapperAnswer = new  wrapperAnswer();
                            objwrapperAnswer.objCmsAnswer = objAnswer;                                       
                            objWrapper.lstExpectedAnswers.add(objwrapperAnswer); 
                        }
                        objWrapperSection.lstWrapperQuestion.add(objWrapper);                                                    
                    }         
                    lstWrapperSection.add(objWrapperSection);
                }
                
            }
            
            
            
        }                                                               
        
    }
    
    // This wrapper is used to capture CMS data
    
    public class wrapperApplication
    {
        public pepCmsQuestion__c objQuestion{get;set;} 
        public List<wrapperAnswer> lstExpectedAnswers {get; set;}//answer of question    
        public List<selectoption> lstSelectOption{get;set;}
        public String strAnswer
        {
            get { return strAnswer; }
            
            set {
                if(objQuestion.pepType__c =='Currency')
                {
                    if(value != null)
                    {
                        strAnswer= value.replace(',','');
                    }
                    else
                    {
                        strAnswer = value;
                    }
                }
                else
                {
                    strAnswer =value;
                }
                
            }
        }
        
    }
    
    public class wrapperSection
    {
        
        public pepCmsSection__c  objSection{get;set;}
        public List<wrapperApplication> lstWrapperQuestion{get;set;}
    }
    
    public class wrapperAnswer
    {
        public pepCmsAnswer__c objCmsAnswer {get; set;}
    }
    
    
    //This method is used to update application from 2nd page.
    
    public PageReference continueApply()
    {
        
        try
        {
            if(objApplication != null)
            {
                if(ReturnValue!=null && ReturnValue!='')
                    objApplication.IP_Address__c =  ReturnValue;        
                
                if(objApplication.id != null || ApexPages.currentPage().getcookies().get('ApplicationId') != null)
                {
                    
                    Map<String,List<SObject>> childObjects = new Map<String,List<SObject>>();
                    Map<String,SObject> relatedObjects = new Map<String,SObject>();
                    String strNavigationStatusPageName = pepUtilityClass.getNavigationPageName('pepIncomePage');
                    Map<string,string> childobjects1 = new Map<string,string>();       
                    
                    if(ApexPages.currentPage().getcookies().get('ApplicationId') != null &&  ApexPages.currentPage().getcookies().get('ApplicationId').getvalue() != null)
                    {
                        
                        List<genesis__Applications__c>  lstApplication  =pepInvokeCLMethodHelper.fetchApplications(null,PepEncryptDecryptData.DecryptData(ApexPages.currentPage().getcookies().get('ApplicationId').getvalue()),null,null,childobjects1);
                        if(lstApplication != null && lstApplication.size() >0)
                        {        
                            objApplication = lstApplication[0];
                            
                        }
                        
                        
                    }
                    
                    //added by : Sushant Kumar, purpose : to include apllication source information on creation of new application
                    objApplication = pepUtilityClass.fillApplicationSourceInfo(objApplication);                                                                                                           
                    objApplication.pepNavigation_Status__c = strNavigationStatusPageName;
                    
                    if(p1 !=null && p1 !='')
                        objApplication.pepP1__c = P1;
                    if(P2 !=null && p2 !='') 
                        objApplication.pepP2__c = P2; 
                    if(P3 !=null && p3 !='')   
                        objApplication.pepP3__c = P3; 
                    if(P4 !=null && p4 !='')    
                        objApplication.pepP4__c = P4;
                    loadApplicationfromcookie();
                    objApplication.Apply_page_policy__c =  true;
                    objApplication.Apply_page_policy_time_stamp__c =  dateTime.Now();                           
                    objApplication =  pepInvokeCLMethodHelper.updateApplication(objApplication,relatedObjects ,childObjects);
                    string redircetPageName= pages_config__c.getinstance('pepincomepage').Page_Label__c;
                    objNextPage =new Pagereference('/'+redircetPageName);
                    objNextPage.setRedirect(true);
                    return objNextPage;
                }
                
                else
                {
                    
                    String strNavigationStatusPageName = pepUtilityClass.getNavigationPageName('pepLoanDetails');
                    objApplication.pepNavigation_Status__c = strNavigationStatusPageName;
                    string redircetPageName= pages_config__c.getinstance('peploandetails').Page_Label__c;
                    objNextPage =new Pagereference('/'+redircetPageName);                      
                    objNextPage.setRedirect(True);
                    return objNextPage;
                }
            }
            
            
            return null;
        }
        catch(Exception ex)
        {
            
            Cookie objCookieEx = new Cookie('ExceptionId',pepEncryptDecryptData.EncryptData(String.valueof(ex.getStackTraceString())),null,-1,false);
            string redircetPageName= pages_config__c.getinstance('pepTechnicalException').Page_Label__c;
            
            Pagereference objNextPage = new Pagereference('/'+redircetPageName); 
            objNextPage.setCookies(new Cookie[]{objCookieEx});
            return  objNextPage;
        }
    }
    
    //This method is used to call the Landing Page on the click of Edit link on second page.   
    
    public PageReference backOnLandingPage() {
        try
        {
            string redircetPageName= pages_config__c.getinstance('peplandingpage').Page_Label__c;
            pageReference objPreviousPage = new Pagereference('/'+redircetPageName); 
            objPreviousPage.setRedirect(false);
            return objPreviousPage ;
        }
        catch(Exception ex)
        {
            Cookie objCookieEx = new Cookie('ExceptionId',pepEncryptDecryptData.EncryptData(String.valueof(ex.getStackTraceString())),null,-1,false);
            string redircetPageName= pages_config__c.getinstance('pepTechnicalException').Page_Label__c;
            
            Pagereference objNextPage = new Pagereference('/'+redircetPageName); 
            objNextPage.setCookies(new Cookie[]{objCookieEx});
            return  objNextPage;
        }
    } 
    
    // This method is used to Redirect the application on the basis of page name
    
    public pageReference retrieveAppCode()
    {
        try{    
            string redircetPageName= pages_config__c.getinstance('pepretrieveapp').Page_Label__c;
            pageReference p1 = new Pagereference('/'+redircetPageName);
            p1.setRedirect(true); 
            return p1;   
        }
        catch(Exception ex)
        {
            Cookie objCookieEx = new Cookie('ExceptionId',pepEncryptDecryptData.EncryptData(String.valueof(ex.getStackTraceString())),null,-1,false);
            string redircetPageName= pages_config__c.getinstance('pepTechnicalException').Page_Label__c;
            
            Pagereference objNextPage = new Pagereference('/'+redircetPageName); 
            objNextPage.setCookies(new Cookie[]{objCookieEx});
            return  objNextPage;
        }
    }
    
    // This method is used to save the value for existing customer  
    
    public void applyNowQuery()
    {
        String strSelected = ApexPages.currentPage().getParameters().get('text');
        String rowNo = ApexPages.currentPage().getParameters().get('rowIndex');
        
        if(rowNo != null)
        {
            Integer intRowNo = Integer.valueOf(rowNo);
            for(WrapperApplication objWrapper: lstWrapperSection[intRowNo -1].lstWrapperQuestion)
            {
                
                
                if(objWrapper.objQuestion.pepFieldApiName__c =='Existing_Customer__c' && objWrapper.objQuestion.pepType__c == 'Button' )
                {
                    objApplication.put(objWrapper.objQuestion.pepFieldApiName__c,strSelected);
                    Cookie existingcustomer = new cookie('existingcustomer',strSelected,null,-1,false);
                    ApexPages.currentPage().setcookies(new cookie[]{existingcustomer});
                    
                }
            }
            
        }
        
    }
    
    // This method is used to load values from cookies
    
    Public void loadApplicationFromCookie(){
        if(ApexPages.currentPage().getcookies().get('existingcustomer') != null && ApexPages.currentPage().getcookies().get('existingcustomer').getvalue() != null && ApexPages.currentPage().getcookies().get('existingcustomer').getvalue() != '')
            objApplication.Existing_Customer__c=ApexPages.currentPage().getcookies().get('existingcustomer').getvalue();
        
    }   
}