objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CRM_Email__c</fullName>
        <label>Email</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Lead_Channel_Level_2__c</fullName>
        <label>Lead channel level 2</label>
        <picklist>
            <controllingField>CRM_Lead_Channel__c</controllingField>
            <picklistValues>
                <fullName>General Phone number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign specific phone number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSC transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_Lead_Channel__c</fullName>
        <label>Lead channel level 1</label>
        <picklist>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_Status_Reason__c</fullName>
        <label>Status reason</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Cannot Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit History</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insufficient Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Serious/Researching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postcode/Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot Contact Post Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Went Direct To New Lender</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn From Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRM_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>PAF</fullName>
        <active>true</active>
        <businessProcess>PAF</businessProcess>
        <label>PAF</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Party__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Company__c</fullName>
        <label>Company</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Create_New_Business_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create New Business Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_Create_New_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create New Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_Create_New_Person_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create New Person Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CRM_Name__c</fullName>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CRM_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Co Borrower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guarantor</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Party</label>
    <nameField>
        <displayFormat>A-{00}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Party</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LookUpController_Tracker.cls
/*------------------------------------------------------------
Author:        Sandip Bijlwan
Name:          LookUpController_Tracker 
Company:       Saasfocus
Description:   This is the Test Class for LookUpController
History
Date    :  29/09/2017     
------------------------------------------------------------*/
@isTest(SeeAllData=false)
Public class LookUpController_Tracker{
    
    public static Lead objLead;
    public static Party__c objParty;
    public static Account acc;
    public static Contact objContact;
    public static Account objAccount;
    
    
    /*----------------------------------------------------------------------------------
    Author:        Sandip Bijlwan
    Name:          createData
    Company:       Saasfocus
    Description:   creating data for test class
    Inputs:        
    Returns:       void
    -----------------------------------------------------------------------------------*/
    public static void createData(){
        objLead = new Lead();
        objLead.FirstName = 'test';
        objLead.LastName ='lastLeadName';
        objLead.Company = 'CompanyOfLead';
        objLead.CRM_Lead_Channel__c = 'Digital';
        objLead.CRM_Lead_Channel_Level_2__c = 'Email';
        objLead.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('PAF').getRecordTypeId();
        objLead.CRM_Status_Reason__c = 'Credit History';
        objLead.MobilePhone = '9999999999';
        insert objLead;
        
        objParty = new Party__c();
        objParty.CRM_Name__c = 'Name';
        objParty.CRM_Email__c  = 'N@gmail.com';
        objParty.CRM_Phone__c  = '1111111111';
        objParty.CRM_Type__c  = 'Co Borrower';
        objParty.CRM_Company__c  = 'C';
        objParty.Lead__c  = objLead.id;
        objParty.CRM_Create_New_Business_Account__c = True;
        objParty.CRM_Create_New_Contact__c  = True;
        objParty.CRM_Create_New_Person_Account__c = false;
        insert objParty;
        
        acc = new Account();
        acc.Name='WAT Automation Pty Ltd';
        insert acc;
        
        objContact = new Contact(
                            AccountId = acc.Id,
                            LastName = 'AutoContact kWemA27986',
                            FirstName = 'Test',
                            Email ='test@test.com',
                            MobilePhone='1234567890');

        insert objContact;
        
        objAccount = new Account();
        objAccount.LastName='testAcc';
        objAccount.Personmobilephone = '90909090909';
        insert objAccount;
           
    }
    
    
   /*----------------------------------------------------------------------------------
    Author:        Sandip Bijlwan
    Name:          lookupClassTest
    Company:       Saasfocus
    Description:   testing fetchAccount,fetchLead,fetchParty,fetchPersonAccount method
    Inputs:        
    Returns:       void
    -----------------------------------------------------------------------------------*/
    
    @isTest
    Public static void lookupClassTest(){
        
        LookUpController_Tracker.createData();
        
        Test.StartTest();
            List<CustomWrapp> lstContact = LookUpController.fetchAccount('Test AutoContact kWemA27986');
            List<CustomWrapp> lstLead = LookUpController.fetchLead('test');
            List<CustomWrapp> lstParty = LookUpController.fetchParty('Name');
            List<CustomWrapp> lstAccount = LookUpController.fetchPersonAccount('testAcc');
        Test.StopTest();
        
        system.assert(lstContact[0].mobilePhone == objContact.MobilePhone, 'worked');
        system.assert(lstLead[0].mobilePhone == objLead.MobilePhone , 'worked');
        system.assert(lstParty[0].mobilePhone == objParty.CRM_Phone__c , 'worked');
        system.assert(lstAccount[0].mobilePhone == objAccount.Personmobilephone , 'worked');
    }
    
    
}