objects/Monthly_Budget__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Monthly Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Monthly Budget</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Monthly Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RetrieveCode__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RetrieveCode</label>
</CustomObject>

classes/pepMonthlyBudget_Tracker.cls
@isTest(SeeAllData=False) private class pepMonthlyBudget_Tracker{
    
    @isTest static void pepMonthlyBudgetTest(){
        
         RetrieveCode__c objRetrieveCode = pepCommonTrackerController.createRetrieveCode();
         genesis__Applications__c objGenesisApp = genesis.TestHelper.createApplication();
         
         genesis__Application_Status_History__c obj = new genesis__Application_Status_History__c();
         obj.genesis__New_Value__c='APPROVED - CONVERTED TO CONTRACT';
         obj.genesis__Application__c=objGenesisApp.id;
         insert obj;
         
         Monthly_Budget__c objMonthlybudget = new Monthly_Budget__c();
         objMonthlybudget.Date__c=System.Today();
         objMonthlybudget.Amount__c=2000000;
         insert objMonthlybudget;
         
         Test.StartTest();
         
         pepMonthlyBudget objMonthlyBudgetBatch = new pepMonthlyBudget();
         ID MonthlyBudget = Database.ExecuteBatch(objMonthlyBudgetBatch);
         
         Test.Stoptest();
        
        
    }
    
    
}