objects/Mulesoft_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Mortgage_Last_Sync_Time__c</fullName>
        <label>Mortgage Last Sync Time</label>
        <type>DateTime</type>
    </fields>
    <label>Mulesoft Configuration</label>
</CustomObject>

objects/Pepper_Analytical_Snapshot__c.object
<CustomObject>
    <fields>
        <fullName>Amount_as__c</fullName>
        <label>Amount as</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ApplicationID_as__c</fullName>
        <label>ApplicationID as</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Date_as__c</fullName>
        <label>Application Date as</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Borrower_State_as__c</fullName>
        <label>Borrower State as</label>
        <picklist>
            <picklistValues>
                <fullName>VIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_as__c</fullName>
        <label>Channel as</label>
        <picklist>
            <picklistValues>
                <fullName>Pepper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_class_name_as__c</fullName>
        <label>Product class name as</label>
        <picklist>
            <picklistValues>
                <fullName>Near Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Detail__c</fullName>
        <label>Status Detail</label>
        <picklist>
            <picklistValues>
                <fullName>Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting New Settlement Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved Awaiting Outstanding Conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Approval with Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Documents Issued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Documents Received - Post Final Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Documents Received - Pre Final Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation of Solicitor Instructions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Settlement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Settlement Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitor Instructions Issued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_as__c</fullName>
        <label>Status as</label>
        <picklist>
            <picklistValues>
                <fullName>Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved in Principle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Documents Issued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Mortgage Analytical Snapshot</label>
    <nameField>
        <displayFormat>Snap-{000000}</displayFormat>
        <label>Pepper Analytical Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mortgage Analytical Snapshot</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pepper_Data__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ApplicationID__c</fullName>
        <externalId>true</externalId>
        <label>ApplicationID</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Date__c</fullName>
        <label>Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Borrower_State__c</fullName>
        <label>Borrower State</label>
        <picklist>
            <picklistValues>
                <fullName>VIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Pepper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_class_name__c</fullName>
        <label>Product class name</label>
        <picklist>
            <picklistValues>
                <fullName>Near Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Detail__c</fullName>
        <label>Status Detail</label>
        <picklist>
            <picklistValues>
                <fullName>Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting New Settlement Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved Awaiting Outstanding Conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Approval with Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Documents Issued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Documents Received - Post Final Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Documents Received - Pre Final Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation of Solicitor Instructions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Settlement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Settlement Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitor Instructions Issued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved in Principle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Documents Issued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Mortgage Application Data</label>
    <nameField>
        <displayFormat>Data-{0000000}</displayFormat>
        <label>Pepper Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mortgage Application Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Mortgage_Analytics_Batch.cls
// This batch class is used as an Anlytics Snapshot for Mortgage data
// --------------------------------------------------------------------------------------------- 
// Version#     Date              Author                 Description
// ---------------------------------------------------------------------------------------------
// 1.0       6-May-2016      Sumit Banarji           Initial Version
// ---------------------------------------------------------------------------------------------

global class Mortgage_Analytics_Batch implements Database.Batchable<sObject>, Database.Stateful
{ 
    //-------- Defining Global Variables -----//
	global Datetime lastSyncDateTime;
    global Datetime SyncStartDateTime;
	//----- End Defining Global Variables ----//

	/**
	* @Constructor
	* @Getting data from Custom Settings and initializing global variables.
	*/
    global Mortgage_Analytics_Batch()
    {
        SyncStartDateTime = Datetime.now();
        List<Mulesoft_Configuration__c> lstMC = Mulesoft_Configuration__c.getall().values();
        if (lstMC != null && lstMC.size() > 0) lastSyncDateTime = lstMC[0].Mortgage_Last_Sync_Time__c;
    }

	/**
	* @Batch query locator
	* @param BC 
	* @return Database.QueryLocator 
	*/
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator('Select CreatedDate, Amount__c, ApplicationID__c, Application_Date__c, Borrower_State__c, Channel__c, Product_class_name__c, Status_Detail__c, Status__c FROM Pepper_Data__c where LastModifiedDate >=: lastSyncDateTime and LastModifiedDate <: SyncStartDateTime ');
      
    }

	/**
	* @Execute Method used to process current context
	* @param BC 
	* @param scope 
	*/
    global void execute(Database.BatchableContext BC, List<Pepper_Data__c> scope)
    {
        List<Pepper_Analytical_Snapshot__c> listMortgAnlyticalSnpst = new List<Pepper_Analytical_Snapshot__c>();
        if(scope != null) for(Pepper_Data__c objAppdata : scope)
        {
			//------------ Creating new record for Analyics object ----------//
            Pepper_Analytical_Snapshot__c objMortgAnlyticalSnpst = new Pepper_Analytical_Snapshot__c();
            
            objMortgAnlyticalSnpst.Amount_as__c = objAppdata.Amount__c;
            objMortgAnlyticalSnpst.ApplicationID_as__c  = objAppdata.ApplicationID__c;
            objMortgAnlyticalSnpst.Application_Date_as__c   = objAppdata.Application_Date__c;
            objMortgAnlyticalSnpst.Borrower_State_as__c = objAppdata.Borrower_State__c;
            objMortgAnlyticalSnpst.Channel_as__c    = objAppdata.Channel__c;
            objMortgAnlyticalSnpst.Product_class_name_as__c = objAppdata.Product_class_name__c;
            objMortgAnlyticalSnpst.Status_Detail__c = objAppdata.Status_Detail__c;
            objMortgAnlyticalSnpst.Status_as__c     = objAppdata.Status__c;
			//--------- End Creating new record for Analyics object ----------//

			//Adding in the list to insert
            listMortgAnlyticalSnpst.add(objMortgAnlyticalSnpst);
        }
        if (listMortgAnlyticalSnpst.size() > 0) insert listMortgAnlyticalSnpst;    
    }

    /**
    * @Method used to run a process after finishing of batch
    * @param BC 
    */
    global void finish(Database.BatchableContext BC)
    {  
		//------- Updating last run timestamp in custom settings -----//
        List<Mulesoft_Configuration__c> lstMC = Mulesoft_Configuration__c.getall().values();
        if (lstMC != null && lstMC.size() > 0)
        { 
            lstMC[0].Mortgage_Last_Sync_Time__c = SyncStartDateTime;
            update lstMC;
        }
		//----- End Updating last run timestamp in custom settings --//
		//ChatterNotification.SendNotification(Label.Mortgage_Dashboard);
    }
}