objects/Mule_Batch_Job__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Id__c</fullName>
        <label>Batch Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <label>Job Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Mule Batch Job</label>
    <nameField>
        <displayFormat>MJOB{00000000}</displayFormat>
        <label>Mule Batch Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mule Batch Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mulesoft_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_ver__c</fullName>
        <label>API ver</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Handling_URL__c</fullName>
        <label>Error Handling URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Error_Recipient__c</fullName>
        <inlineHelpText>Please enter email id&apos;s of recipient. To whom error messages to be sent.</inlineHelpText>
        <label>Error Recipients</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mortgage_Last_Sync_Time__c</fullName>
        <label>Mortgage Last Sync Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mulesoft_Job_Url__c</fullName>
        <label>Mulesoft Job Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Mulesoft_Password__c</fullName>
        <label>Mulesoft Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mulesoft_User_Name__c</fullName>
        <label>Mulesoft User Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Password__c</fullName>
        <label>SF Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Token_Endpoint__c</fullName>
        <label>SF Token Endpoint</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>SF_User_Name__c</fullName>
        <label>SF User Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Instance_URL__c</fullName>
        <label>Salesforce Instance URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Success_Recipients__c</fullName>
        <label>Success Recipients</label>
        <type>TextArea</type>
    </fields>
    <label>Mulesoft Configuration</label>
</CustomObject>

classes/TestMulesoftBatchJobResult.cls
@isTest
public class TestMulesoftBatchJobResult
{
     static testMethod void MulesoftBatchJobResult() 
    { 
        Database.BatchableContext BC;
        Mulesoft_Configuration__c Mule =New Mulesoft_Configuration__c();
            Mule.Name='Mulesoft';
            Mule.API_ver__c='34.0';
            Mule.Client_Id__c='3MVG9Se4BnchkASmwj33vhYPd_QE9LxUiHnGD_sa93eiXJ9kqKzcjzoPtAN_b5kSvTq0Soxp9xHBx.xMZaD_J';
            Mule.Client_Secret__c='7150987666493593516';
            Mule.Error_Handling_URL__c='https://c.cs31.visual.force.com/apex/MulesoftBatchJobHandler';
            Mule.Error_Recipient__c='sumit.banarji@saasfocus.com ';
            Mule.Mulesoft_Job_Url__c='sumit.banarji@saasfocus.com ';
            Mule.Mulesoft_Password__c='P3pp3rPa55';
            Mule.Mulesoft_User_Name__c='pepper';
            Mule.Salesforce_Instance_URL__c='https://cs31.salesforce.com/home/home.jsp?sdtd=1';
            Mule.SF_Password__c='saasfocus@2016';
            Mule.SF_Token_Endpoint__c='https://test.salesforce.com/services/oauth2/token';
            Mule.SF_User_Name__c='siddharth.malhotra@pepper.com.au.clevel';
            Mule.Success_Recipients__c='sumit.banarji@saasfocus.com ';
            Mule.Mortgage_Last_Sync_Time__c=System.today()-3;
            Insert Mule;
        Mule_Batch_Job__c objMBJ = new Mule_Batch_Job__c();
            objMBJ.Batch_Id__c = 'B1';
            objMBJ.Job_Id__c = 'J1';
            insert objMBJ;
        Test.startTest();
        MulesoftBatchJobResult JobResult =New MulesoftBatchJobResult();
        Database.executebatch(JobResult);
         JobResult.start(BC);
        JobResult.finish(BC);
        Test.stopTest();
    }
}