objects/pages_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Page_Label__c</fullName>
        <label>Page_Label</label>
        <type>TextArea</type>
    </fields>
    <label>pages_config</label>
</CustomObject>

objects/pepCmsAnswer__c.object
<CustomObject>
    <fields>
        <fullName>pepActualValue__c</fullName>
        <label>Actual Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepCmsQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Question</label>
        <referenceTo>pepCmsQuestion__c</referenceTo>
        <relationshipLabel>Answer</relationshipLabel>
        <relationshipName>pepCmsAnswer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepDisplayText__c</fullName>
        <label>Display Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepSequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CMS Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsPage__c.object
<CustomObject>
    <fields>
        <fullName>pepPageName__c</fullName>
        <label>Page Name</label>
        <picklist>
            <picklistValues>
                <fullName>Landing Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apply Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App Login Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save &amp; Retrieve Functionality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Living Expenses Calculator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Header</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Footer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability Negative2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(verifyid)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup (Credit-Policy)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalise Repayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(FinancialDoc)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Consolidation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(Manual Upload)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Congratulations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(upload another Image)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SideBarTemplate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup (Bank-Detail)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsQuestion__c.object
<CustomObject>
    <fields>
        <fullName>pepCMSAnswer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Answer</label>
        <referenceTo>pepCmsAnswer__c</referenceTo>
        <relationshipLabel>Question</relationshipLabel>
        <relationshipName>pepCmsQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepFieldApiName__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepGenericErrorMessage__c</fullName>
        <label>Generic Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>pepLabelAfterQuestion__c</fullName>
        <label>Label (After Question)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepLabelPriorQuestion__c</fullName>
        <description>The text that will be displayed just before the question is rendered.</description>
        <label>Label (Prior Question)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepPage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Page</label>
        <referenceTo>pepCmsPage__c</referenceTo>
        <relationshipLabel>Question</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepSObjectApiName__c</fullName>
        <label>SObject API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepSequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HomePhone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Question</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PepFinaliseRepayment.cls
// ---------------------------------------------------------------------------------------------------------
// This class is used to calculate the repayment amount on the basis of frequency(weekly,fortnightly and monthly). 
// 
//      Date                       Author                
// ---------------------------------------------------------------------------------------------------------
//      5th Apr 2016           Rishabh Tyagi          
// ---------------------------------------------------------------------------------------------------------

public class PepFinaliseRepayment
{
public List<pepCmsQuestion__c> lstQuestion{get;set;} 
public List<wrappperQusetion> wrapperList{get;set;}
public decimal calculatedRepayment{get;set;}
public String selectedFrequency{get;set;}
public genesis__Applications__c objApplication{get;set;}
public transient Cookie cookieApplicationId; 
public String inputDate{get;set;}
public Boolean successSaveForLater{get;set;}

// This is used to initialize the variable and to assign values to different variables on page load.

public PepFinaliseRepayment()
 {
         objApplication = new genesis__Applications__c();
     //    objApplication.id = 'a5UN0000000959v';
         lstQuestion = new List<pepCmsQuestion__c>();
         wrapperList = new List<wrappperQusetion>();
         calculatedRepayment = 0;
         selectedFrequency = '';
         getCookieData();
         loadCMSContent();
         fetchApplication();
         if(objApplication.id !=null)
          {
            
             if(objApplication.Automated_Payment_Start_Date__c !=null)
             inputDate = (objApplication.Automated_Payment_Start_Date__c).format();
             if(objApplication.Debit_Amount__c !=null && objApplication.Debit_Amount__c !=0)
             calculatedRepayment = (objApplication.Debit_Amount__c).setScale(2) ;
             if(objApplication.Debit_Frequency__c !='' && objApplication.Debit_Frequency__c !=null)
                selectedFrequency = (objApplication.Debit_Frequency__c).tolowercase();
             if(selectedFrequency == 'bi-weekly')
                selectedFrequency = 'fortnightly';
             system.debug('freIS'+selectedFrequency);
         }    
 } 

// This method is to fetch application on the basis of application id.

   public void fetchApplication()
    {
            
            Map<string,string> childobjects = new Map<string,string>();       
            if(objApplication != null && objApplication.Id !=null)
            {
                
               List<genesis__Applications__c>  lstApplication  =pepInvokeCLMethodHelper.fetchApplications(null ,objApplication.Id,null,null,childobjects );
               System.debug('lstApplication  *********'+lstApplication);
                if(lstApplication != null && !lstApplication.isEmpty())
                {        
                    objApplication = lstApplication[0];
                }
            }
    }
 
 // Thid method id used to load data from CMS.
        
 public void loadCMSContent()
  {  
      for(pepCmsQuestion__c objQuestion:[select id,pepLabelPriorQuestion__c,pepType__c,pepLabelAfterQuestion__c,pepGenericErrorMessage__c,pepSequence__c,pepFieldApiName__c,pepSObjectApiName__c,
      (select id,pepActualValue__c,pepCmsQuestion__c,pepDisplayText__c,pepSequence__c from pepCMSAnswer__r order by pepSequence__c limit 3 ) from pepCmsQuestion__c  where pepPage__r.pepPageName__c ='Finalise Repayment' order by pepSequence__c])
      {  
          wrapperList.add(new wrappperQusetion(objQuestion));
      }
  }
 
 // This wrapper class is used to create container of frequncy option list(weekly,fortnightly and monthly) and other variables which is used in page.
 
 public class wrappperQusetion
 {
       public pepCmsQuestion__c objCmsQuestion {get; set;} //main question      
       public list<selectOption> lstOptions {get; set;}
 
    public wrappperQusetion(pepCmsQuestion__c objQuestion)
    {
       objCmsQuestion = objQuestion;
       lstOptions = new list<selectOption>();
      if(objQuestion != null && objQuestion.pepCmsAnswer__r!=null && objQuestion.pepCmsAnswer__r.size()>0)
       {
           for(pepCmsAnswer__c objAnswer : objQuestion.pepCmsAnswer__r)
                {
                   if(objAnswer.pepDisplayText__c !='' && objAnswer.pepDisplayText__c !=null)
                    {
                       lstOptions.add(new selectOption(objAnswer.pepDisplayText__c, objAnswer.pepDisplayText__c));
                    }
               }
      }
   }
 }

// This method is used to calculate the repayment amount on the basis of frquency.

public void calculateRepaymentValue()
 {
        system.debug('freqIs'+selectedFrequency);
        if(objApplication.genesis__Payment_Amount__c !=null && objApplication.genesis__Payment_Amount__c !=0)
        {
      
                       if(selectedFrequency=='weekly')
                       {
                           calculatedRepayment = (objApplication.genesis__Payment_Amount__c)/4;
                           objApplication.Debit_Frequency__c = 'WEEKLY';
                           objApplication.Automated_Payment_Start_Date__c = date.parse(inputDate);
                       }
                      else if(selectedFrequency=='fortnightly')
                      {
                          calculatedRepayment =(objApplication.genesis__Payment_Amount__c)/2;
                          objApplication.Debit_Frequency__c = 'BI-WEEKLY';
                          objApplication.Automated_Payment_Start_Date__c = date.parse(inputDate);
                      }
                      else  if(selectedFrequency=='monthly')
                      {
                          calculatedRepayment = (objApplication.genesis__Payment_Amount__c);
                          objApplication.Debit_Frequency__c = 'MONTHLY';
                          objApplication.Automated_Payment_Start_Date__c = date.parse(inputDate);
                      }
                    
                      else
                      {
                         calculatedRepayment = (objApplication.genesis__Payment_Amount__c);
                      }
                          calculatedRepayment  = calculatedRepayment.setScale(2);
        }
 } 

// This method is used to get cookies from previous page.
 
   public void getCookieData()
    {
             cookieApplicationId = ApexPages.currentPage().getCookies().get('ApplicationId');  
             
             if(cookieApplicationId !=null && cookieApplicationId.getValue() !=null && cookieApplicationId.getValue() !='')
            {                           
               objApplication.Id = pepEncryptDecryptData.DecryptData(String.valueof(cookieApplicationId.getValue()));
            }
             System.debug('CookieValueIs'+cookieApplicationId);
    }
  
    Public Pagereference checkcookie(){
        Pagereference pr=Peputilityclass.checkCookieAndRedirect();
        return pr;
        }
    
    //  This method is used to save the page name of current page in navigation status of application and sent notification(retrieval code)
  //  through SMS and Email to related account of respected application.

      public void saveForLater()
     {
            successSaveForLater=false;
           if(objApplication!=null && objApplication.id!=null)  
             {
                         genesis__Applications__c objApplicationReturn = new  genesis__Applications__c ();
                         objApplicationReturn = pepUtilityClass.SaveForLater(objApplication,'pepFinaliseRepayment') ; 
             
                        if(objApplicationReturn!=null && objApplicationReturn.id!=null)
                         {  
                                  successSaveForLater = true;
                                  system.debug('aplicationIs'+objApplicationReturn);
                                  
                         }     
               }                                  
      
     }

         
 // This method is used to update frequency and debit amount of application and to redirect on next page.
    
  public pagereference redirectToNextPage()
   {
            if(objApplication.Id !=null)
            {
                String strNavigationStatusPageName = pepUtilityClass.getNavigationPageName('pepLoanSetupCreditPolicy');
                objApplication.pepNavigation_Status__c = strNavigationStatusPageName;
                objApplication.Debit_Amount__c = calculatedRepayment;
                Map<String,List<SObject>> mapChildObjects = new Map<String,List<SObject>>();
                Map<String,SObject> mapRelatedObjects = new Map<String,SObject>();
                objApplication = pepInvokeCLMethodHelper.updateApplication(objApplication,mapRelatedObjects,mapChildObjects);
            }
            String redircetPageName= pages_config__c.getinstance('peploansetupcreditpolicy').Page_Label__c;
            pageReference objNextPage = new PageReference('/'+redircetPageName);
           // pageReference objNextPage = Page.pepLoanSetupCreditPolicy;
            objNextPage.setCookies(new Cookie[]{cookieApplicationId}); 
            objNextPage.setRedirect(true);
            return objNextPage;
    }        
 
}