objects/pages_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Page_Label__c</fullName>
        <label>Page_Label</label>
        <type>TextArea</type>
    </fields>
    <label>pages_config</label>
</CustomObject>

objects/pepCmsPage__c.object
<CustomObject>
    <fields>
        <fullName>pepPageName__c</fullName>
        <label>Page Name</label>
        <picklist>
            <picklistValues>
                <fullName>Landing Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apply Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App Login Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save &amp; Retrieve Functionality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Living Expenses Calculator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Header</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Footer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability Negative2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(verifyid)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup (Credit-Policy)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalise Repayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(FinancialDoc)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Consolidation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(Manual Upload)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Congratulations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(upload another Image)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SideBarTemplate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup (Bank-Detail)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsQuestion__c.object
<CustomObject>
    <fields>
        <fullName>pepFieldApiName__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepGenericErrorMessage__c</fullName>
        <label>Generic Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>pepLabelPriorQuestion__c</fullName>
        <description>The text that will be displayed just before the question is rendered.</description>
        <label>Label (Prior Question)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepPage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Page</label>
        <referenceTo>pepCmsPage__c</referenceTo>
        <relationshipLabel>Question</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>pepCmsQuestion__c</referenceTo>
        <relationshipName>CmsQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepSObjectApiName__c</fullName>
        <label>SObject API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepSection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Section</label>
        <referenceTo>pepCmsSection__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>pepQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pepSequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HomePhone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Question</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsSection__c.object
<CustomObject>
    <fields>
        <fullName>pepHeader__c</fullName>
        <label>Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pepPage__c</fullName>
        <label>Page</label>
        <referenceTo>pepCmsPage__c</referenceTo>
        <relationshipName>pepSection</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>pepSectionBodyRich__c</fullName>
        <label>Section Body (Rich)</label>
        <length>130000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>pepSectionBody__c</fullName>
        <label>Section Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>pepSectionStoryRich__c</fullName>
        <label>Section Story</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>pepSectionStory__c</fullName>
        <label>Section Story</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>pepSectionUniqueName__c</fullName>
        <label>Section Unique Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>pepSequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Running Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>CMS Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ServiceabilityNegativeTask__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>User_Id__c</fullName>
        <label>User Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>ServiceabilityNegativeTask</label>
</CustomObject>

classes/pepServiceabilityController.cls
/*
This Class is used to handle the working of pepserviceabilityPositive/pepservicebilityNegative1/2/3 Pages.
Added by Varun(Code Refactoring) on August 26,2017
*/
public class pepServiceabilityController {
    
    public list<pepCmsSection__c> lstSection{get;set;}
    public string strSectionHeader{get;set;}
    public Id idApplication{get;set;} 
    public string strPurpose{get;set;}
    public List<genesis__Applications__c> lstApp{get;set;}
    public string strSectionBody{get;set;}
    public string strSectionBody2{get;set;}
    public string strSectionBody3{get;set;}
    
    public string YesOrNo{get;set;}
    private ApexPages.StandardController stdController;
    public pepCmsModelContainer objModel {get; set;}
    public string strFirstName{get;set;}
    public string strMobileNo{get;set;}
    public Id accountId{get;set;}
    public string strAppNumber {get;set;}
    public string strThanksMsz{get;set;}
    
    public pepCmsModelContainer modelConInst {get; set;}
    public boolean isError{get;set;}
    public boolean displayMsz{get;set;}
    public list<pepCmsQuestion__c> lstQuestion{get;set;}
    public static string strMsz{get;set;}
    list<pepCmsSection__c> lstSection1;
    public string strPageName{get;set;}
    public list<pepCmsSection__c> lstsectionHeader{get;set;}
    
    public String Page_Name{get;set;}//Added by KG
    public String Page_Label{get;set;}//Added by KG
    //Constructor to load the prerequisites  for various methods used in the page ahead.
    public pepServiceabilityController(ApexPages.StandardController controller) { 
    
        page_Name=ApexPages.currentPage().getUrl();//Added by KG
        page_Name=page_Name.substring(page_Name.contains('/apex')?6:1,page_Name.contains('?')?page_Name.indexof('?'):page_Name.length());//Added by KG
        Page_Label=pages_config__c.getValues(page_Name.toLowerCase()).Page_Label__c;//Added by KG
        
        modelConInst = new pepCmsModelContainer();           
        lstsectionHeader =  new list<pepCmsSection__c>();
        isError =false;
        displayMsz = false;
        lstSection1 = new list<pepCmsSection__c>();
        lstSection =  new list<pepCmsSection__c>();
        
        string strURL = ApexPages.currentPage().getUrl();          
        if(strURL.contains('?'))
        {
            strURL = strurl.substringBefore('?');
        }
        
        lstsectionHeader  = [select id , pepSectionBodyRich__c , pepSectionUniqueName__c,pepSequence__c from pepCmsSection__c where pepPage__r.pepPageName__c = 'Header' order by pepSequence__c ASC];
        
        //Decline
        if(strURL == '/apex/pepServiceabilityPositve' || strURL == '/pepServiceabilitypositve' )
        {
            strPageName = 'Serviceability';    
        }   
        if(strURL == '/apex/pepServiceabilitynegative2' || strURL == 'pepServiceabilitynegative2' || strURL == '/apex/pepServiceabilitynegative1' || strURL == 'pepServiceabilitynegative1' || strURL=='/apex/pepServiceabilitynegative3' || strURL=='pepServiceabilitynegative3')      
            strPageName = 'Serviceability Negative2'; 
        
        if(strURL == '/apex/pepServiceabilityNegative' || strURL == 'pepServiceabilityNegative')    
            strPageName = 'Serviceability';  
        
        strAppNumber ='';
        strSectionHeader='';
        lstQuestion = new list<pepCmsQuestion__c>();
           
        getCookieData();
        fetchAffordibikityCheck();
    } 
    //Method to redirect the flow to PersonalDetailsPage.
    public pageReference getRedirect()
    {   
        //Modified by : Sushant Kumar -- added exception handling
        try {
            genesis__Applications__c  aps = new genesis__Applications__c(id=idApplication);
            genesis__Applications__c  app=peputilityclass.savecontinuestatus(aps,'pepPersonalDetails');
            string redircetPageName= pages_config__c.getinstance('peppersonaldetails').Page_Label__c;
            PageReference ref = new Pagereference('/'+redircetPageName); 
            ref.setRedirect(true);
            return ref;
        }
        catch(Exception ex) {
            
            return pepUtilityClass.handlePageException(ex);
        }

    }
    //method to reditrect the flow to landing Page.
    public pageReference getRedirectToLandingPage()
    {
        //Modified by : Sushant Kumar -- added exception handling
        try {
            string redircetPageName= Label.LandingPageRedirect;
            PageReference ref = new Pagereference(redircetPageName);
            ref.setRedirect(true);
            return ref;
        }
        catch(Exception ex) {
            
            return pepUtilityClass.handlePageException(ex);
        }

    }
    //This method will be used to get the cookie data.
    public void getCookieData()
    {
        Cookie cookieApplicationId = ApexPages.currentPage().getCookies().get('ApplicationId');  
        
        if(cookieApplicationId !=null && cookieApplicationId.getValue() !=null && cookieApplicationId.getValue() !='')
        {                           
            idApplication = pepEncryptDecryptData.DecryptData(String.valueof(cookieApplicationId.getValue()));
        }
        
    }
    
    //Calling Api of CloudLending for affordability check. 
    public void fetchAffordibikityCheck()
    {    
        Decimal decAmount;
        decimal decyear;
        String strpaymentFreQuency;
        string strcreditRating;
        Id idClPurpose;
        decimal decIndicativeInterestrate;
        isError = false;
        Map<string,string> childobjects = new Map<string,string>();
        list<Account> lstAcc =  new list<Account>();
        list<clcommon__CL_Product__c> lstCLP;
        list<pepCmsSection__c> lstSection;
        
        genesis.BorrowerAPI3 bApi = genesis.APIFactory.getBorrowerAPI3();
        genesis__Applications__c objApp = [select id, genesis__CL_Purpose__c, genesis__CL_Purpose__r.Name,genesis__Account__c from genesis__Applications__c where Id=: idApplication];
        
        strPurpose = objApp .genesis__CL_Purpose__r.Name;                                      
        lstApp  = pepInvokeCLMethodHelper.fetchApplications(null,idApplication,null,null,childobjects); 
        accountId = lstApp[0].genesis__Account__c; 
        
        if(lstApp!=null && lstApp[0].genesis__Account__c!=null)
        {
            lstAcc  = [select id, FirstName, Name, Phone, RecordType.Name from Account where Id=: lstApp[0].genesis__Account__c];
            
        }
        lstCLP = [select id,clcommon__Product_Name__c from clcommon__CL_Product__c where Id=: lstApp[0].genesis__CL_Product__c];
        
        lstSection = [select Id, Name, pepSectionUniqueName__c, pepSectionStoryRich__c, pepSectionStory__c,pepSectionBodyRich__c,pepSectionBody__c,
                                           pepHeader__c ,pepSequence__c,
                                           (select id, Name,pepSObjectApiName__c, pepFieldApiName__c, pepType__c , pepLabelPriorQuestion__c,
                                            pepGenericErrorMessage__c
                                            from pepQuestion__r order by pepSequence__c ASC)                                             
                                           from pepCmsSection__c
                                           where pepPage__r.pepPageName__c=:strPageName order by pepSequence__c ASC];
        
        string roundedwithdollar = '$' + string.valueOf((lstApp[0].debit_amount__c).setScale(2));
        for(pepCmsSection__c objSection: lstSection)
        {
            //modified by : sushant kumar
            //replace multiple if with else if because all comparisons have only logical check on objSection.pepSectionUniqueName__c
            if(objSection.pepSectionUniqueName__c == 'ThanksMsz')
            {
                string strTemp1 = objSection.pepSectionBodyRich__c;
                strThanksMsz = strTemp1 ;
            }
            
            else if(objSection.pepSectionUniqueName__c =='Serviceabiltylast')
            {
                strSectionBody3 = objSection.pepSectionBodyRich__c;
                strSectionBody3 = strSectionBody3.replace('{!genesis__Applications__c.genesis__CL_Purpose__r.Name}', strPurpose);
            }
            else if(objSection.pepSectionUniqueName__c == 'Greeting') {
                strSectionHeader = objSection.pepHeader__c;
            }   
            
            else if(objSection.pepSectionUniqueName__c == 'Let See What we can do')
            {
                strSectionHeader = objSection.pepHeader__c;
            }
            
            else if(objSection.pepSectionUniqueName__c == 'Serviceability Section 2')
            {
                
                string str1 = objSection.pepSectionBodyRich__c;
                string str2 = str1.replace('{!genesis__Applications__c.genesis__Loan_Amount__c}', lstApp[0].genesis__Loan_Amount__c.format());
                str2 = str2.replace('{!genesis__Applications__c.pep_Loan_Type__c}', lstCLP[0].clcommon__Product_Name__c);
                str2 = str2.replace('{!genesis__Applications__c.genesis__CL_Purpose__r.Name}', strPurpose);
                str2 = str2.replace('{!objApplication.genesis__Interest_Rate__c}', String.valueOF(lstApp[0].genesis__Interest_Rate__c.setscale(2)));
                
                Decimal toround = lstApp[0].debit_amount__c;
                Decimal rounded = toround.setScale(2);
                
                str2 = str2.replace('{!genesis__Applications__c.Debit_amount__c}', roundedwithdollar);
                
                if(lstApp[0].Debit_Frequency__c == 'BI-WEEKLY')
                {    
                    lstApp[0].Debit_Frequency__c = 'fortnightly';
                }
                             
                if(lstApp[0].Debit_Frequency__c != null && lstApp[0].Debit_Frequency__c != '')
                {
                    string frequency = lstApp[0].Debit_Frequency__c.tolowercase();
                    lstApp[0].Debit_Frequency__c = frequency;
                }

                str2 = str2.replace('{!genesis__Applications__c.Debit_Frequency__c}', lstApp[0].Debit_Frequency__c);
                strSectionBody = str2.replace('{!genesis__Applications__c.Requested_Term__c}', string.valueOf(lstApp[0].genesis__Term__c));
            }
            else if(objSection.pepSectionUniqueName__c == 'Serviceability Section 2a')
            {  
                string term = '';
                if(lstApp[0].genesis__Term__c != null)
                {
                    term = string.valueOf(lstApp[0].genesis__Term__c/12);
                }
                
                string str3 = objSection.pepSectionBodyRich__c;
                string str4 = str3.replace('${!genesis__Applications__c.Debit_amount__c}', roundedwithdollar);
                str4 = str4 .replace('{!genesis__Applications__c.Debit_Frequency__c}', lstApp[0].Debit_Frequency__c);
                strSectionBody2 = str4 .replace('{!genesis__Applications__c.Requested_Term__c}', term);
            }
            
            else if(objSection.pepSectionUniqueName__c == 'AppNumber')
            {
                string str7 = objSection.pepSectionBodyRich__c;
                strAppNumber = str7.replace('{!genesis__Applications__c.Name}',lstApp[0].Name  );             
            }
        }
    }
    
    public pageReference RedirectToEnd()
    {
        return null;
    }
    //This method will redirect the flow to Loan Details Page.
    public pageReference RedirectToLoanDetail()
    {
        YesOrNo = 'yes';
        PageReference ref;
        if(YesOrNo == 'yes')
        {
            string redircetPageName= pages_config__c.getinstance('peppersonaldetails').Page_Label__c;
            ref = new Pagereference('/'+redircetPageName); 
            ref.setRedirect(true);
        }       
        
        return ref;
    }
    //This method will be used to redirect the flow to pepServiceabilityNegative.
    public pageReference RedirectToNegative()
    {
        //modified by : sushant kumar
        //declared variable on top of the class
        PageReference ref;
        Map<String,SObject> relatedObjects = new Map<String,SObject>();
        Map<String,List<SObject>> childObjects = new Map<String,List<SObject>>();
        string redircetPageName;
        genesis__Applications__c objApplication;
        
        if(YesOrNo == 'no')
        {
            
            if(idApplication != null && String.valueof(idApplication) !='') {
                
                objApplication = new genesis__Applications__c(id=idApplication,genesis__Status__c='Closed'); 
                if(objApplication.Debit_Frequency__c == 'fortnightly')
                {    
                    objApplication.Debit_Frequency__c = 'BI-WEEKLY';
                }  
                objApplication.pepNavigation_Status__c = pepUtilityClass.getNavigationPageName('pepServiceabilityNegative3');  
                objApplication =  pepInvokeCLMethodHelper.updateApplication(objApplication,relatedObjects ,childObjects);
            }
            redircetPageName = pages_config__c.getinstance('pepServiceabilityNegative3').Page_Label__c;
        }
        if(YesOrNo == 'yes') {
            
            if(idApplication != null && String.valueof(idApplication) !='') {
                
                String navigationStatus = pepUtilityClass.getNavigationPageName('pepPersonalDetails');
                objApplication=new genesis__Applications__c(id=idApplication,genesis__Status__c='AWAITING PERSONAL INFORMATION',pepNavigation_Status__c=navigationStatus); 
                if(objApplication.Debit_Frequency__c == 'fortnightly')
                {    
                    objApplication.Debit_Frequency__c = 'BI-WEEKLY';
                }    
                objApplication =  pepInvokeCLMethodHelper.updateApplication(objApplication,relatedObjects ,childObjects);
            }
            redircetPageName = pages_config__c.getinstance('peppersonaldetails').Page_Label__c;
        }
        
        ref = new Pagereference('/'+redircetPageName); 
        ref.setRedirect(true);
        return ref;
    }
    
    public void setParam()
    {
        YesOrNo = 'yes';
    }
    //Assigning a Task for the user(credit officer currently working with the customer) to follow up the customer on flow going to ServiceabilityNegative.
    public void createTask()
    {
        modelConInst.strPageName='Serviceability';
        modelConInst.strSectionName='AccountInfo';
        modelConInst.ReadControlValue();   
        list<account> lstAcc;
        
        if(accountId !=null)
        {
           lstAcc = [select id, FirstName,LastName, Phone, RecordType.Name from Account where Id=: accountId limit 1];
            
            if( lstAcc[0].RecordType.Name == 'Person Account')
            {
                lstAcc[0].LastName = strFirstName;
            }
            
            lstAcc[0].PersonMobilePhone= strMobileNo;
            strThanksMsz = strThanksMsz.replace('{name}', strFirstName);
            try {
                update lstAcc;
            }
            catch(exception e) {
                
            }
            
            ServiceabilityNegativeTask__c assignedUser=ServiceabilityNegativeTask__c.getValues('userIdtoTask');
            Task t = new Task();
            t.OwnerId = assignedUser.User_Id__c;
            t.Subject = 'Call me back';
            t.Status = 'Open';
            t.Priority = 'Normal';
            t.WhatId = accountId ;
            t.ActivityDate = system.today().addDays(1);
            insert t;
        }
    }
    //This method will be used to check the cookie.
    Public Pagereference checkcookie(){
        //modified by : sushant Kumar
        //changed if-else cunstructs to turnery operator and added exception handling
        try {
            Pagereference pr = Peputilityclass.checkCookieAndRedirect();
            return (pr==null)? Peputilityclass.HandleRedirectSecurity() : pr;
        }
        catch(Exception ex) {
            return pepUtilityClass.handlePageException(ex);
        } 
    }
    
}