objects/pages_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Page_Label__c</fullName>
        <label>Page_Label</label>
        <type>TextArea</type>
    </fields>
    <label>pages_config</label>
</CustomObject>

objects/pepCmsPage__c.object
<CustomObject>
    <fields>
        <fullName>pepPageName__c</fullName>
        <label>Page Name</label>
        <picklist>
            <picklistValues>
                <fullName>Landing Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apply Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App Login Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save &amp; Retrieve Functionality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Living Expenses Calculator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Header</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Footer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serviceability Negative2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(verifyid)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup (Credit-Policy)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalise Repayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(FinancialDoc)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Consolidation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(Manual Upload)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Congratulations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup(upload another Image)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SideBarTemplate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup (Bank-Detail)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsSection__c.object
<CustomObject>
    <fields>
        <fullName>pepSectionBodyRich__c</fullName>
        <label>Section Body (Rich)</label>
        <length>130000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>pepSectionUniqueName__c</fullName>
        <label>Section Unique Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Running Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>CMS Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RetrieveCode__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RetrieveCode</label>
</CustomObject>

classes/pepServiceabilityRstController_Tracker.cls
@isTest(SeeAllData=False)

private class pepServiceabilityRstController_Tracker 
{
    
    @isTest static void pepServiceabilityResultsControllerTest0() {
        
        pepCommonTrackerController obj =new pepCommonTrackerController(); 
        pepCmsPage__c cmsPage = pepCommonTrackerController.createPage('Header');
        pepCmsSection__c cmsSection =  pepCommonTrackerController.createSection(cmsPage);
        cmsSection.pepType__c = 'Running Text';
        cmsSection.pepSectionUniqueName__c = 'Decline2';
        update cmsSection;
        cmsPage.pepPageName__c = 'Referred';
        update cmsPage;
        Account acc = pepCommonTrackerController.createAccount();
        test.startTest(); 
        genesis__Applications__c objApplication = new genesis__Applications__c();
        
        RetrieveCode__c objRetrieveCode = pepCommonTrackerController.createRetrieveCode();
        objApplication = genesis.TestHelper.createApplication();
        objApplication.Debit_Frequency__c ='bi-weekly';
        objApplication.genesis__Account__c = acc.id;
        update objApplication; 
        
        pages_config__c pg1 = new pages_config__c(Name='pepreferredpage',Page_Label__c='ReferredPage');
        insert pg1;
        pages_config__c pg2 = new pages_config__c(Name='peplandingpage',Page_Label__c='landingpage');
        insert pg2;
        
       test.stopTest(); 
        Pagereference pd=Page.pepReferredPage;
        Test.setcurrentPagereference(pd);
        Cookie Applicationid=new Cookie('Applicationid',pepEncryptDecryptData.EncryptData(String.valueof(objApplication.id)),'-1',null,false);
        pd.setcookies(new cookie[]{Applicationid});
        
        ApexPages.StandardController sc = new ApexPages.StandardController(acc);
        pepServiceabilityResultsController objClass = new pepServiceabilityResultsController (sc);
        objClass.createTask();
        objClass.getRedirectToLandingPage();
        PageReference redirectPage = objClass.checkcookie();
        System.assertEquals(null, redirectPage);
    }
    
    @isTest static void pepServiceabilityResultsControllerTest1() {
        
        pepCommonTrackerController obj1 =new pepCommonTrackerController(); 
        pepCmsPage__c cmsPage1 = pepCommonTrackerController.createPage('Header');
        pepCmsSection__c cmsSection1 =  pepCommonTrackerController.createSection(cmsPage1);
        cmsSection1.pepType__c = 'Running Text';
        cmsSection1.pepSectionUniqueName__c = 'ThanksContent';
        cmsSection1.pepSectionBodyRich__c = '{!ACCOUNT_NAME}ErichBody';
        update cmsSection1;
        cmsPage1.pepPageName__c = 'Decline';
        update cmsPage1;
        
        Account acc1= pepCommonTrackerController.createAccount();
        genesis__Applications__c objApplication1 = new genesis__Applications__c();
       test.startTest(); 
        RetrieveCode__c objRetrieveCode1 = pepCommonTrackerController.createRetrieveCode();
       test.stopTest(); 
        objApplication1 = genesis.TestHelper.createApplication();
        objApplication1.genesis__Account__c = acc1.id;
        update objApplication1;
        
        pages_config__c pg1 = new pages_config__c(Name='pepserviceabilitydecline',Page_Label__c='serviceabilitydecline');
        insert pg1;
        
        Pagereference pd1=Page.pepServiceabilityDecline;
        Test.setcurrentPagereference(pd1);
        Cookie Applicationid=new Cookie('Applicationid',pepEncryptDecryptData.EncryptData(String.valueof(objApplication1.id)),'-1',null,false);
        pd1.setcookies(new cookie[]{Applicationid});
       
        ApexPages.StandardController sc1 = new ApexPages.StandardController(acc1);
        pepServiceabilityResultsController objClass1 = new pepServiceabilityResultsController (sc1);
        System.assertEquals(true, objClass1.strThanksMsz.contains(acc1.firstname));
    }
    
    @isTest static void pepServiceabilityResultsControllerTest2() {
        
        pepCommonTrackerController obj2 =new pepCommonTrackerController(); 
        pepCmsPage__c cmsPage2 = pepCommonTrackerController.createPage('Header');
        pepCmsSection__c cmsSection2 =  pepCommonTrackerController.createSection(cmsPage2);
        cmsSection2.pepType__c = 'Running Text';
        cmsSection2.pepSectionUniqueName__c = 'ThanksContentDecline';
        cmsSection2.pepSectionBodyRich__c = '{!ACCOUNT_NAME}ErichBody1';
        update cmsSection2;
        cmsPage2.pepPageName__c = 'Decline';
        update cmsPage2;
        
        Account acc2= pepCommonTrackerController.createAccount();
        
        genesis__Applications__c objApplication2 = new genesis__Applications__c();
       test.startTest();
        RetrieveCode__c objRetrieveCode2 = pepCommonTrackerController.createRetrieveCode();
        objApplication2 = genesis.TestHelper.createApplication();
        objApplication2.genesis__Account__c = acc2.id;
        update objApplication2;
        
        pages_config__c pg1 = new pages_config__c(Name='pepserviceabilitydecline',Page_Label__c='serviceabilitydecline');
        insert pg1;
        
       test.stopTest(); 
        Pagereference pd2=Page.pepServiceabilityDecline;
        Test.setcurrentPagereference(pd2);
        Cookie Applicationid=new Cookie('Applicationid',pepEncryptDecryptData.EncryptData(String.valueof(objApplication2.id)),'-1',null,false);
        pd2.setcookies(new cookie[]{Applicationid});
        
        ApexPages.StandardController sc2 = new ApexPages.StandardController(acc2);
        pepServiceabilityResultsController objClass2 = new pepServiceabilityResultsController (sc2);
        System.assertEquals(true, objClass2.strThanksMsz.contains(acc2.firstname));
    }
    
}