objects/pepCmsPage__c.object
<CustomObject>
    <label>CMS Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsQuestion__c.object
<CustomObject>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HomePhone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Question</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsSection__c.object
<CustomObject>
    <fields>
        <fullName>pepSectionUniqueName__c</fullName>
        <label>Section Unique Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Running Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>CMS Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PepForgotSetPassword_Tracker.cls
@isTest public class PepForgotSetPassword_Tracker{

  @isTest static void PepForgotSetPasswordTest(){
  
        String password ='test';
        String confirmPassword ='test';
    
        pepCommonTrackerController obj =new pepCommonTrackerController();
        pepCmsPage__c objPage = pepCommonTrackerController.createPage('Login Screen');
        pepCmsSection__c objSection = new pepCmsSection__c();
        objSection = pepCommonTrackerController.createSection(objPage);
        objSection.pepSectionUniqueName__c ='SectionFour(FSP)';
        System.debug(objSection);        
        pepCmsQuestion__c objQuestion = pepCommonTrackerController.createCmsQuestion(objPage,objSection);
        objQuestion.pepType__c='Forgot Set Password';
        
        PepForgotSetPassword objForgotSetPassword = new PepForgotSetPassword();
        
        objForgotSetPassword.resetPassword();
        

  }
  
  @isTest static void PepForgotSetPasswordTest1(){
  
        
        
    
        pepCommonTrackerController obj =new pepCommonTrackerController();
        pepCmsPage__c objPage = pepCommonTrackerController.createPage('Login Screen');
        pepCmsSection__c objSection = new pepCmsSection__c();
        objSection = pepCommonTrackerController.createSection(objPage);
        objSection.pepSectionUniqueName__c ='SectionFour(FSP)';
        System.debug(objSection);        
        pepCmsQuestion__c objQuestion = pepCommonTrackerController.createCmsQuestion(objPage,objSection);
        objQuestion.pepType__c='Forgot Set Password';
        
        PepForgotSetPassword objForgotSetPassword = new PepForgotSetPassword();
        objForgotSetPassword.password='test';
        objForgotSetPassword.confirmPassword='testdddd';
        
        objForgotSetPassword.resetPassword();
        
        

        


  }
  
  
  
  
}