objects/pepCmsPage__c.object
<CustomObject>
    <label>CMS Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/pepCmsSection__c.object
<CustomObject>
    <fields>
        <fullName>pepSectionBodyRich__c</fullName>
        <label>Section Body (Rich)</label>
        <length>130000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>pepSectionUniqueName__c</fullName>
        <label>Section Unique Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>pepType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Running Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>CMS Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/pepcmscomponent_Text_Tracker.cls
@isTest public class pepcmscomponent_Text_Tracker {
    
    
    @isTest static void pepcmscomponent_TextTest(){
      test.startTest();  
         pepCmsPage__c objPage1 = new pepCmsPage__c();
         objPage1 = pepCommonTrackerController.createPage('Loan Details');
        
        
         pepCmsSection__c objSection2 = new pepCmsSection__c();
         objSection2 = pepCommonTrackerController.createSection1(objPage1);
         objSection2.pepSectionUniqueName__c ='pqr';
         objSection2.pepType__c='Help Text';
         objSection2.pepSectionBodyRich__c='test body rich';
         update objSection2;
      
         pepCmsSection__c objSection3 = new pepCmsSection__c();
         objSection3 = pepCommonTrackerController.createSection1(objPage1);
         objSection3.pepSectionUniqueName__c ='lmn';
         objSection3.pepType__c='Running Text';
         update objSection3;
        
         pepCmsSection__c objSection4 = new pepCmsSection__c();
         objSection4 = pepCommonTrackerController.createSection1(objPage1);
         objSection4.pepSectionUniqueName__c ='lmno';
         objSection4.pepType__c='Running';
         update objSection4;
        
         pepCmsSection__c objSection5 = new pepCmsSection__c();
         objSection5 = pepCommonTrackerController.createSection1(objPage1);
         objSection5.pepSectionUniqueName__c ='lmnop';
         objSection5.pepType__c='Running';
         update objSection5;
         
         pepCmsSection__c objSection6 = new pepCmsSection__c();
         objSection6 = pepCommonTrackerController.createSection1(objPage1);
         objSection6.pepSectionUniqueName__c ='Decline2';
         objSection6.pepType__c='Running Text';
         update objSection6;

//instance of class        
         pepcmscomponent_Text objpapcmscomponent = new pepcmscomponent_Text();
         objpapcmscomponent.strSectionName='pqr';
         objpapcmscomponent.strPageName='Loan Details';
         objpapcmscomponent.getRenderSection();
        
         pepcmscomponent_Text objpapcmscomponent1 = new pepcmscomponent_Text();
         objpapcmscomponent1.strSectionName='lmn';
         objpapcmscomponent1.strPageName='Loan Details';
         objpapcmscomponent1.getRenderSection();
        
         pepcmscomponent_Text objpapcmscomponent2 = new pepcmscomponent_Text();
         objpapcmscomponent2.strSectionName='lmno';
         objpapcmscomponent2.strPageName='Loan Details';
         objpapcmscomponent2.getRenderSection();
        
         pepcmscomponent_Text objpapcmscomponent3 = new pepcmscomponent_Text();
         objpapcmscomponent3.strSectionName='lmnopp';
         objpapcmscomponent3.strPageName='Loan Details';
         objpapcmscomponent3.getRenderSection();
         
         pepcmscomponent_Text objpapcmscomponent4 = new pepcmscomponent_Text();
         objpapcmscomponent4.strSectionName='Decline2';
         objpapcmscomponent4.strPageName='Loan Details';
         objpapcmscomponent4.getRenderSection();
     test.stopTest();    
    }
    
    

}