objects/PL_Broker_Accreditation__c.object
<CustomObject>
    <fields>
        <fullName>P1__c</fullName>
        <description>Parameter to store random string</description>
        <label>P1</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>PL Broker Accreditation</label>
    <nameField>
        <displayFormat>PL-{00000000}</displayFormat>
        <label>PL Broker Accreditation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PL Broker Accreditations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PL_Broker_Accreditation_TriggerHandler.cls
/*------------------------------------------------------------
    Author:        	Sean Jolly
    Name:          	PLBrokerAccreditationController
    Company:       	Pepper
    Description:   	Handles all trigger related operations of the PL_Broker_Accreditation_Trigger trigger on PL_Broker_Accreditation__c
	Test Class : 	PL_Broker_Accreditation_TriggerTest
    History
    20171113     	Sean Jolly     Class Created
    ------------------------------------------------------------*/


public class PL_Broker_Accreditation_TriggerHandler {

        /*------------------------------------------------------------
        Author:        Sean Jolly
        Name:          onBeforeInsert
        Company:       Pepper
        Description:   Handles all actions to be done before insert of records
        Inputs:        List of PL_Broker_Accreditation__c objects
        Returns:       void
        History
        20171113     	Sean Jolly     Method Created
        ------------------------------------------------------------*/ 
    
    public void onBeforeInsert(List<PL_Broker_Accreditation__c> lstNew)
    {        
        populateP1RandomString(lstNew);
    }
 
        /*------------------------------------------------------------
        Author:        Sean Jolly
        Name:          onBeforeInsert
        Company:       Pepper
        Description:   Calls the generate random string method for each object in the list, and sets P1 on each object to the returned random string.
        Inputs:        List of PL_Broker_Accreditation__c objects
        Returns:       void
        History
        20171113     	Sean Jolly     Method Created
        ------------------------------------------------------------*/     
    
    public void populateP1RandomString(List<PL_Broker_Accreditation__c> lstNew){
        for(PL_Broker_Accreditation__c obj : lstNew)
        {
            obj.P1__c = GenerateRandomString.generateRandomString(20);
        }
    }
}