objects/ScCollection_Bucket_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used for the bucketing of the contracts on the basis of days past due value on the contract object</description>
    <label>Bucket Configuration</label>
</CustomObject>

objects/ScCollection_Funders_Target__c.object
<CustomObject>
    <fields>
        <fullName>ScCollection_Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScCollection_Source_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source System</label>
        <referenceTo>collect__Source_System__c</referenceTo>
        <relationshipLabel>Funders Targets</relationshipLabel>
        <relationshipName>ScCollection_Funders_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ScCollection_Target__c</fullName>
        <label>Target</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Funders Target</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Funders Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funders Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScCollection_TestTrgOnFundersTarget.cls
@isTest(SeeAllData = False) Public Class ScCollection_TestTrgOnFundersTarget{


     @isTest static void test0(){
     
         collect__Source_System__c objSource  = ScCollection_CommonTrackerClass.createTestSourceSystem('PAF');
         
         ScCollection_Bucket_Configuration__c  cs = ScCollection_CommonTrackerClass.createTestBucketConfig();
         
         ScCollection_Funders_Target__c objFundTransfer = new ScCollection_Funders_Target__c();
         objFundTransfer.ScCollection_Source_System__c=objSource.id;
         objFundTransfer.ScCollection_Bank_Name__c = 'Hdfc';
         objFundTransfer.ScCollection_Target__c = 20;
         insert objFundTransfer;
     }
}