objects/ScCollection_Bulk_Scheduled_SMS__c.object
<CustomObject>
    <description>This Object is used to store information for scheduled SMS.</description>
    <fields>
        <fullName>ScCollection_Action_Code_Id__c</fullName>
        <label>Action Code Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScCollection_Contract_Id_s__c</fullName>
        <label>Contract Id&apos;s</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ScCollection_Job_Id__c</fullName>
        <description>This field is used to store the scheduled job Id</description>
        <label>Job Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScCollection_Review_Date__c</fullName>
        <label>Review Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ScCollection_SMS_Text__c</fullName>
        <label>SMS Text</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Bulk Scheduled SMS</label>
    <nameField>
        <displayFormat>BSMS-{0000000}</displayFormat>
        <label>Bulk Scheduled SMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Scheduled SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sms_Magic__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to store sms settings</description>
    <fields>
        <fullName>senderId__c</fullName>
        <label>senderId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sms Magic</label>
</CustomObject>

classes/ScheduleBulkSMSIfErrorTest.cls
/*------------------------------------------------------------
Author:        Sandip Bijlwan
Name:          ScheduleBulkSMSIfErrorTest 
Company:       Saasfocus
Description:   This class is use to test ScheduleBulkSMSIfError class.
History
Date    :  24/09/2017     
------------------------------------------------------------*/
@isTest(SeeAllData=false)
public class ScheduleBulkSMSIfErrorTest{
    
    public static collect__Source_System__c objSourceSystem;
    public static collect__Loan_Account__c objContract;
    public static collect__Action_Code__c objActioncode;
    public static loan__Loan_Account__c  objPLContract;
    
    
    /*------------------------------------------------------------------------------
    Author:        Sandip Bijlwan
    Name:          ScheduleSMSTest
    Company:       Saasfocus
    Description:   This method is use to test the apex method ScheduleSMS.
    Inputs:        
    Returns:       void
    -----------------------------------------------------------------------------------*/
    
    @isTest
    public static void ScheduleSMSTest(){
        
        objSourceSystem = ScCollection_CommonTrackerClass.createTestSourceSystem('PAF');
        objContract = ScCollection_CommonTrackerClass.createTestContract(objSourceSystem.Id);
        
        Sms_Magic__c objCustomSetting = new Sms_Magic__c();
        objCustomSetting.senderId__c ='PepperMoney';
        objCustomSetting.Name = 'CollectionSenderId';
        insert objCustomSetting;
        
        objActioncode = new collect__Action_Code__c(
                                            Name = 'Other',
                                            ScCollection_Is_Inbound_Action__c = false,
                                            ScCollection_Action_Code_Old_Value__c = 'Other1');
        insert objActioncode;
        ScCollection_Bulk_Scheduled_SMS__c objBulkSMS = new ScCollection_Bulk_Scheduled_SMS__c(
                                                                        ScCollection_Contract_Id_s__c = objContract.Id,
                                                                        ScCollection_Job_Id__c = 'testing',
                                                                        ScCollection_Review_Date__c = DateTime.newInstance(2017,9,27,14,840,50400),
                                                                        ScCollection_Action_Code_Id__c = objActioncode.Id,
                                                                        ScCollection_SMS_Text__c = 'Reminder: Your ');
        insert objBulkSMS;
        
        Test.StartTest();
            String strResponse = ScheduleBulkSMSIfError.ScheduleSMS(objBulkSMS.Id);
        Test.Stoptest();
        String str = strResponse.split('\\-')[0];
        System.assert(str == 'SUCCESS' ,'worked');
    }
    
}