objects/Sms_Magic__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to store sms settings</description>
    <fields>
        <fullName>senderId__c</fullName>
        <label>senderId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sms Magic</label>
</CustomObject>

classes/pepSMSmagicSendMessageHandler_Tracker.cls
@isTest(SeeAllData=False) private class pepSMSmagicSendMessageHandler_Tracker{

    @isTest static void pepSMSmagicSendMessageHandlerTest(){
    
        pepSMSmagicSendMessageHandler.sendSMS('','','');
        pepSMSmagicSendMessageHandler.sendSMS('sd','','');
        pepSMSmagicSendMessageHandler.sendSMS('asd','12','');
        

        pepSMSmagicSendMessageHandler.sendSMS('Test','123456','jhavduj');
        
        Sms_Magic__c objSms = new Sms_Magic__c();
        objSms.Name='senderId';
        objSms.senderId__c='Pep-Code';
        insert objSms;
        pepSMSmagicSendMessageHandler.sendSMS('Test','123456','jhavduj');
        
        
    }


}